.dockerignore, Dockerfile, requirements.txt
For a reproducible environment when testing and presumably for
deployment, we will run the app in a Docker container. Using Gunicorn
for a WSGI server, but only as a default.
=> Add a basic Dockerfile

Dockerfile, settings/common.py
Refactor of the project layout left a few module paths and directories
broken in settings and the Dockerfile.
=> Fix settings and Dockerfile to work with changed directory structure

.github/workflows/django.yml, README.md
This will report test coverage to codecov.io
=> Add code coverage report step to Github Actions

Makefile, common/fixtures/test-user-fixtures.json, common/jinja2/common/logged_out.jinja, common/jinja2/common/login.jinja, common/jinja2/layouts/layout.jinja, common/urls.py, common/views.py, settings/common.py
Temporarily, until we integrate with DIT SSO, add a user login and logout flow.
Also add a test user.
=> Add user login and logout

workbaskets/jinja2/includes/workbasket-list.jinja, workbaskets/serializers.py
* Format the workbasket list UI similarly to the prototype
* Fix the workbasket serializer to show the transaction ID if present and handle setting the approver
=> Fix workbasket serializer and UI

additional_codes/serializers.py, additional_codes/tests/bdd/conftest.py, additional_codes/tests/bdd/features/browse-additional-codes.feature, additional_codes/tests/bdd/features/detail_additional_codes.feature, additional_codes/tests/bdd/test_browse_additional_codes.py, additional_codes/tests/bdd/test_detail_additional_codes.py
* Scenarios for browsing and viewing additional codes added
* Serializer bugs with type SID and missing code field fixed
=> Add BDD tests for additional codes UI

commodities/jinja2/taric/footnote_association_goods_nomenclature.xml, commodities/jinja2/taric/goods_nomenclature.xml, commodities/jinja2/taric/goods_nomenclature_description.xml, commodities/jinja2/taric/goods_nomenclature_indent.xml, commodities/serializers.py, commodities/tests/conftest.py, commodities/tests/test_business_rules.py, commodities/tests/test_xml.py, commodities/urls.py, commodities/validators.py, commodities/views.py, common/tests/util.py, urls.py
A JSON API for the Goods Nomenclatures has also
been added for convenience.
=> TP-205: Add XML export for Goods Nomenclature.

footnotes/models.py
The queryset for footnote descriptions included only published descriptions and used a
non-existent SID as the identifying field.
This change uses the description period SID as the identifying field and selects
database-live descriptions.
=> Fix editing footnote description

footnotes/jinja2/taric/footnote_description.xml, footnotes/serializers.py
Should have description_period_sid, but had footnote_id instead
=> Fix footnote description xml template

common/jinja2/macros/common_elements.xml, common/tests/factories.py, common/tests/test_models.py, common/tests/util.py, quotas/jinja2/taric/quota_association.xml, quotas/jinja2/taric/quota_blocking.xml, quotas/jinja2/taric/quota_definition.xml, quotas/jinja2/taric/quota_event.xml, quotas/jinja2/taric/quota_event_types.jinja, quotas/jinja2/taric/quota_order_number.xml, quotas/jinja2/taric/quota_order_number_origin.xml, quotas/jinja2/taric/quota_order_number_origin_exclusion.xml, quotas/jinja2/taric/quota_suspension.xml, quotas/serializers.py, quotas/tests/test_xml.py, quotas/urls.py, quotas/views.py, urls.py
* Added views and TARIC3 XML templates for quotas
* QuotaEvent model requires some workarounds for handling the multiple event types
represented by a single model
* Added a simple macro for validity_period fields in the XML
=> Add XML exporter for quotas

common/tests/factories.py, footnotes/import_handlers.py, footnotes/import_parsers.py, footnotes/serializers.py, footnotes/tests/test_importer.py, importer/handlers.py
=> TP-297 add footnotes importer

.github/workflows/django.yml
Forgot to copy a line from the PR build workflow
=> Fix documentation build on merge to master

package-lock.json, package.json
Also add a couple of packages to remove warnings
=> Apply node-forge security update

importer/management/commands/import_countries.py, importer/management/commands/import_gsp.py, importer/management/commands/import_indents.py, importer/management/commands/import_sheet.py, importer/management/commands/import_ukgt.py
Small change to display helpful error if author is not present (My version being mis-configured like this was the first issue I hit attempting to run UKGT locally)
=> Measure tweaks and UKGT import script - Prompt user for author if it doesn't exist.

docs/adr/0004-xml-export-and-import.rst, docs/adr/0009-record-generated-envelopes.rst
Here are some new ADRs that are the result of TP-156 exploration. They are "discussion-ready" but not necessarily completely thought through yet.
0008 is probably not hugely controversial.
0009 is a bit moreso, and likely less well motivated too.
=> New ADRs for discussion

.dockerignore, Dockerfile, docker-compose.yml, exporter/storages.py, exporter/tasks.py, exporter/tests/test_exporter_commands.py, exporter/tests/test_exporter_tasks.py
Re-add exporter tests.
Catch up changes to docker-compose, Dockerfile.
=> Tp 464 fixup exporter tests

common/jinja2/layouts/layout.jinja, common/static/common/scss/_layout.scss
Jira Ticket: [TP-527](https://uktrade.atlassian.net/browse/TP-527)
Updates the header of the layout to fit the designs. 
- Changed service title to represent the designs
- Moved the nav to the same line as the service title and logo, this change only affects the desktop viewport. Will need to be assessed when we add the workbasket into the nav.
**Desktop**
**Tablet**
**Mobile**
=> TP-527 Style header component

.github/workflows/check-pr.yml, .github/workflows/django.yml, README.md, package.json
Bumping node version to 14.15.3 in an attempt to fix staging deployment error
=> Bump node version to fix deployment error

.dockerignore, additional_codes/business_rules.py, additional_codes/tests/test_business_rules.py, certificates/tests/test_business_rules.py, commodities/tests/test_business_rules.py, commodities/tests/test_importer.py, common/models/records.py, common/tests/test_models.py, conftest.py, footnotes/tests/test_business_rules.py, geo_areas/tests/test_business_rules.py, importer/cache/redis.py, importer/handlers.py, importer/management/commands/chunk_taric.py, importer/management/commands/patterns.py, importer/nursery.py, measures/tests/test_business_rules.py, quotas/tests/test_business_rules.py, quotas/tests/test_xml.py, regulations/tests/test_business_rules.py, workbaskets/tests/test_models.py
Adds new docstrings to a few niche functions and methods.
Cleans up some of the tests and makes the business rule error
checking more specific.
=> Minor refactor and documentation.

.github/workflows/django.yml, .profile, Makefile, Procfile, README.md, manifest.yml, package.json, settings/common.py, settings/dev.py
It is a requirement to conform the deployment setup to be inline
with the rest of DITs apps. This commit updates the settings,
Procfile, manifest, READEME and Github actions to be inline with this.
A .profile file has also been added to facilitate the static files system.
=> TP-503: Add deployment configuration.

additional_codes/jinja2/additional_codes/list.jinja, additional_codes/views.py
- Fixing bugs with settings access and incorrect ternary
=> TP-540 Fix pagination component 

additional_codes/filters.py, additional_codes/forms.py, additional_codes/jinja2/additional_codes/list.jinja, additional_codes/jinja2/includes/additional_codes_list.jinja, additional_codes/models.py, additional_codes/tests/bdd/test_detail_additional_codes.py, additional_codes/urls.py, additional_codes/validators.py, additional_codes/views.py, common/filters.py, common/jinja2.py, common/static/common/scss/_layout.scss, common/views.py, footnotes/views.py, requirements.txt, settings/common.py
Implements the search features for additional codes, alongside making various code changes to make everything a little cleaner.
=> TP-568 Search Additional Codes

commodities/import_handlers.py, commodities/tests/test_importer.py
The EU TARIC we have recently processed contains a
number of instances of codes being end dated and
then subsequently updated to remove the end date.
In this case, the code is first updated and then
the successor removed. This breaks the import of
the successor because the importer expects an end
date to be on the replacing code in order to look
up the correct absorbing code, but it has just
been removed.
Instead, in this specific case we now look up the
absorbed link using the previous version of the
successor. As this is a deletion, the data should
in the XML should not have changed since the last
update so this is safe to do.
=> Handle successors deleted after their replacing code is unterminated

common/jinja2/layouts/list.jinja
Just a few small changes to get pagination looking prim and proper
- Use page_obj to get the current page
- Add govuk-link class to the next button
=> TP-540 Pagination tweaks

additional_codes/jinja2/includes/additional_codes_list.jinja, common/jinja2/layouts/list.jinja
Small refactor of bits and pieces to bring the list page for additional codes up to the most recent design 
- Populated status field with correct data
- Made the sid field bold and corrected some link styling
- Altered the generic search content to fit with designs (This may need to  be reviewed by content)
=> TP-532 Refactor additional code list page

additional_codes/jinja2/includes/additional_codes_list.jinja, additional_codes/jinja2/includes/tabs/core_data.jinja, additional_codes/jinja2/includes/tabs/descriptions.jinja
Small changes to the descriptions page, with unusable functionality being removed.
- Added a heading
- Styling changes (first field is bold)
- Removed the sidebar actions
=> TP-518 Refactor additional codes descriptions tab

additional_codes/jinja2/additional_codes/detail.jinja, additional_codes/jinja2/includes/tabs/version_control.jinja
Added the version control tab to additional codes
=> TP-519 Add additional codes version control tab

footnotes/jinja2/includes/footnotes/tabs/version_control.jinja
Refactored footnotes version control tab to fit with designs
=> TP-579 Refactor footnotes version control tab

footnotes/jinja2/includes/footnotes/tabs/descriptions.jinja
Refactored footnotes description tab to fit more with designs
=> TP-578 Refactor footnote descriptions tab

footnotes/jinja2/footnotes/detail.jinja
Only showing the type rather than the ID currently
=> TP-577 Refactor footnote details tab (#165)

commodities/tests/test_util.py, commodities/util.py, measures/tests/test_util.py, measures/util.py
The tests picked up on a few edge cases that should be taken care of.
=> Tiny PR to fix utils and add tests

measures/business_rules.py, measures/tests/test_business_rules.py
- Make sure ME32 doesn't consider older versions
or the same measure being passed if it is
already saved.
- Make sure ME32 considers measures on the same
goods code, not just parents and children.
=> More ME32 fixes and tests

additional_codes/filters.py, certificates/filters.py, certificates/jinja2/certificates/list.jinja, certificates/jinja2/includes/certificates_list.jinja, certificates/models.py, certificates/urls.py, certificates/views.py, common/jinja2/common/index.jinja
Adds functionality to view / search certificates into TAP
=> TP-174 View / Search certificates

additional_codes/jinja2/additional_codes/detail.jinja, additional_codes/jinja2/includes/tabs/descriptions.jinja, common/static/common/js/showHideCheckboxes.js, footnotes/jinja2/includes/footnotes/tabs/core_data.jinja, footnotes/jinja2/includes/footnotes/tabs/descriptions.jinja, footnotes/jinja2/includes/footnotes/tabs/version_control.jinja, footnotes/jinja2/includes/footnotes_list.jinja
Small tidbits for each to bring them up to standard with requirements (I didn't want to make 3 PRs)
**TP-578 / TP-579** 
Fixed casing issues
**TP-577** 
Added footnote type description
**TP-578** 
Unbolded start date column
**TP-580**
Fixed 'show more' button and moved usage to the details page
=> TP-577 / TP-578 / TP-579 / TP-580 General Cleanup

certificates/jinja2/certificates/detail.jinja, certificates/jinja2/includes/certificates/tabs/core_data.jinja, certificates/jinja2/includes/certificates_list.jinja, certificates/models.py, certificates/urls.py, certificates/views.py
Adds the details page for certificates 
Description does work, just a mistake when creating the records.
=> TP-172 Certificate details tab

certificates/filters.py, certificates/jinja2/includes/certificates_list.jinja
The long slashed words have risen again!
=> TP-174 Fixed breaking long words

certificates/jinja2/certificates/detail.jinja, certificates/jinja2/includes/certificates/tabs/version_control.jinja
Adds the version control tab for certificates
=> TP-608 Add certificate version control tab

common/models/records.py, common/tests/test_models.py
When checking actual current data `.current` works adequately.
However in many cases, especially the business rules this isn't
enough. In these cases the normal requirement is to check the
most current data for an object, or the data for the object in
the current transaction, or the data for the object in any
preceding transaction that is within the same workbasket as the
current transaction. Whichever has the greatest ID (so is most
recent) needs to be returned.
This commit adds a new QuerySet method called `current_as_of`
which takes a transaction and executes a query that satisfies
this requirement.
=> TP-609: Include objects up to a given transaction in .current

certificates/filters.py
- Stops the long slashed words in types breaking the container
- Uses the new active state mixin
=> TP-174 Fix certificate filter labels breaking container

certificates/business_rules.py, certificates/import_handlers.py, certificates/models.py
The certificate SID is only unique when considering the type as well.
=> Add type SID to certificate identifying fields

additional_codes/filters.py, additional_codes/jinja2/additional_codes/detail.jinja, common/filters.py, footnotes/filters.py
General code cleanup and small fixes 
- Changed additional codes detail to use the common detail template 
- Added common start year filter 
- Added missing active state filter imports 
- Changed additional codes to use the common `active_state` and `start_year` filters 
- Changed footnotes to use the common `active_state` and `start_year` filters
=> Add common filters and refactor additional code detail

.pre-commit-config.yaml, geo_areas/filters.py, geo_areas/jinja2/geo_areas/detail.jinja, geo_areas/jinja2/geo_areas/list.jinja, geo_areas/jinja2/includes/geo_areas/list.jinja, geo_areas/jinja2/includes/geo_areas/tabs/core_data.jinja, geo_areas/jinja2/includes/geo_areas/tabs/memberships.jinja, geo_areas/jinja2/includes/geo_areas/tabs/version_control.jinja, geo_areas/urls.py, geo_areas/views.py
Refactored the 4 tabs for a single geographical area
=> TP-618 Refactor geographical areas tabs

additional_codes/jinja2/additional_codes/detail.jinja, certificates/jinja2/certificates/detail.jinja, common/jinja2/layouts/detail.jinja, footnotes/jinja2/footnotes/detail.jinja, geo_areas/jinja2/geo_areas/detail.jinja
Detail breadcrumb had hardcoded link text, made that dynamic using the same standard as list.
=> TP-172 Fix hardcoded breadcrumb

additional_codes/business_rules.py, certificates/business_rules.py, commodities/business_rules.py, common/business_rules.py, common/models/records.py, footnotes/business_rules.py, geo_areas/business_rules.py, measures/business_rules.py, quotas/business_rules.py, regulations/business_rules.py
Business rules must also account for objects in the current transaction (and
unapproved transactions up to the current one in the same workbasket). This
commit updates business rules queries to take this into account.
=> TP-615: Update business rules query top find objects in current transaction

common/filters.py, common/jinja2/common/index.jinja, common/jinja2/layouts/list_vertical.jinja, common/jinja2/macros/create_link.jinja, common/static/common/scss/_layout.scss, common/static/common/scss/_table.scss, common/static/common/scss/application.scss, footnotes/filters.py, measures/filters.py, measures/forms.py, measures/jinja2/includes/measures/conditions.jinja, measures/jinja2/includes/measures/list.jinja, measures/jinja2/measures/list.jinja, measures/urls.py, measures/views.py, urls.py
Add measures list view
- Had to pretty much build the form structure in the form file.
- Couldn't apply a class to the wrapper of some of the form fields, so had to do a janky `quarters` class approach to get the same style.
=> TP-610 Add measures search filter

commodities/models.py, measures/jinja2/includes/measures/list.jinja, measures/jinja2/includes/measures/tabs/core_data.jinja, measures/jinja2/measures/detail.jinja, measures/models.py, measures/urls.py, measures/views.py
Adds the detail page for measures
=> TP-639 Add measure details tabs

common/filters.py, common/jinja2/common/index.jinja, common/jinja2/layouts/list_vertical.jinja, common/static/common/scss/_table.scss, quotas/filters.py, quotas/forms.py, quotas/jinja2/includes/quotas/list.jinja, quotas/jinja2/quotas/list.jinja, quotas/urls.py, quotas/views.py
Added quotas list page with search and filter
=> TP-652 Find and view quotas

quotas/jinja2/includes/quotas/list.jinja, quotas/jinja2/includes/quotas/tabs/core_data.jinja, quotas/jinja2/quotas/detail.jinja, quotas/models.py, quotas/urls.py, quotas/views.py
Adds the detail page for quotas
=> TP-667 View quota details

additional_codes/__init__.py, certificates/__init__.py, commodities/__init__.py, common/models/mixins.py, common/models/records.py, docs/adr/0012-ordering-of-tariff-transactions.rst, docs/architecture/birds-eye.svg, docs/architecture/index.rst, docs/code.rst, docs/importer/index.rst, exporter/__init__.py, footnotes/__init__.py, geo_areas/__init__.py, hmrc_sdes/__init__.py, importer/__init__.py, measures/__init__.py, measures/business_rules.py, quotas/__init__.py, regulations/__init__.py, requirements.txt, taric/__init__.py, workbaskets/__init__.py
An architecture primer. Best viewed in the rendered documentation, so would recommend checking out this branch and building it.
=> TP-634 Architectural documentation.

.pre-commit-config.yaml
Add pre-commit hook to apply [`flynt`](https://github.com/ikamensh/flynt) to changed files
=> Add flynt to automatically convert to f-strings

common/jinja2/layouts/list.jinja, common/jinja2/layouts/list_vertical.jinja, measures/filters.py
- Changed pagination to comma separate large numbers 
- Fixed bug in third party class
=> TP-610 Fix measures list third party and tweak navigation

common/static/common/scss/_layout.scss, measures/forms.py
I have having this inability to add a class to the wrapper of components and thus having to add a class to the wrapper of the wrapper to access the initial wrapper
=> TP-610 move all radios to one line

measures/filters.py, measures/forms.py, measures/jinja2/includes/measures/list.jinja, measures/jinja2/includes/measures/tabs/core_data.jinja
Just changing 'geography' to 'geographical area' to standardise terminology
=> TP-610 Change geographical area field content

measures/jinja2/includes/measures/tabs/conditions.jinja, measures/jinja2/includes/measures/tabs/core_data.jinja, measures/jinja2/measures/detail.jinja, measures/models.py
Adds the conditions tab for measures 
I think the ordering we want may happen by default
=> TP-682 Add measures conditions tab

settings/common.py
Currently the URL configuration causes an error.
Simplify the config to be less error prone.
=> Simplifies redis URL configuration.

settings/common.py
CERT_REQUIRED is not the correct confifguration for an SSL
URL. Instead just "required" should be used.
=> Update redis URL configuration to use correct setting.

additional_codes/business_rules.py, additional_codes/tests/test_business_rules.py, commodities/business_rules.py, commodities/tests/test_business_rules.py
Found whilst importing the latest set of deltas. There is also TP-690 which isn’t fixed in this PR and will need a bit more attention.
=> More fixes for business rules NIG1, ACN4 and NIG5

measures/jinja2/includes/measures/tabs/conditions.jinja
It's exactly what it looks like
=> TP-682 Adjust conditions tab content

certificates/views.py, common/views.py
There was a typing typo, somebody typed "type" instead of "Type" which made the type inferator sad when it couldn't find the type and the site fell over.
=> Fix type vs Type typo.

additional_codes/forms.py, additional_codes/jinja2/includes/additional_codes/tabs/core_data.jinja, additional_codes/models.py, additional_codes/urls.py, additional_codes/views.py, certificates/jinja2/includes/certificates/tabs/core_data.jinja, common/jinja2/common/confirm_update.jinja, common/jinja2/common/edit.jinja, common/jinja2/includes/common/tabs/core_data.jinja, common/jinja2/layouts/form.jinja, common/static/common/scss/_layout.scss
Allows a user with permissions to edit additional codes
=> TP-653 Edit additional codes

regulations/jinja2/includes/regulations/list.jinja
=> List view: Don't use regulation group, use public identifier and link to legislation if present.

regulations/jinja2/includes/regulations/tabs/core_data.jinja
=> Regulation group shoud have a lower case G

common/jinja2/common/confirm_update.jinja, footnotes/jinja2/footnotes/confirm_update.jinja, footnotes/jinja2/footnotes/confirm_update_description.jinja, footnotes/jinja2/footnotes/edit.jinja, workbaskets/jinja2/includes/workbaskets/workbasket-list.jinja, workbaskets/jinja2/workbaskets/choose-or-create.jinja, workbaskets/jinja2/workbaskets/detail.jinja, workbaskets/views/decorators.py
Workbasket URLs have been namespaced. Update references to the URLs
to reflect this.
=> Fix references to workbasket URLs

regulations/jinja2/includes/regulations/list.jinja, regulations/jinja2/includes/regulations/tabs/core_data.jinja
This PR feels like new-design-final-final-2.psd
=> Settle on header for public identifier field as "Public identifier"

common/business_rules.py
It turns out that making a new subclass doesn't
cause most of the things we need to be inherited
by the new class, such as the Violation object and
the class' docstring. This results in cryptic
errors when the business rule fires. This new
method prevents that from happening by just
overriding the method.
As a bonus wrapped classes will now appear in
generated documentation.
=> TP-709 Fix messages on wrapped business rule classes

additional_codes/forms.py, additional_codes/models.py, additional_codes/urls.py, additional_codes/views.py, common/forms.py, common/jinja2/common/confirm_update_description.jinja, common/jinja2/common/edit_description.jinja, common/jinja2/includes/common/tabs/descriptions.jinja, common/models/__init__.py, common/models/mixins.py, common/urls.py, footnotes/models.py, workbaskets/jinja2/includes/workbaskets/workbasket-detail.jinja
Allow people to edit additional code descriptions
=> TP-662 Edit additional code descriptions

common/tests/test_validators.py, common/validators.py
Starting to chip away at some of the stuff that isn't well tested.
=> TP-656: Tests for common validators.

additional_codes/models.py, additional_codes/urls.py, common/forms.py, common/jinja2/common/edit_description.jinja, common/jinja2/includes/common/tabs/descriptions.jinja, common/static/common/scss/_table.scss, common/urls.py, footnotes/forms.py, footnotes/models.py, footnotes/urls.py, footnotes/views.py
Allow the ability to edit footnotes
=> TP-719 Edit footnote description

geo_areas/jinja2/includes/geo_areas/tabs/memberships.jinja, geo_areas/models.py, geo_areas/tests/bdd/features/detail_geo_areas.feature, geo_areas/tests/bdd/test_detail_geo_areas.py, geo_areas/tests/test_models.py
The Memberships view had been changed to only show memberships on groups. These commits also show memberships on members.
=> TP-746 Fix bug where geo area members don't show memberships

common/tests/test_views.py, common/views.py
* Removed unnecessary \<strong> elements in XML payload
* A bit DRYer
* Added some test coverage
=> Quick refactor of the healthcheck endpoint

common/forms.py, common/jinja2/components/autocomplete.jinja, common/jinja2/components/autocomplete/macro.jinja, common/models/records.py, common/static/common/js/application.js, common/static/common/js/autocomplete.js, common/static/common/scss/_accordion.scss, common/static/common/scss/_autocomplete.scss, common/static/common/scss/application.scss, measures/forms.py, measures/jinja2/includes/measures/tabs/core_data.jinja, measures/jinja2/measures/edit.jinja, measures/models.py, measures/urls.py, measures/views.py, package-lock.json, package.json, regulations/models.py, workbaskets/jinja2/includes/workbaskets/workbasket-detail.jinja
Adds the measures edit page, with an autocomplete for most fields. 
This PR does not currently include the duties or geographical area fields, they'll be added after this.
=> TP-695 Edit Measure detail

common/tests/test_models.py, conftest.py, docs/exporter/celery-tasks.rst, workbaskets/models.py, workbaskets/tests/test_models.py, workbaskets/tests/test_views.py
Triggers workbasket upload on setting workbasket to 'READY_TO_EXPORT'.
=> TP 650 - Schedule workbasket upload to bucket

geo_areas/models.py, measures/forms.py, measures/jinja2/measures/edit.jinja, measures/views.py
Adds ability to edit the geographical area of a measure
=> TP-695 Edit measure geographical area

additional_codes/models.py, common/models/records.py, common/tests/models.py, quotas/jinja2/taric/quota_order_number_origin.xml
-  Show remote fields in model `__str__` output
- Fix validity end date position in quota origin xml
=> Two tiny fixes to __str__ and quota origin XML

common/forms.py, common/jinja2/common/confirm_create.jinja, common/jinja2/common/confirm_update.jinja, common/jinja2/common/index.jinja, common/jinja2/components/description_help.jinja, common/jinja2/layouts/confirm.jinja, common/jinja2/layouts/create.jinja, common/models/records.py, common/util.py, footnotes/forms.py, footnotes/jinja2/footnotes/create.jinja, footnotes/urls.py, footnotes/views.py
Allow the user to create footnotes
=> TP-92 Create a new foonote

additional_codes/forms.py, additional_codes/jinja2/additional_codes/create.jinja, additional_codes/urls.py, additional_codes/views.py, common/jinja2/common/index.jinja
Allows the user to create additional codes
=> TP-770 Create Additional Codes

requirements.txt
Fix issue with skipped tests: https://github.com/getsentry/pytest-responses/issues/10
=> Bump pytest-responses.

exporter/sqlite/runner.py
Builds on #357 , but parses the environment variables using JSON.
I'm going to ask WebOps today about us deploying non-master branches in Jenkins, to avoid all this incremental PR approach to fixing deployment related issues.
=> TP859: Use json to parse env variables

footnotes/forms.py
This PR provides a fix for [TP-918](https://uktrade.atlassian.net/browse/TP-918).
=> Fix for Create Footnote 500 error response.

footnotes/tests/test_views.py, package-lock.json
Updates tar version (in response to Dependabot node alert).
=> Update tar version to 6.1.9

manifest.yml
A potential fix to our disk quota woes (for the SQLite updates) suggested by the Gov PaaS team.
=> Update disk quota

manifest.yml
Same principle as #370 for attempting to update the disk space we have allocated in PaaS, but with correct syntax this time round.
=> Update disk quota with correct syntax

README.md, manifest.yml, package-lock.json, package.json
Reverts uktrade/tamato#391 - because the buildpack isn't updated until Tuesday.
=> Revert "Update node version for buildpack changes"

importer/sheet.py, measures/parsers.py, measures/sheet_importers.py, measures/tests/test_sheet.py
TP-1040: Tweaks to the excel importer
Upon loading a create measures file provided by MTPO, we noticed we needed to make a few small tweaks to the excel importer.
A few small tweaks to the excel importer
=> TP-1040: Tweaks to the excel importer

importer/tasks.py, importer/tests/test_tasks.py
New PR, since the branch was named incorrectly before (and fix the failing test too).
=> Bugfix PR for change missed in TP-1045

.pre-commit-config.yaml, common/app_config.py, common/business_rules.py, common/exceptions.py, common/filters.py, common/jinja2.py, common/models/tracked_qs.py, common/models/trackedmodel.py, common/path_converters.py, common/querysets.py, common/urls.py, common/util.py, common/validators.py, common/views.py, docs/source/envvars.rst, docs/source/testing.rst, requirements.txt
Docstrings are valuable both for generating documentation automatically with Sphinx, and for use in some IDEs contextual help. Code can be self-documenting, but it is difficult to make the intention of the code author or the reasons for the decisions they take immediately comprehensible. In these cases, docstrings and inline comments help express that context.
* Add missing docstrings to the common app code
* Tidy up envvars documentation
* Simplify testing documentation to reduce the detail in the introduction, hopefully making it easier to read
=> TP-990 Common docstrings

docs/source/adr/0015-make-reverse-relations-aware-of-versions.rst
ADR for fixing reverse relations – please read the text and discuss :)
=> ADR-15: Make reverse relations aware of versions.

common/business_rules.py, common/models/tracked_qs.py
It turns out the recent changes to validity rules are not very performant when there are lots of joins involved, because the database has to compute validity dates for nearly all measures and then filter them to just the one or two are interested in.
Because the number of objects we expect to return from business rules is quite small, instead we materialize the result set for each join and just dispatch them as separate queries. This seems to be faster that allowing the database to do that.
=> TP2000-166: Improve performance of validity rules

Procfile, requirements.txt
Long running HTTP requests are almost entirely IO-bound, waiting on large and complex DB queries to complete. Tamato's web workers are currently synchronous and few in number. This PR allows a greater number of web workers to run asynchronously.
Integrates the gevent package supporting use of asynch request handling.
Requires installation of the gevent package (newly included and pinned in the project's `requirements.txt`.
=> Add async web worker support with gevent.

.pre-commit-config.yaml, certificates/validators.py, common/tests/test_transactions.py, footnotes/validators.py, importer/utils.py, regulations/path_converters.py, regulations/validators.py, requirements.txt, taric/models.py
We are all struggling with a broken dependency for `black`, so this commit updates all of our pre-commit linters and applies them to the entire codebase.
You will need to update dependencies and also ensure pre-commit has picked up the new plugin versions.
=> Update linters and apply resulting reformats.

manage.py
Remove a couple of print statements from manage.py.
=> Remove debug prints from manage.py

Dockerfile, docker-compose.yml
* Docker build currently fails on broken APT dependencies.
* Postgres docker image is misaligned with prod.
* Fix broken docker build.
* Align Postgres docker image with prod.
=> Docker tweaks

importer/management/commands/import_taric.py, importer/tasks.py
Add commodity code import option to import_taric management command.
To match the option in the GUI.
=> TP2000-346 - Add commodity code import option to import_taric management command.

docs/source/envvars.rst, requirements.txt
better_exceptions provides more readable exceptions and importantly outputs the values of variables.
This would be very handy for debugging celery tasks among other things.
=> Add better-exceptions to requirements.txt

workbaskets/management/commands/list_workbaskets.py, workbaskets/management/util.py
Allow outputting all approved workbaskets
Add status column to compact workbasket list output.
=> workbasket_list:  add status.   add ability to list all approved statuses.

common/static/common/scss/_components.scss, common/tests/test_views.py, pii-ner-exclude.txt, workbaskets/jinja2/includes/workbaskets/edit-workbasket-list.jinja, workbaskets/jinja2/workbaskets/select-workbasket.jinja, workbaskets/views/ui.py
* Statuses didn't exactly match those used in the system
* Makes filter bar more accessible
* Excludes archived, published and sent statuses
* Changes styling
=> TP2000-366 Workbasket list page design tweaks

common/models/trackedmodel.py, common/tests/test_models.py, measures/jinja2/includes/measures/tabs/conditions.jinja, measures/models.py, measures/tests/test_views.py
* Tariff managers need additional info on measure conditions tab
* Adds the sid to the measure conditions tab
* Adds a link to the measure conditions tab from the tariff changes list
=> TP2000-378 Add sid to conditions tab, add conditions link

measures/jinja2/includes/measures/tabs/version_control.jinja, measures/jinja2/measures/detail.jinja, measures/tests/test_views.py
* Users need to be able to see version history of measures
* Adds a version control tab to the measure detail page
=> TP2000-376 Add version control tab to measure detail page

pii-ner-exclude.txt, workbaskets/tests/test_views.py, workbaskets/views/ui.py
* In changing some of the urls we needed to add the workbasket pk to the url instead of the view getting it from the session and in this view that was missed
* Adds the pk to the url
* Adds a test to check it works
=> TP2000-433: Fix missing pk in review workbasket url

README.rst
Mac-specific info missing from README.
Add Mac-specific info to README.
=> Small Mac-specific addition to README.

pii-ner-exclude.txt, workbaskets/jinja2/workbaskets/violation_detail.jinja, workbaskets/jinja2/workbaskets/violations.jinja, workbaskets/tests/test_views.py, workbaskets/urls.py, workbaskets/views/ui.py
* Enable users to see more detail on a particular rule violation and remediate
* Adds a detail view for a single business rule violation in a workbasket
=> TP2000-510: Add business rule violation detail page

pii-ner-exclude.txt, workbaskets/admin.py, workbaskets/jinja2/includes/workbaskets/workbasket-list.jinja, workbaskets/templates/admin/workbaskets/change_form.html, workbaskets/tests/test_views.py
It's useful to know how many transactions are in a workbasket for business rule checking purposes - object checks are grouped by transaction.
Provide transaction count on the workbasket's admin list view and details view.
Show the transaction count on workbasket review list view, /workbaskets/list-all/
=> Tp2000-522  show transaction count

workbaskets/jinja2/workbaskets/violations.jinja
* Fixing mistake in previous PR
* Adds the correct param var name to the macro
=> TP2000-513: Fix incorrect param in url

Procfile
=> Revert "TP2000-610 add flower to tamato (pt.2)"

publishing/jinja2/includes/packaged-workbasket-queue.jinja, publishing/models.py
=> Tp2000 613  queued packaged workbaskets

README.rst
add minio setup instructions
It's useful to be able to test s3 storage locally without having to do a deployment and set up env variables in Vault etc., but this has proved difficult in the past.
Adds instructions on setting up minio to run s3 logic locally
=> add minio setup instructions

common/jinja2/common/dashboard_overview.jinja, common/urls.py, common/views.py
=> Firebreak: Add total comm codes, small fixes

common/jinja2/common/dashboard_overview.jinja, common/views.py
=> Firebreak: Add measures and comm codes active counts

common/jinja2/common/dashboard_overview.jinja, common/views.py
=> Firebreak: Add regulations and quotas, modify layout

notifications/admin.py, notifications/tasks.py, publishing/models/packaged_workbasket.py
A few small issues were found during a test session. 
This PR provides fixes for those issues.
=> Various small fixes from testing session

publishing/views.py
From the envelope queue view, the currently downloadable envelope may not be the one currently being processed if the page has not been refreshed since it was processed (e.g. by another user or from another browser tab).
Only permit downloading the envelope that is currently being processed from the envelope queue view.
=> Prevent downloading a wrong envelope from a stale view

publishing/admin.py, publishing/urls.py, publishing/views.py
incase of any investigation TAP admins should be able to download the envelope to analyse
added download link for envelopes in django admin
=> added admin download envelope view

common/jinja2/layouts/_generic.jinja
[TP000-712](https://uktrade.atlassian.net/browse/TP000-712) Impl'n Packaging Automation - Add Google Analytics tracking
to track the user journeys taken through the new automation feature
add gtag script to generic template
=> Add Google Analytics tracking

measures/conditions.py, measures/constants.py, measures/forms.py, measures/jinja2/measures/edit-multiple-start.jinja, measures/jinja2/measures/edit-wizard-step.jinja, measures/tests/test_forms.py, measures/tests/test_views.py, measures/urls.py, measures/views.py, measures/wizard.py
* Users want to be able to edit start dates as well as end dates on measures
* Adds the end date form and a new start date form to a form wizard
* Users can select which fields they wish to edit at the start of the form
=> TP2000-743 Edit multiple measures start and end dates

measures/jinja2/includes/measures/list.jinja, measures/views.py
* Fixes this error: Uncaught DOMException: Failed to execute 'querySelector' on 'Document': 'input[type=checkbox][name=543736]' is not a valid selector.
* Makes sure to pass the full field name ('selectableobject_<number>') to the JS not just the ID number
=> TP2000-769 Fix invalid selector

measures/conditions.py, measures/constants.py, measures/forms.py, measures/tests/test_views.py, measures/views.py
* Users need to be able to edit the regulation for multiple measures
* Adds an extra step to the multiple measure edits form wizard for the regulation
=> TP2000-745 Add regulations to multiple measures edit form

requirements.txt
* Exposing the version of the webserver can help attackers identify possible vulnerabilities
* See https://github.com/benoitc/gunicorn/pull/2233
=> TP2000-690 Bump gunicorn to remove version from Server HTTP header

additional_codes/filters.py, certificates/filters.py, commodities/filters.py, common/forms.py, common/tests/test_forms.py, footnotes/filters.py, geo_areas/filters.py, geo_areas/models.py, measures/filters.py, measures/querysets.py, measures/tests/test_forms.py, requirements.txt
* Upgrade Django to move to a long term support version
* Upgrades Django to 3.2.14
* Fixes stuff that broke
=> TP2000-760 Upgrade Django

common/tests/test_views.py
In the [Sessions PR](https://github.com/uktrade/tamato/pull/827) Paul made a handy suggestion to make a test more robust, and I swear I clicked commit suggestion and applied it and it just didn't? So weird, anyway here's that
=> Justice for Paul's Comment PR

additional_codes/forms.py, additional_codes/tests/test_forms.py, certificates/forms.py, certificates/tests/test_forms.py, commodities/filters.py, common/filters.py, common/jinja2/common/create_description_no_description_help.jinja, common/tests/test_validators.py, common/validators.py, geo_areas/forms.py, geo_areas/tests/test_forms.py, geo_areas/views.py, measures/filters.py, measures/forms.py, workbaskets/forms.py, workbaskets/tests/test_forms.py
In order to prevent Cross Site Scripting, we need to add validation to the fields that accept user input, so anything the users can type into. Dropdowns, prepop, and choice fields aren't affected. This is what's been applied within each subapp: 
**Filters:** 
- The search on the side bar filters have had basic validation applied. 
- The code and ID fields on the Commodities and  Measures filters have validation applied.
**Quotas and Regulations:** 
- Required no changes due to either having no fields requiring validation, or validation applied on the model. 
**Footnotes:** 
- Required no changes as description requires HTML but is autoescaped by Django. 
**Measures:** 
- Create Measures form has had validation added to the fields that accept user input such as Duties etc. 
**Geographical …
=> Add validation to Workbasket Create form

commodities/jinja2/commodities/detail.jinja, commodities/jinja2/commodities/hierarchy.jinja, commodities/tests/test_templates.py, commodities/tests/test_views.py, commodities/urls.py, commodities/views.py, common/static/common/scss/_commodities.scss, common/static/common/scss/application.scss, requirements.txt
* It's helpful for users to be able to see where the commodity code they're looking at sits in the full tree
* Uses CommodityTreeSnapshot to produce a visual display of the commodity tree for a given commodity code
=> TP2000-859 Commodity hierarchy tab

workbaskets/tests/test_views.py, workbaskets/views/ui.py
Unit tests are required for work done to implement https://uktrade.atlassian.net/browse/TP2000-870.
This PR adds unit tests to cover three important cases.
- Requires dependency updates?
=> TP2000-871 Unit tests for superuser-only rule violation override

settings/common.py
currently the back up task is not correctly routed
the task is routed properly
=> exporter task backup regex

quotas/forms.py, quotas/jinja2/includes/quotas/actions.jinja, quotas/validators.py, quotas/views.py
=> Revert "TP2000-884: Add quota edit form for validity period, category"

publishing/management/commands/publish_to_api.py, publishing/models/packaged_workbasket.py, publishing/tasks.py, publishing/tests/conftest.py, publishing/tests/test_model_crown_dependencies_envelope.py, publishing/tests/test_models.py
=> PR comments

importer/goods_report.py, importer/tests/test_views.py, workbaskets/jinja2/workbaskets/review-goods.jinja, workbaskets/views/ui.py
Tariff managers would like to see the same content in the goods review tab as they see in an Excel goods report.
Extract goods review content from GoodsReport source as performed for Excel reports and display the content on the workbasket's Goods Review tab.
=> TP2000-962 Show report in goods review tab

commodities/tests/test_views.py, commodities/urls.py, commodities/views.py
* 500 error after submitting form due to missing success url
* Adds success url to edit view
=> TP2000-945: Commodity footnote edit - fix missing success url

workbaskets/jinja2/workbaskets/summary-workbasket.jinja, workbaskets/tests/test_views.py
* This ticket makes the live status text clearer for workbasket business rule checks following Patrick's recommendations. 
* Updated the text for when a business rule check passes, fails or has not been run
* Added in a test that checks that success banner appears following a successful check or does not appear otherwise
=> TP2000 627 workbasket summary business rules text

geo_areas/tests/bdd/conftest.py
* Rerunning tests is annoying
* Ensures validity dates and transactions are explicitly set on test fixtures so that ordering will be the same every time
=> TP2000-976: Fix flaky test

quotas/forms.py, quotas/tests/test_forms.py, quotas/validators.py
=> TP2000-1124: Add validation for quota definition volume

README.rst
There's no readme documentation to detail how the application can be transitioned in and out of maintenance mode.
This PR adds a section to the readme docs on how to transition the application in and out of maintenance mode.
=> TP2000-1192 Document maintenance mode operation

measures/models/__init__.py, measures/models/bulk_processing.py, measures/models/tracked_models.py
The Measures-related `models.py` file is already relatively large. It also currently contains only `TrackedModel` related models. Adding measure bulk creation / editing models and related classes to this confuses its purpose.
This PR factors out models into two separate modules that live under a new `measures/models/` directory: one retaining the existing `TrackedModel`s-based models, and another containing the new bulk creation/editing-relate models.
=> TP2000-1222 Refactor measures based models

geo_areas/tests/test_forms.py, regulations/forms.py, regulations/tests/test_views.py
=> Revert "TP2000-1238 Fix AttributeError when editing a regulation"

.pre-commit-config.yaml, package.json
Pre-commit hook keeps failing.
Implements the changes identified by @eadpearce in this [thread](https://teams.microsoft.com/l/message/19:80f6ef27ef454a87a8c4844d3aa5b3f7@thread.tacv2/1712057060974?tenantId=8fa217ec-33aa-46fb-ad96-dfe68006bb86&groupId=7dec05eb-83aa-4ca6-8bff-bf9b86f579e7&parentMessageId=1712057060974&teamName=TAP&channelName=Dev%20and%20Data&createdTime=1712057060974)
=> TP2000-1285 Implementing fix for pre-commit hook

Procfile, docker-compose.yml, manifest.yml
- Celery will need to be tested on testing and prod prior to full deployment
- extracts Celery set up from mega branch for separate deployment to each service for testing
=> TP2000-1267 Setting up Celery

measures/forms/wizard.py, measures/tests/test_bulk_processing.py
This old bugfix got accidentally reverted when merging another PR with master https://github.com/uktrade/tamato/pull/1263
=> Fix regression

common/jinja2/layouts/detail.jinja, conftest.py, tasks/forms.py, tasks/jinja2/tasks/workflows/task_template_confirm_create.jinja, tasks/jinja2/tasks/workflows/task_template_create.jinja, tasks/jinja2/tasks/workflows/task_template_detail.jinja, tasks/jinja2/tasks/workflows/template_detail.jinja, tasks/models/workflow.py, tasks/tests/conftest.py, tasks/tests/factories.py, tasks/tests/test_views.py, tasks/tests/test_workflow_models.py, tasks/urls.py, tasks/views.py
Task template creation and detail views are needed as part of workflow template management.
This PR:
- Adds UI support for creating new task templates within existing workflow templates.
- Adds UI support for viewing task template details.
- Provides unit tests for the create and detail views for task templates.
=> TP2000-48 & TP2000-1549 Task template create and detail views

tasks/forms.py, tasks/jinja2/tasks/workflows/task_template_confirm_delete.jinja, tasks/jinja2/tasks/workflows/task_template_delete.jinja, tasks/jinja2/tasks/workflows/task_template_detail.jinja, tasks/tests/test_views.py, tasks/urls.py, tasks/views.py
A task template delete view is needed as part of workflow template management.
This PR:
Creates new views and form to support task template deletion.
Adds unit tests for view processing.
=> TP2000-1572 Delete task template views

.gitignore, Makefile, pyproject.toml, requirements.txt
The TAP service has been requested to remove Python packages - see TP2000-1605 for details, avoiding divulging unnecessary info here.
This PR:
- Removes two packages from `requirements.txt`.
- Removes a pytest flag used to invoke features from the removed packages.
- Removes other references to the packages.
- Removes a related line from `.gitignore` which might otherwise mask the presence of files that should be removed.
- Requires dependency updates? Yes
=> TP2000-1605 Remove Python packages as requested by cyber

common/jinja2/common/accessibility.jinja
* The TAP accessibility statement has been updated to reflect new changes
* Content change on the following URL: [https://www.manage-trade-tariffs.trade.gov.uk/accessibility-statement](https://www.manage-trade-tariffs.trade.gov.uk/accessibility-statement)
Optionally let reviewers know they need to run migrations or update dependencies before testing by adding the following section:
- Requires migrations? - No
- Requires dependency updates? - No
=> Tp2000 1613  update accessibility statement

tasks/tests/test_views.py, tasks/views.py
The test `tasks/tests/test_views.py::test_workflow_template_list_view` is failing - see "What", below, for failure details.
This PR:
- Adds a missing return from `TaskWorkflowTemplateListView.get_context_data()`, which caused an exception when attempting to access the view's `filter` from the view's Jinja template.
- Corrects referencing the `updated_at` and `created_at` attributes on a `TaskWorkflowTemplate` instance within the test function.
- Simplifies test function structure and vars.
=> Fix failing test

tasks/jinja2/tasks/edit.jinja, tasks/views.py
The task update view's title is missing a value.
Set the task update view's title in the view via a context dict item.
=> Fix UI bug

tasks/admin.py
This PR introduces a very simple admin view for Workflows. It displays a workflow's id, title, description, and creator template. It also allows you to search by title.. which is the workflow's associated summary task's title.
- Requires migrations? nope
- Requires dependency updates? no! 
Very cute!!
=> Add simple TaskWorkflowAdmin view

settings/common.py
* Task was not running in UAT env as it was being sent to the default 'celery' queue and we don't have a worker running this queue https://docs.celeryq.dev/en/stable/userguide/routing.html 
* Added task to the rule-check queue
=> Add missing measures check to rule-check task queue

pyproject.toml
Test coverage incorrectly includes `/tmp` directory and subdirectories that are used when creating sqlite snapshots - required to avoid writing 'extra' migration files to the source.
Omit `/tmp/' from test coverage.
=> TP2000-1693 Filter /tmp from test coverage

common/jinja2.py, common/static/common/scss/_components.scss, common/util.py, tasks/jinja2/tasks/includes/task_list.jinja, tasks/jinja2/tasks/includes/task_queue.jinja, tasks/jinja2/tasks/macros/display_assignees.jinja, tasks/jinja2/tasks/macros/display_details.jinja, tasks/jinja2/tasks/workflows/detail.jinja, tasks/tests/factories.py, tasks/tests/test_views.py, tasks/views.py
A new UI has been designed to replace the current workflow detail view.
- Implements UI changes to detail view following the new design
- Aligns ticket template detail view with the new UI changes
- Updates detail view unit tests
- Adds new CSS classes that style the summary list component as a stacked list
- Adds datetime formatting filters for use in Jinja templates
Note: Adding ticket comments, changing ticket status and viewing ticket attachments will be implemented in follow-up work.
<details><summary>Ticket detail view</summary>
<p>
</p>
</details> 
<details><summary>Ticket template detail view</summary>
<p>
</p>
</details>
=> TP2000-1725  Redesign ticket detail view

tasks/forms.py, tasks/jinja2/tasks/workflows/detail.jinja, tasks/tests/test_forms.py, tasks/tests/test_views.py, tasks/views.py
Users need to be able to add comments on tickets like they can in Jira.
This PR adds functionality to add comments to tickets. A _Comments_ form appears on the ticket detail view.
=> TP2000-1733 Add comments to tickets

common/jinja2/common/homepage.jinja, common/tests/test_views.py, common/views/pages.py, tasks/jinja2/tasks/workflows/confirm_update.jinja, tasks/jinja2/tasks/workflows/detail.jinja, tasks/jinja2/tasks/workflows/edit.jinja, tasks/tests/test_views.py
Following the introduction of ticketing into TAP, the homepage needs an update to show a users tickets.
This PR:
- adds a new _Tickets_ card to the homepage which shows a user's assigned tickets - only visible to users with the `tasks.view_taskworkflow` permission, assuming this will be granted to TMs
- updates the workbaskets cards to regular links rather than buttons
- removes the currently working on card as per[ the design](https://www.figma.com/design/9yUrEswjxKJNvslpiQMwSs/%5BTP2000-1705%5D-Making-changes-to-the-homepage-to-support-Tariff-tickets?m=dev)
- updates various view tests which were failing as a result of [TP2000-1744](https://github.com/uktrade/tamato/pull/1438)
It does not:
- add in the _Tickets in review_ card as the assignment of reviewers is not yet a feature to be …
=> TP2000-1708 Update homepage cards
