uktrade/tamato

- docs/adr/0001-record-architecture-decisions.md
Decisions affecting the technical architecture of the TAMATO project should be recorded
in the docs/adr folder in Markdown format so that the reasons for decisions and the
alternatives considered are documented and kept alongside the code, for ease of
maintenance and future development.
See:
* http://thinkrelevance.com/blog/2011/11/15/documenting-architecture-decisions
* [adr-tools](https://github.com/npryce/adr-tools)
> Start using ADRs to record architecture decisions

- .dockerignore
- Dockerfile
- README.md
- docker-compose.yml
- urls.py
The webapp now depends on NodeJS to fetch and compile GOV.UK Frontend and its dependencies.
This change introduces a multi-stage build, which first uses a NodeJS image to install GOV.UK Frontend, then passes the compiled assets to the Python image.
The container is now run with docker-compose, as it depends on a Postgres database.
> Compile SCSS and Javascript assets in Dockerfile

- .github/workflows/django.yml
- commodities/migrations/0001_initial.py
- commodities/models.py
- measures/migrations/0001_initial.py
- measures/models.py
- requirements.txt
Because we want to keep the Python codebase maintainable, we should keep to a consistent code standard. Black checks code for violations of that standard and Github will show a failed check if there are any violations.
> Check code standards with Black

- .cfignore
- .github/workflows/check-pr.yml
- .gitignore
- Makefile
- Procfile
- common/static/common/js/application.js
- common/static/common/scss/application.scss
- manifest.yml
- package.json
- requirements.txt
- settings/common.py
- setup.cfg
* Adds [`dj-database-url`](https://github.com/jacobian/dj-database-url) to get the connected database service credentials from the `DATABASE_URL` environment variable.
* Adds [`whitenoise`](http://whitenoise.evans.io/en/stable/) to serve static assets
* Adds a [`Procfile`](https://docs.cloudfoundry.org/buildpacks/prod-server.html) to run migrations and start the app on deployment
* Updates the Github Actions workflow to deploy to GOV.UK PaaS on passing tests
> Enable deployment onto GOV.UK PaaS

- common/jinja2/common/logged_out.jinja
- common/static/common/scss/_icon-action-list.scss
- common/static/common/scss/application.scss
- docker-compose.yml
- footnotes/fixtures/test-footnotes-fixtures.json
- footnotes/jinja2/footnotes/detail.jinja
- footnotes/jinja2/footnotes/list.jinja
- footnotes/static/footnotes/scss/_footnotes.scss
- footnotes/tests/bdd/features/footnotes.feature
- footnotes/tests/bdd/test_browse_footnotes.py
- footnotes/urls.py
- footnotes/views.py
- webpack.config.js
As a Tariff manager
I want to view the summary of a footnote
So that core information is visible at a glance
This change overrides the FootnoteViewSet to return a rendered Jinja template, which
uses GOV.UK Frontend Tabs and Table components to display the footnote core data.
The footnotes list is updated to make the footnote ID a link to the detail view.
This also adds a couple of test footnotes and footnote types in fixtures to be loaded
into the database with `python manage.py loaddata test-footnotes-fixtures`.
> Add footnote detail view [TP-88]

- manifest.yml
A better namespace for the dev database is needed - as well as a clean
database for the new data models.
This commit adds "dev" to the name.
> Update the database service for dev.

- common/jinja2/common/index.jinja
- common/tests/factories.py
- footnotes/models.py
- geo_areas/filters.py
- geo_areas/jinja2/geo_areas/list.jinja
- geo_areas/jinja2/includes/geo_areas_list.jinja
- geo_areas/models.py
- geo_areas/serializers.py
- geo_areas/tests/bdd/features/geo_areas.feature
- geo_areas/tests/bdd/test_browse_geo_areas.py
- geo_areas/urls.py
- geo_areas/views.py
- urls.py
It is required for tariff managers to be able to view, browse and search
for geographical areas in order to edit and update them.
This commit introduces a frontend page for viewing and searching lists
of geographical areas. The search input utilises postgreSQLs full-text
search features and so can run a search over both the geographical areas
ID and its description set.
> TP-148: Add frontend view to browse geographical areas.

- common/static/common/scss/application.scss
- common/tests/factories.py
- conftest.py
- geo_areas/jinja2/geo_areas/detail.jinja
- geo_areas/models.py
- geo_areas/static/geo_areas/scss/_geo_areas.scss
- geo_areas/tests/bdd/conftest.py
- geo_areas/tests/bdd/features/browse_geo_areas.feature
- geo_areas/tests/bdd/features/detail_geo_areas.feature
- geo_areas/tests/bdd/test_browse_geo_areas.py
- geo_areas/tests/bdd/test_detail_geo_areas.py
- geo_areas/views.py
- webpack.config.js
It is required for tariff managers to be able to view, individual
geographical areas in order to edit ad update them.
This commit introduces a frontend page for viewing individual
geographical areas. This includes a tabbed view for core data,
descriptions, as well as a members/memberships tab.
The members/memberships tab changes based on the area_code. i.e.
if a geographical area is a group then it has members and so
displays the members tab. If a geographical area is not a group then it
does not have members but may have memberships - in which case these
are displayed in a memberships tab.
> TP-166: Add frontend view to details of geographical areas.

- geo_areas/jinja2/geo_areas/detail.jinja
Currently when appending to a list within a Jinja2 `set` tag "None"
is always returned and rendered on the page. By adding an `or ""` after
the append python will automatically inject the blank string into the
page instead - which is the equivalent to adding nothing to the page.
> Stop "None" from showing in the geo area description tab.

- commodities/serializers.py
- common/serializers.py
- measures/serializers.py
- setup.py
The TAMATO TARIC importer script has a dependency on TAMATO's serializers and models to
validate and modify the TAMATO DB.
This change adds a `setup.py` to allow TAMATO to be added as a pip dependency
It also adds preliminary serializers for Commodity and Measure models, to allow the
importer to deserialize these models.
Finally, the ValiditySerializerMixin is modified to handle TARIC date format strings
(YYYY-MM-DD) as well as ISO 8601 format (the default), for convenience.
> Make compatible with tamato-taric-import

- additional_codes/models.py
- additional_codes/tests/test_business_rules.py
- additional_codes/validators.py
- certificates/models.py
- certificates/tests/test_business_rules.py
- certificates/validators.py
- common/models.py
- common/tests/factories.py
- footnotes/models.py
- geo_areas/tests/test_business_rules.py
- workbaskets/models.py
Some business rules require validating across models in a workbasket, for example,
Certificates must have at least one associated CertificateDescription. This cannot be
achieved with standard model validation.
This change adds a method to all TrackedModel objects, `validate_workbasket`, which may
be overridden to perform validation across all models in the same workbasket. When the
WorkBasket is validated, it calls this method on all its TrackedModels. Any
ValidationErrors raised are stored in the WorkBasket instance to enable error messaging
in the UI.
> Add a hook for validating models in a workbasket

- additional_codes/filters.py
- additional_codes/views.py
- common/filters.py
All additional codes were returned regardless of search terms.
This change adds a custom DRF filter backend, which searches for exact Additional Code
Type SID + Additional Code matches (eg: X001), and falls back to full-text search on
sid, code, type, description and type description.
> Fix additional code search

- .github/workflows/check-pr.yml
- .github/workflows/django.yml
- README.md
- package.json
PaaS no longer supports 12.16, which causes deployment to fail
> Bump nodejs version 12.18.2

- commodities/import_handlers.py
- commodities/serializers.py
- commodities/tests/assets/footnote_association_goods_nomenclature.xml
- commodities/tests/assets/goods_nomenclature.xml
- commodities/tests/assets/goods_nomenclature_description.xml
- commodities/tests/assets/goods_nomenclature_indent.xml
- commodities/tests/test_importer.py
- common/app_config.py
- common/tests/factories.py
- common/tests/util.py
- footnotes/models.py
- geo_areas/models.py
- importer/handlers.py
- importer/management/commands/import_taric.py
- importer/taric.py
- measures/import_handlers.py
- package-lock.json
- regulations/import_handlers.py
- requirements.txt
It is imperative that legacy data from the TARIC can be imported at will into the
TaMaTo database. Given the Goods Nomenclature models are now ready it is necessary
that the importer is setup for these models.
As this is the first set of models using the integrated importer there are a number
of changes made to the importing system to remove a few bugs and make it easier to
use the system for more models in the future.
A few discoveries of varying complexity have also been found. Firstly merged
models do not fit well with the current importer architecture. These instances have
been passed over to be done later as a way of adapting the importer to all models
affected by this (the majority of models in the system). The second is that, as
the hierarchical tree is largely unrepresented by the …
> TP-206: Add importer for Goods Nomenclature and related models.

- Makefile
- common/jinja2.py
- common/models.py
- footnotes/jinja2/footnotes/edit.jinja
- footnotes/tests/bdd/test_detail_footnotes.py
- footnotes/views.py
- requirements.txt
- workbaskets/jinja2/workbaskets/choose-or-create.jinja
- workbaskets/models.py
- workbaskets/views.py
- workbaskets/views/__init__.py
- workbaskets/views/decorators.py
- workbaskets/views/generic.py
- workbaskets/views/mixins.py
This change refactors the `CurrentWorkBasketMixin`, moving the queryset filtering code to
a new method `with_workbasket()` on the `TrackedModelQuerySet` class, and ensuring that only the latest version of models in
the workbasket are added to the queryset.
Additionally, if there is already a draft of an object in the current workbasket, this is now reused, rather
than creating a new draft.
This fixes the bug seen when editing the same footnote more than once. Multiple drafts
in the workbasket were added to the queryset, which caused an exception in the
`DetailView` which expects a single object.
> Fix querysets with multiple versions of models

- footnotes/jinja2/footnotes/detail.jinja
Was showing workbasket creation date, rather than the footnote draft
update timestamp.
> Show correct activity date on footnote versions list

- .pre-commit-config.yaml
We use the pre-commit (https://pre-commit.com/) tool to automatically run the Black
Python linter on our code before commits. This change adds the
`reorder-python-imports` formatter and shares the config, so that all
developers on the project can use it.
> Add config file for pre-commit

- additional_codes/import_parsers.py
- additional_codes/tests/test_importer.py
- certificates/import_handlers.py
- certificates/import_parsers.py
- certificates/models.py
- certificates/serializers.py
- certificates/tests/test_importer.py
- commodities/models.py
- commodities/tests/test_importer.py
- common/assets/taric3.xsd
- common/tests/factories.py
- common/tests/util.py
- footnotes/tests/test_importer.py
- importer/handlers.py
- importer/parsers.py
All certificates models now work with the importer.
Tests have been simplified as the majority of importer tests would include
significant amounts of boilerplate. To handle this a new test utility has
been added and applied to older importer tests.
Also replaced tabs in the taric3.xsd with spaces. Because copying the XML
definitions for the parser docstrings was upsetting the PyCharm linter.
> TP-300: Apply importer to certificates models.py

- common/jinja2.py
The v0.5.5-alpha release of govuk-frontend-jinja fixes a bug which we had patched locally.
When Nunjucks iterates over an object, it does `for key, value in object`. This is fails in Jinja, and govuk-frontend-jinja now corrects this to `for key, value in object.items()`. However, we were already applying this patch, in addition to inserting a guard for iterating an undefined attribute (eg: `for key, value in (object.attribute|default({})).items()`) which results in `.items().items()` in the processed template, causing an error.
> Fix double `.items()`

- additional_codes/tests/test_business_rules.py
- certificates/tests/test_business_rules.py
- common/tests/factories.py
- common/tests/test_models.py
- common/tests/util.py
- common/util.py
- footnotes/tests/bdd/test_detail_footnotes.py
- footnotes/tests/test_business_rules.py
- footnotes/views.py
- requirements.txt
We are currently using a set of fixed dates for testing purposes.  Eventually the
current date will no longer fall within those date ranges.  This commit replaces the
fixed dates with relative dates, based on the current date at runtime.  This also
removes our dependency on freezegun for the few tests that needed it.
This change has been separated out from TP-240 (measures data model), because I need it for another PR.
> Remove dependency on freezegun

- .github/workflows/django.yml
Publishing to Github pages fails because the path to the Sphinx build is wrong
> Correct build path for Sphinx docs

- .github/workflows/check-pr.yml
- commodities/import_handlers.py
- commodities/import_parsers.py
- commodities/serializers.py
- commodities/tests/test_business_rules.py
- commodities/tests/test_importer.py
- commodities/validators.py
- common/tests/factories.py
- common/tests/util.py
It is a requirement for the project to be able to import Goods Nomenclature,
Goods Nomenclature descriptions and Indents from legacy TARIC3 XML data.
This commit introduces the import parsers and handlers for these models.
Most of the models are straightforward and follow the predefined patterns
set out in other importers. However indents, being a materialized path in the
new data models but only a pseudo materialized path in the old data models,
has some divergence.
It has been necessary to find the appropriate parent of any new indents
coming in using only the limited dataset given. To this end the following
algorithm has been used:
- If top level indent, assign indent as root with no parents.
- If 1 < indent < 6, the parent item ID can be ascertained from the given
data, use this to …
> TP-272: Implement importer for Goods Nomenclature and Indents.

- common/tests/test_util.py
- common/util.py
- footnotes/tests/bdd/test_edit_footnote.py
- measures/tests/test_business_rules.py
The `validity_range_contains_range` function incorrectly returned `False` when a contained
range had the same end date as the containing range.
This commit fixes that by checking that the contained range bounds are within or equal
to the containing range bounds.
Also, a few fixes to tests that failed after this change
- the tests for this function, natch
- the footnotes editing test was submitting an empty start date when editing the end date
- the measures tests were missing the measure_type_series validity period (probably only passed before because of the bug this commit fixes)
> Refactor range contains check function

- importer/parsers.py
- importer/tests/test_parsers.py
The `etree` streaming API will sometimes emit start
events for elements without their children if
passed a IO object or the Pull mecahnism is used.
This is because the API will consume input in
blocks and return as many events as it can, rather
than waiting for elements to be complete.
So we are not able to check what elements an
element has when handling a start event. To get
around this, this commit removes the need for
looking at if an element is a leaf node and
instead introduces extra state fields to keep
track of if the parser is currently parsing an
element or not, which is sufficient for selecting
the right parser. (This should also remove the
limitation on only having a single level of
nesting.)
> Handle partially-loaded elements in XML parsing

- common/models.py
- common/tests/factories.py
- common/tests/util.py
- measures/import_handlers.py
- measures/import_parsers.py
- measures/jinja2/taric/measure_condition_component.xml
- measures/models.py
- measures/serializers.py
- measures/tests/conftest.py
- measures/tests/test_importer.py
- measures/validators.py
It is a requirement for the project to be able to import Measures,
Measure Types, Components, Conditions, Duty Expressions, Measurements, Monetary Units,
etc from legacy TARIC3 XML data.
This commit introduces the import parsers and handlers for these models.
> TP-242: Importer for measures

- Makefile
- common/assets/envelope.xsd
- common/tests/factories.py
- measures/import_handlers.py
- measures/jinja2/taric/measure.xml
- measures/serializers.py
- measures/tests/test_importer.py
- measures/tests/test_xml.py
- measures/unit_serializers.py
- quotas/jinja2/taric/quota_definition.xml
- quotas/models.py
- quotas/serializers.py
- quotas/tests/test_xml.py
- workbaskets/serializers.py
Another mixed bag of fixes for core:
- XSD change to ensure envelopes are produced according to our ID standard.
- Fix quota definition XML to include units.
- Don't use the quota description as a string representation as it may be `None`.
- Allow Python from a envrionment variable in the Makefile.
> Fixes from the field

- Makefile
- README.md
- manage.py
Change `manage.py` so that DJANGO_SETTINGS_MODULE defaults to `settings.test` if `test` or `pytest` is in the commandline.
Update README, and remove don't explicitly set this in `Makefile`.
> Default settings module to settings.test if running tests..

- taric/tests/test_models.py
Reset the factory sequence so test can't fail if it's not the first test to run using EnvelopeFactory.
> Fix taric test pollution test fail

- geo_areas/models.py
- geo_areas/tests/test_business_rules.py
- geo_areas/validators.py
There are a number of ways to break GA3 that we
haven't accounted for in our current business
rules (although it seems our downstream systems
are only able to catch some of these).
Most of this code is lifted directly from the
additional codes application... which makes me
wonder if it would be worth abstracting out a
common pattern here for description-period-based
business rules.
> Add missing validations for geographical areas

- importer/namespaces.py
The seed file uses a slightly different namespacing from the EU taric files. This commit updates the namespaces to reflect this.
> TP-398: Fix namespaces

- hmrc_sdes/models.py
The Upload model generates a JSON payload ready to be sent to the HMRC
SDES API, but had an error where it passed a UUID object instead of a
string.
This commit fixes that error and also sets a default value for the `now`
argument to `Upload.notify_hmrc()` for convenience.
> Fix HMRC SDES notification payload JSON

- common/tests/factories.py
- regulations/import_handlers.py
- regulations/jinja2/taric/regulation.xml
- regulations/serializers.py
- regulations/tests/test_importer.py
- regulations/tests/test_xml.py
This is the format tentatively agreed with the Trade Tariff Service for adding extra information about UK legislation. We now output the pipe format in the order:
information_text "|" public_identifier "|" url
And we also detect this in XML so that we can load any TAP-produced regulations in this format.
CC @matthewford – does this still match the format expected by the Trade Tariff Service?
> Regulation information text should contain URL and public ID

- conftest.py
- hmrc_sdes/api_client.py
- hmrc_sdes/tests/test_client.py
- settings/common.py
- settings/test.py
Questionable things ahead:
* This commit adds a test which is skipped by default.
* This test makes real HTTP requests to https://test-api.service.hmrc.gov.uk
* This test relies on a `.env` file in the project root directory
Run the test with `pytest hmrc_sdes --hmrc-live-api`.
The test will be skipped if the command line argument is omitted.
> Add a test hitting the HMRC sandbox API

- common/jinja2/common/index.jinja
- common/jinja2/layouts/layout.jinja
- common/static/common/scss/_layout.scss
Jira Ticket: [TP-529](https://uktrade.atlassian.net/browse/TP-529)
Changing the layout of the homepage to suit the designs.
- Added the Alpha Banner, link to a feedback page has been removed because we do not have a way of receiving feedback yet.
- Altered content to fit with the new designs, including increasing the max-width of the container to 1100px.
- Reshuffled the order of the manage sections to fit the order in the designs.
> TP-529 Rework Homepage

- measures/migrations/0001_initial.py
Commodities migration 0001 already depends on Common migration 0001, so no need to list both in the Measure migration 0001
> Remove unnecessary migration dependency

- additional_codes/models.py
- additional_codes/views.py
- footnotes/models.py
- footnotes/views.py
- geo_areas/models.py
- geo_areas/views.py
- regulations/views.py
Historically descriptions didn't have a named `related_name`. This has
changed recently and so the frontend queries were prefetching the
wrong related name and erroring as a result.
This commit updates the queries to use the correct related_name for
descriptions - it also improves the caching setup for fetching the
latest descriptions. This may need to be made more generic and more
flexible in the near future.
> TP-542: Update frontend views to be inline with current relations.

- README.md
- common/jinja2/layouts/layout.jinja
- common/tests/util.py
- quotas/tests/test_xml.py
- requirements.txt
- settings/common.py
- urls.py
It is a requirement that changes to the tariff can be attributed to the user who made
them, for auditing purposes. It may also be required later that different groups of
users have different permissions, for example only some users may be permitted to
approve workbaskets.
This commit integrates the tariff editor with the DIT single sign-on authentication
broker service (https://sso.trade.gov.uk). All pages in the tariff editor require an
authenticated user, so if not currently authenticated, the user is redirected on any
page request to the DIT SSO login screen. After successfully logging in, they are
redirected back to the tariff editor.
Credentials for the DIT SSO broker service are secret, so not included in this commit.
The credentials are passed into the tariff editor via environment …
> TP-534: Integrate DIT staff SSO

- additional_codes/jinja2/additional_codes/list.jinja
- additional_codes/views.py
- common/pagination.py
- common/static/common/scss/_pagination.scss
- common/static/common/scss/application.scss
- common/tests/test_pagination.py
- exporter/tests/test_exporter_commands.py
- exporter/tests/test_exporter_tasks.py
- settings/common.py
JIRA Ticket: [TP-540](https://uktrade.atlassian.net/browse/TP-540)
Adding the pagination component and then using it for the additional codes list page.
- Created pagination component
- Added pagination component to the additional codes list page 
- Paginated additional codes for API  and UI view
- Removed Auth for ease of use until SSO becomes a thing
> TP-540 Create pagination component

- .github/workflows/check-pr.yml
- .github/workflows/django.yml
- additional_codes/filters.py
- additional_codes/tests/bdd/test_browse_additional_codes.py
- additional_codes/views.py
- common/filters.py
- conftest.py
- footnotes/filters.py
- footnotes/tests/bdd/features/edit-footnote.feature
- footnotes/tests/bdd/test_browse_footnotes.py
- footnotes/views.py
- geo_areas/filters.py
- geo_areas/tests/bdd/test_browse_geo_areas.py
- regulations/filters.py
- regulations/tests/bdd/test_regulations.py
- regulations/views.py
The old views have used a mix of Rest Framework UI views and
standard Django Generic views. As a result the filtering setups
have become a bit confusing - they also simply don't work as
descriptions have been updated.
This commit fixes the reverse relations to descriptions and creates
a more generic filtering setup which serves both standard Django views
and Rest Framework UI views.
> TP-567: Fix search on current frontend views.

- README.md
- common/jinja2.py
- common/jinja2/layouts/layout.jinja
- sample.env
- settings/common.py
- urls.py
When running locally, during development, it may be useful to disable
SSO and avoid requiring an internet connection.
This change adds an environment variable `SSO_ENABLED` which switches
on the SSO authentication flow if truthy (eg "on", or "true"), and
disables it if falsy - falling back to Django's auth ModelBackend, which
authenticates users in the database.
> Allow disabling SSO

- exporter/management/commands/dump_transactions.py
- exporter/management/commands/util.py
Looks like this got broken at some point in the past. This now successfully outputs any workbasket currently in ready to export status, and accepts an envelope ID.
We'll be using this command for as long as we have a manual interface with HMRC.
> Fix `dump_transactions` and accept an envelope ID.

- common/views.py
Although updates are actually creating new versions of a record, the view class
must still be a subclass of generic.UpdateView so that the current object is
retrieved using the identifiers in the request and is added to the template
context.
This fixes a 500 error on attempting to edit a footnote.
> Update views must inherit from generic.UpdateView

- regulations/tests/test_validators.py
- regulations/validators.py
We have previously extended the system to include
the public ID and URL in the `information_text`
field for the Trade Tariff Serivce in 97ea76a6.
It turns out that the HMRC system filters this out
and replaces it with some whitespace character:
`0xA0` in UTF-8.
We should continue to output pipes and add a
validation that this character isn't present
anywhere else in the final text string, so that
the Trade Tariff Service can split on that
character instead.
> TP-526 Add validation for non-printable whitespace character in legislation text

- additional_codes/filters.py
- common/filters.py
Currently if an regexable piece of data exists within a search
query the rest of the search query will be removed in favour of it
which is not desired behaviour. It also expected anything regexable
to be at the front of the query.
This commit fixes this behaviour to prepend the query with the regexed
data and provide the rest of the search query as well. re.search has also
replaced re.match which enables the term to be found anywhere in the query.
In addition to this the Additional Codes regex expected the search term
to _only_ be the ID, which is wrong. This has been updated.
> TP-568: Small patch to fix search functionality.

- additional_codes/jinja2/includes/additional_codes_list.jinja
- common/jinja2/layouts/list.jinja
- common/static/common/scss/_layout.scss
Bring down the width of the type column in additional codes lists, so description gets more space
The type data is a great deal longer than it will be in Prod, so it may look strange in dev screenshots
> TP-532 Refactor addition code list

- measures/import_parsers.py
- measures/jinja2/taric/measure.xml
- regulations/serializers.py
- Wrong xml tag used for additional code in measure xml. Unfortunately it seems the TARIC import didn't import any additional codes on measures due to this bug.
- Fix some attributes in the regulation serialiser
> Fix regulation attributes and measure tag

- common/jinja2/layouts/detail.jinja
- footnotes/jinja2/footnotes/detail.jinja
- footnotes/jinja2/includes/footnotes/tabs/core_data.jinja
- footnotes/jinja2/includes/footnotes/tabs/descriptions.jinja
- footnotes/jinja2/includes/footnotes/tabs/version_control.jinja
Refactoring the details page of footnotes.
- Created a generic detail layout, which only the footnote currently uses (others will be moved over in a different PR) 
- General styling changes based on designs
- Moved each footnote into their own name spaced file
> TP-577 Refactor footnote details tab

- measures/business_rules.py
- measures/models.py
- measures/tests/test_business_rules.py
- Remove some business rule application mistakes
- Don't need to check ME62 twice
- ME108 is for condition components, not ordinary
components
- Implement ME25
- ME25 had no implementation which caused violations
when cleaning a transaction. This commit adds an
implemetation of ME25 and tests.
- Fix ME32 false positive on non-overlapping measures
- The current implementation of ME32 accidentally
fires even when measures do not overlap in time.
This commit adds the time constraint and a test to
check that ME32 passess successfully when the
measures are not overlapping in time.
> Fixes to some business rules

- docs/adr/0010-convert-the-importer-to-a-pipeline.rst
- docs/adr/index.rst
- docs/business_rules/additional_codes.rst
- docs/business_rules/certificates.rst
- docs/business_rules/commodities.rst
- docs/business_rules/common.rst
- docs/business_rules/footnotes.rst
- docs/business_rules/geo_areas.rst
- docs/business_rules/index.rst
- docs/business_rules/measures.rst
- docs/business_rules/quotas.rst
- docs/business_rules/regulations.rst
- docs/conf.py
- docs/importer/index.rst
- docs/project.rst
- importer/handlers.py
- importer/taric.py
- measures/business_rules.py
- Add business rules to the documentation.
- Fix up documentation to not emit so many warnings
- Updates to Pygments that are [about to land](https://github.com/pygments/pygments/pull/1657) will
take care of the remaining issue with `dot`.
> Documentation upgrades

- measures/business_rules.py
- measures/tests/test_business_rules.py
Current implementation barfs when there are no end dates defined for anything.
> ME25: handle measure and regulation with no end date.

- common/renderers.py
- importer/management/commands/utils.py
- workbaskets/jinja2/workbaskets/taric/workbasket_list.xml
This is a small PR to make /api/workbaskets.xml output data again.
It changes the key for the list of results to be `results` - which is where Pagination outputs them.
This changes EnvelopeSerializer to use `TrackedModelSerializer(models, many=True, read_only=True).data` instead of it's custom map iterator.
`envelope_id` is wrong here, and there aren't any tests - but how this work will probably need changing in TP-396.
This is more to return some kind of base, so that when the new envelope serialization is added it's easy to see that it doesn't break anything.
> Make workbaskets.xml great again.

- additional_codes/filters.py
- common/filters.py
- common/static/common/js/application.js
- common/static/common/js/showHideCheckboxes.js
- common/static/common/scss/_layout.scss
- footnotes/filters.py
- footnotes/jinja2/footnotes/list.jinja
- footnotes/jinja2/includes/footnotes/tabs/descriptions.jinja
- footnotes/jinja2/includes/footnotes/tabs/version_control.jinja
- footnotes/jinja2/includes/footnotes_list.jinja
- footnotes/validators.py
Refactored the list page to look more like the designs, also moved a few common search fields into common, rather than have repetitive code. 
- General styling tweaks
- Moved start year and active year into the common filters
- Added JS button for showing more than 10 checkboxes, similar to the implementation at https://data.trade.gov.uk/
**_(The grey bit of box at the bottom left is the screen capture extension not working properly, not an actual bug)_**
> TP-580 Refactor footnote list page

- common/serializers.py
- exporter/tests/test_views.py
- exporter/urls.py
- exporter/views.py
- footnotes/tests/bdd/test_edit_footnote.py
- requirements.txt
- urls.py
It is a requirement that the tariff data be open and as accessible as possible.
Part of this is to make the data available on Data Workspace, and the advised
route to do so is to expose an endpoint that provides all the current tariff
data in an ActivityStream format.
This commit adds an endpoint in the exporter package which formats all the
latest TrackedModels (paginated by 20) in the ActivityStream format ready
for consumption by DataWorkspace.
> TP-575: Add an Activity Stream endpoint for Data Workspace.

- conftest.py
- importer/cache/base.py
- importer/cache/cache.py
- importer/cache/memory.py
- importer/cache/pickle.py
- importer/cache/redis.py
In some cases bits of data get stuck in the test cache when
running, this causes a cascade of all following importer tests
to fail as they try to resolve the cache.
This commit adds a clearing action to the cache and utilises it
within the tests to ensure this issue does not arise.
> Fix cache issues in importer tests.

- exporter/views.py
Activity Stream was trying to access attributes on non-existent
relations, causing a 500 error. This commit checks the relation
exists, stopping the error.
> TP-575: Fix bug for null relations

- measures/business_rules.py
- measures/tests/test_business_rules.py
Previously ME32 only considered the explicit validity period of any matching measures. 
It now also considers the implicit validity period through the user of `effective_valid_between`.
Tests have also been refactored to make it easier to check all the permutations of dates and comm codes, all in their own transaction (otherwise the transactions have to be controlled manually).
> Prevent ME32 on measures with implicit end dates

- .pre-commit-config.yaml
Adds the following pre-commit plugins:
- add-trailing-comma
- autoflake (removes unused imports and variables)
- isort (fix configuration)
- docformatter (standardise doc-comment format)
> Add some checks to pre-commit hooks

- certificates/jinja2/certificates/detail.jinja
- certificates/jinja2/includes/certificates/list.jinja
- certificates/jinja2/includes/certificates/tabs/core_data.jinja
- certificates/models.py
- certificates/urls.py
A certificate sid alone is not unique, it's the combination of the type id and the sid that is. Changed so that we now use both.
> TP-172 Fix non-unique certificate SID scenario

- common/tests/factories.py
- measures/business_rules.py
- measures/tests/test_business_rules.py
- ME32: Cut down on the number of test cases
- ME32: Handle dead fields as well as null cases.
- ME32: Prevent trigger on measure deletion.
- Measure business rules formatting.
- ME32: Use current indents to ignore past history of codes
> More ME32 fixes

- geo_areas/jinja2/includes/geo_areas/tabs/memberships.jinja
The membership area_id selector was breaking on geographical areas within the membership tabs. Fixed this and also added a clause for if there are no memberships (There is a question around whether we may not want to show empty tabs also)
> TP-618 Fix geographical area membership tab

- geo_areas/jinja2/includes/geo_areas/tabs/memberships.jinja
Currently Geo Areas shows all members with all their versions in one. It should instead
only show the most current versions of each member.
This commit changes the query to only get current members.
> Only show current members for Geo Areas

- geo_areas/jinja2/includes/geo_areas/tabs/memberships.jinja
- geo_areas/models.py
The previous patch would find only the current members (via the
geographical area table), however as the query was proxied through
memberships (a separate table) it still resulted in duplicate
members being shown.
This commit introduces a new method which builds a list of members
based on the memberships being current - removing duplicates.
> Patch 2 for showing only current members in geo members tab

- geo_areas/jinja2/includes/geo_areas/tabs/memberships.jinja
- geo_areas/models.py
Currently the memberships tab uses the dates of the country's
existence, not of the membership's existence.
This commit updates the template to use the correct date range.
It also optimises the query a bit (by creating more queries,
but faster executing ones).
> Update Geo Memberships to use the membership validity dates

- geo_areas/views.py
Prefetching helps save queries, however in some cases
it provides an incorrect description for Geographical
Areas. To remedy this prefetching has been removed from
Geographical Area views.
> Remove description prefetch for Geo Areas

- quotas/business_rules.py
- quotas/models.py
- quotas/tests/test_business_rules.py
QAM doesn't like processing Quota Definition deletions
once the start date for said Quota Definition is in the past.
This commit introduces a business rule to prevent Quota
Definition deletion once the start date has been reached.
> TP-539: Prevent active Quota Definition deletions

- quotas/business_rules.py
- quotas/models.py
- quotas/tests/test_business_rules.py
Quota Associations, Quota Suspensions and Quota Blocking
Periods all demand that their linked quotas be live. I.e.
the linked Quota Definitions can not be deleted until the
relevant associations, suspensions and blocking periods
either refer to a different quota or are deleted themselves.
This commit introduces a business rule to check that any
quota being deleted cannot be referred to by an association,
suspension or blocking period.
> TP-541: Prevent deletion of linked quotas.

- common/business_rules.py
- common/tests/test_business_rules.py
The `NoOverlapping` rule correctly removes the model being checked from the query but the `UniqueIdentifyingFields` rule does not. This is a fix for that and tests for both rules.
> Ignore same model version in uniqueness check

- commodities/import_handlers.py
- commodities/models.py
- commodities/tests/test_importer.py
- common/tests/factories.py
- common/tests/util.py
- common/util.py
In some cases new Goods Nomenclature Indents are inserted in between
old indents and their children. When this happens it is important to
update the tree by migrating these children under the new indent.
This commit introduces an addition to the GoodsNomenclatureIndentHandler
post_save method, finding inappropriate parents of possible child nodes
and replacing them with the new indent.
> TP-640: Replace inappropriate parent nodes.

- additional_codes/models.py
- additional_codes/tests/test_business_rules.py
- certificates/models.py
- certificates/tests/test_business_rules.py
- certificates/views.py
- commodities/business_rules.py
- commodities/models.py
- commodities/tests/test_business_rules.py
- common/business_rules.py
- common/exceptions.py
- common/models/records.py
- common/models/transactions.py
- common/tests/factories.py
- common/tests/migrations/0001_initial.py
- common/tests/models.py
- common/tests/test_business_rules.py
- common/tests/test_models.py
- footnotes/models.py
- footnotes/tests/test_business_rules.py
- geo_areas/business_rules.py
- geo_areas/models.py
- geo_areas/tests/test_business_rules.py
- measures/tests/test_business_rules.py
- quotas/tests/test_business_rules.py
- regulations/models.py
- regulations/tests/test_business_rules.py
Currently described models don't have an obvious single mechanism for
fetching related descriptions. `.descriptions` would be the logical
method, however this only provides descriptions directly attached to
the given version, which is innacurate.
This commit introduces a generic `.get_descriptions` method on the
`TrackedModel` class so all described `TrackedModels` can automatically
fetch all related descriptions. This method optionally takes a
`Transaction` which triggers the query to use `approved_up_to_transaction`
by default it will use `latest_approved`.
In this process it was discovered that business rules currently don't pay
attention to the current transaction - only the given models transaction.
As business rules now often cross multiple transactions, including
transactions which …
> TP-543: Update descriptions queries and fix business rules context.

- settings/common.py
VCAP provides a rediss endpoint, requiring SSL for the
cache and celery broker connections.
This commit updates the URL to add `?ssl_cert_reqs=CERT_REQUIRED`.
In turn this tells the redis client how to properly connect to the
redis instance.
> Fix redis url.

- regulations/jinja2/includes/regulations/list.jinja
- regulations/jinja2/includes/regulations/tabs/core_data.jinja
- regulations/jinja2/includes/regulations/tabs/version_control.jinja
Fixes after feedback from UAT:
List (TP-614)
Details: (TP-613)
Regulation ID -> ID (We already say "Regulation" in very large text above it and this is consistent with other screens)
Version control(TP-135)
> Wrapup fixes for TP-59

- measures/filters.py
- measures/jinja2/includes/measures/list.jinja
- measures/jinja2/includes/measures/tabs/core_data.jinja
- measures/views.py
- Change additional code filter to work on the type / code setup we currently display, also changed the list view to show that. 
- Changed the end date on the measure detail page to be the effective end date  
- Changed the quota filter to work on the order number, and the list view also to show it (also links off to the quota detail page now)
- Made list view only search for latest approved measures
> TP-610 Fix measures filter issues

- additional_codes/business_rules.py
- certificates/business_rules.py
- commodities/import_handlers.py
- common/business_rules.py
- common/models/mixins.py
- common/models/records.py
- common/serializers.py
- common/tests/test_serializers.py
- exporter/serializers.py
- geo_areas/business_rules.py
- geo_areas/models.py
- importer/management/commands/import_taric.py
- importer/taric.py
- measures/business_rules.py
- measures/models.py
- measures/tests/test_business_rules.py
- quotas/business_rules.py
- quotas/tests/test_business_rules.py
- settings/common.py
- workbaskets/models.py
Previously the clean method on workbaskets was not implemented, so there was no validation performed on import.
But also, running against the entire workbasket is not what we want – as per ADR 12, validations need to be performed after every transaction.
This commit changes our import validation to run business rules after every transaction, but also implements a clean method for a workbasket as well (it will be useful later).
Notably we also no longer halt an import run when an error is found and instead just print an error. The reason for this is that when importing we are normally importing well-formed XML and business rule violations are (at the moment) normally an indication that our implementations are wrong. Plus, it's much easier to debug data when it is in the database rather …
> Check validation rules on import and log them as errors.

- measures/models.py
- quotas/models.py
- regulations/models.py
These implementations broke when called in the measures, quotas and regulations detail templates.
A working and generic implementation is provided in TrackedModel, so these methods are
no longer needed.
> Remove deprecated get_url methods

- certificates/views.py
If there is no current workbasket set, then certificate UI views will error.
> Fix certificate views when no current workbasket

- common/jinja2/common/confirm_update.jinja
- footnotes/jinja2/footnotes/confirm_update.jinja
- footnotes/jinja2/footnotes/confirm_update_description.jinja
Currently when succesfully changing a model the workbasket is referenced.
This is unnecessary. Therefore this commit removes the reference to the
workbasket.
> TP-669: Remove references to the workbasket on a change.

- common/tests/factories.py
- importer/tasks.py
- importer/tests/conftest.py
- importer/tests/test_nursery.py
- importer/tests/test_tasks.py
Added tests for the nursery caching interface as well as the tasks.
There's still elements of the importer untested, and lots of edge cases which could have done with testing. But no time to do it in!
I'll document some of the key bits that are missing on the ticket.
> TP-655: Added more tests for the importer system.

- geo_areas/business_rules.py
- geo_areas/tests/test_business_rules.py
The rule as written specifies that the group must
span the *membership* period of all of its members,
but our code checked that the group spanned the
*validity* period of its members.
This commit fixes that and introduces more tests.
> TAMATO-19: Fix validity check for geo memberships

- .github/workflows/check-pr.yml
- .github/workflows/django.yml
- .gitignore
- Makefile
- requirements.txt
At the moment our code coverage is not reported correctly. For some reason `pytest-cov` seems to initialise after Django has already loaded all of the code, meaning that our imports and definitions are reported as not hit. This is unhelpful because it clouds the real areas in the code that do not have adequate coverage.
This commit changes to calling `coverage` directly which correctly captures all of the statements.
> Calculate code coverage correctly

- additional_codes/filters.py
- additional_codes/tests/test_business_rules.py
- additional_codes/validators.py
- certificates/filters.py
- certificates/validators.py
- commodities/tests/test_business_rules.py
- commodities/validators.py
- common/filters.py
- common/models/records.py
- common/serializers.py
- common/tests/test_filters.py
- common/tests/util.py
- common/util.py
- exporter/tests/test_exporter_commands.py
- exporter/tests/test_exporter_tasks.py
- footnotes/filters.py
- hmrc_sdes/models.py
- hmrc_sdes/validators.py
Fixing up the coverage has revealed a few areas where we have unused or untested code. This commit addresses the lowest of the low-hanging fruit from these.
- Clean-up of dead or duplicated code ed6d329
* Remove dead or unused code
* Remove instances of raises_if duplication
* Improve type hints in some places
- Remove use of hard-coded additional code type list 90926fb
* Also add a generic helper for generating a list of type choices.
> Spring clean

- additional_codes/tests/bdd/features/browse-additional-codes.feature
- additional_codes/tests/bdd/features/detail_additional_codes.feature
- additional_codes/tests/bdd/features/edit_additional_codes.feature
- additional_codes/tests/bdd/test_edit_additional_codes.py
- additional_codes/views.py
- certificates/tests/bdd/conftest.py
- certificates/tests/bdd/features/edit.feature
- certificates/tests/bdd/test_edit_certificates.py
- certificates/views.py
- common/tests/bdd/features/edit.feature
- common/tests/bdd/test_edit_view.py
- common/tests/factories.py
- common/tests/test_views.py
- common/views.py
- conftest.py
- footnotes/tests/bdd/conftest.py
- footnotes/tests/bdd/features/browse-footnotes.feature
- footnotes/tests/bdd/features/detail-footnotes.feature
- footnotes/tests/bdd/features/edit-footnote.feature
- footnotes/tests/bdd/test_edit_footnote.py
- footnotes/views.py
- geo_areas/tests/bdd/features/browse_geo_areas.feature
- geo_areas/tests/bdd/features/detail_geo_areas.feature
- regulations/tests/bdd/features/regulations.feature
This commit modifies our generic Create and Update class-based views to inherit from PermissionRequiredMixin to ensure only users with permission to edit the tariff are allowed to do so. This saves having to use the mixin with every component create and update view class.
Also, I've added a first pass at a generic BDD test for edit views - this currently only tests that a 403 response is returned if the user does not have permission to edit. It would be nice to reduce the copy-pasta by making a generic "I edit \<model> <unique-id>" step, but it's a little out of scope for this PR.
As a bonus, I've added some BDD tests for additional codes and certificates edit views. I haven't touched the footnotes BDD tests for now.
> TP-647: Check users have permission to edit

- common/views.py
Updating a TrackedModel is actually creating a new version, so the permission required
is `add_trackedmodel`
> Fix wrong permission for updates

- .github/workflows/check-pr.yml
- .github/workflows/django.yml
- importer/tests/conftest.py
- importer/tests/test_tasks.py
The object_nursery fixture was maintaining state across tests, leading to failures.
This commit erases the nursery cache between each test.
> Fix importer test shared state

- additional_codes/models.py
- additional_codes/tests/test_models.py
- certificates/models.py
- certificates/tests/test_models.py
- commodities/models.py
- commodities/tests/test_models.py
- common/tests/factories.py
- common/tests/test_business_rules.py
- conftest.py
- footnotes/models.py
- footnotes/tests/test_models.py
- geo_areas/models.py
- geo_areas/tests/test_models.py
- measures/models.py
- measures/tests/test_models.py
- quotas/models.py
- quotas/tests/test_models.py
- regulations/models.py
- workbaskets/models.py
Some business rules (particularly ones which prevent deleting a record) apply if a
record is currently "in use".
For example, if a `FootnoteType` is associated with at least one `Footnote` record, then
that `FootnoteType` is considered "in use".
But if all `Footnote`s that had been associated with the type were then deleted, the 
`FootnoteType` would still consider itself "in use".
Similarly, if a `Footnote` was subsequently associated with the type, but the transaction
containing that association was not yet approved, the `FootnoteType` would still consider
itself "in use".
This change corrects this class of business rules to correctly exclude deleted records
and those in "future" transactions from consideration of whether a record is "in use".
> TP-690: Model in use rules should respect deletes

- certificates/filters.py
- certificates/validators.py
Before, if you searched on type and sid, it would fail. Now you can search on type, sid or both.
> TP-739 Fix certificate search to find type and code together

- .github/workflows/check-pr.yml
- .github/workflows/django.yml
- Dockerfile
- README.md
- package.json
Our CI pipeline is failing due to support for node.js 14.15.1 being dropped.
This change updates our version of node to 14.16.1 - the latest LTS release.
> Bump nodejs

- commodities/business_rules.py
- commodities/models.py
- commodities/tests/test_business_rules.py
- common/business_rules.py
- footnotes/validators.py
- measures/business_rules.py
- measures/models.py
- measures/tests/test_business_rules.py
Only footnotes with a footnote type that have one of three possible application codes are allowed to be applied to commodity codes. This commit implements the business rule NIG18 that ensures only footnotes with the right type can be associated.
It also DRYs up some similar logic for measures, and makes what footnote codes should apply a property of the models themselves.
> Add footnote applicability check to commodity codes

- additional_codes/tests/test_importer.py
- additional_codes/tests/test_xml.py
- certificates/tests/test_importer.py
- certificates/tests/test_xml.py
- commodities/tests/test_importer.py
- commodities/tests/test_xml.py
- common/serializers.py
- common/tests/util.py
- common/xml/namespaces.py
- conftest.py
- footnotes/tests/test_importer.py
- footnotes/tests/test_xml.py
- geo_areas/tests/test_importer.py
- geo_areas/tests/test_xml.py
- importer/namespaces.py
- importer/taric.py
- measures/tests/test_importer.py
- measures/tests/test_xml.py
- quotas/tests/test_importer.py
- quotas/tests/test_xml.py
- regulations/tests/test_importer.py
- regulations/tests/test_xml.py
Here's some self-contained work that has fallen out of the XML performance branch – updates and deduplication of lots of test logic around the import and export features. Merging this now will give a much smaller PR for the XML work later.
> Our importer tests are quite verbose – in particular the same tests are repeated once for creation and again for delete/update. The two tests also have different styles but are functionally equivalent.
>
> There is no real need for this, so this commit removes this duplication. We now instead can simply call `imported_fields_match` once and this will test the importer for all variations of update type.
> Our XML tests validate that the XML we output is valid according to the TARIC3 spec and contain the elements we expect. They do this by checking for …
> Clean up XML and importer tests

- quotas/business_rules.py
- quotas/tests/test_business_rules.py
This rule was the wrong way around – quota definitions that have *started* cannot be deleted but ones that have *not started* yet can be.
> Fix rule preventing quota definition deletions

- additional_codes/business_rules.py
- additional_codes/forms.py
- additional_codes/tests/bdd/conftest.py
- additional_codes/tests/bdd/features/edit_additional_codes.feature
- additional_codes/tests/bdd/test_edit_additional_codes.py
- additional_codes/views.py
- certificates/forms.py
- certificates/tests/bdd/features/edit.feature
- certificates/tests/bdd/test_edit_certificates.py
- certificates/views.py
- common/business_rules.py
- common/forms.py
- common/jinja2.py
- common/models/records.py
- common/tests/factories.py
- common/tests/util.py
- common/views.py
- conftest.py
- footnotes/forms.py
- footnotes/tests/bdd/features/edit-footnote.feature
- footnotes/tests/bdd/test_edit_footnote.py
- footnotes/views.py
This PR addresses both TP-705 and TP-742
Edit forms currently only provide simple field validation (eg, SID matches a regular expression).
We need to prevent users accidentally adding invalid data to the database which would violate the business rules. To prevent this at the earliest opportunity, this commit adds checks for the following:
* When start date is after end date on models which have a validity period
* Selected business rules - some business rules can only be checked across all models in a transaction, some do not make sense in a create/edit form (eg PreventDeleteIfInUse rules)
If these checks fail, the form is redisplayed with error messages, allowing the user to correct the mistakes:
> TP-742: Basic error handling

- additional_codes/serializers.py
- additional_codes/views.py
- commodities/filters.py
- commodities/serializers.py
- commodities/views.py
- measures/filters.py
- measures/serializers.py
- measures/urls.py
- measures/views.py
- quotas/filters.py
- quotas/serializers.py
- quotas/views.py
- regulations/serializers.py
- regulations/views.py
Just cleaning up the APIs to search on the parameters related to what we're looking for in the autocompletes, given that they aren't used elsewhere? 
The search criteria is meant to match how the search suggestion strings display currently, this is likely to change after some UR and we learn how they use the search.
> TP-695 Fix api calls for edit measures

- common/forms.py
- workbaskets/jinja2/includes/workbaskets/workbasket-detail.jinja
- workbaskets/jinja2/includes/workbaskets/workbasket-list.jinja
- workbaskets/jinja2/workbaskets/list.jinja
- workbaskets/models.py
- workbaskets/tests/test_views.py
- workbaskets/urls.py
- workbaskets/views/__init__.py
- workbaskets/views/decorators.py
After successfully editing and publishing a change, subsequent edits do not appear in
the list of tariff changes on the home page.
This is due to the workbasket not being updated in the user session. Subsequent edits
are appended to the already-published workbasket. The home page only lists the contents
of the current workbasket, which is a new and empty one after publishing the last one.
This change ensures that the session is updated on publishing the workbasket, and that
subsequent edits are correctly appended to the new unpublished workbasket.
Before testing make sure to clear your session by logging out and back in again.
> TP-788: Fix edits after publishing workbasket

- commodities/tests/test_business_rules.py
- common/models/records.py
- common/tests/test_business_rules.py
- common/tests/test_models.py
- common/views.py
- conftest.py
- measures/models.py
- quotas/tests/test_business_rules.py
- regulations/tests/test_business_rules.py
- workbaskets/tests/test_models.py
This is a small API change that came out of  discussions with @simonwo around updates.
Renames new_draft -> new_version, (since we don't have a strong concept of drafts in the code at the moment), and more importantly adds a docstring for this.
The docstring was an edit based on an original from Simon:
```
Returns a new version of the object with all of its existing data except where overridden by keyword arguments. This is the function that should be used to update existing models.
The new version will be part of a new transaction in the passed workbasket. If transaction is specified, it will hold the model instead and a new transaction is not created. Ifupdate_type is specified it must be either UPDATE or DELETE – it is UPDATE by default. If save is False, the model won't be saved.
```
> Rename new_draft->new_version and add a docstring.

- additional_codes/import_parsers.py
- certificates/import_parsers.py
- commodities/import_handlers.py
- commodities/import_parsers.py
- footnotes/import_parsers.py
- geo_areas/import_handlers.py
- geo_areas/import_parsers.py
- importer/parsers.py
- importer/tests/test_parsers.py
- measures/import_parsers.py
- quotas/import_handlers.py
- quotas/import_parsers.py
- regulations/import_handlers.py
- regulations/import_parsers.py
This is the first part of the work (started but not finished in firebreak!) to make better use of the database to generate XML envelope output. I'm trying to get as much stuff out of the way which can be merged early to make the later PR more manageable.
This first set of commits is focused around more accurately representing the XML datamodel in the import parsers. This lets us get rid of some custom logic and provides natural extension points which we will use in a later PR to provide serialisation. On the whole though, not much _behaviour_ has changed here – we are just making the import parsers into more accurate data models.
There is some stuff in here which at first glance seems a bit weird (I'd encourage you to read the commit messages) and that we don't use yet e.g. adding the …
> XML performance refactor: part 1

- .gitignore
- Makefile
- README.md
Connecting to the databases in our GOV.UK PaaS hosted environments can be fiddly, requiring multiple CloudFoundry CLI commands and copy-pasting JSON values into command line arguments.
This change adds a few `Makefile` targets so that the process is streamlined a little.
For example:
```sh
$ make paas-login
> Login to PaaS
API endpoint: api.london.cloud.service.gov.uk
Temporary Authentication Code ( Get one at https://login.london.cloud.service.gov.uk/passcode ): 
```
Open the URL above to login and get a code, then paste it into the terminal. You will then be prompted to select a space:
```sh
Targeted org dit-staging.
Select a space:
1. tariffs-dev
2. tariffs-staging
3. tariffs-training
4. tariffs-uat
Space (enter to skip):
```
Then, start the SSH tunnel
```sh
$ make paas-db-tunnel …
```
> Access PaaS hosted DB via SSH

- common/jinja2/common/create_description.jinja
Fixes a data string left in the help text for adding description text.
> Fix incorrect text in HTML description

- additional_codes/tests/test_business_rules.py
- certificates/tests/test_business_rules.py
- common/tests/util.py
- conftest.py
- footnotes/tests/test_business_rules.py
- geo_areas/tests/test_business_rules.py
- measures/tests/test_business_rules.py
- quotas/tests/test_business_rules.py
- regulations/tests/test_business_rules.py
Some of our business rules are only tested fully by fuzzy test cases that sometimes exercise all code paths and sometimes do not. This makes the code coverage vibrate around the true value as some lines are only randomly covered.
So this commit adds positive test cases to:
- ON6
- ME70
- QA5
- ME40
- all uniqueness business rules
> Positive cases for "fuzzy" business rule tests

- common/models/mixins/description.py
- common/tests/test_models.py
Description `__str__` should not raise an exception a field has validity_between instead of validity_start.
Fixes an error that was occuring as one of the fields still referenced valid_between.
AttributeError: 'AdditionalCodeDescription' object has no attribute 'valid_between'
Add very basic test that checks every TrackedModel subclass, via @simonwo
> __str__ don't die if a field has validity_start instead of valid_between

- commodities/import_handlers.py
- commodities/tests/test_importer.py
- commodities/tests/test_xml.py
- common/tests/factories.py
- conftest.py
There was a bug in the indents importer which meant that a commodity code could end up as a parent of itself if an indent is updated without changing any of its fields. This was because the parent search didn't correctly only allow the item id to be equal in the case that the suffix is also less.
This also fixes up some tests to use the import infrastructure which makes it easy to swap out our XML export mechanism later.
> Stop commodity codes being parents of themselves

- README.md
Update the README to explain Python 3.9 is required (for typing mostly)
> Require Python 3.9

- additional_codes/models.py
- additional_codes/tests/test_models.py
- certificates/models.py
- certificates/tests/test_business_rules.py
- certificates/tests/test_models.py
- commodities/models.py
- commodities/tests/test_models.py
- common/business_rules.py
- common/models/mixins/description.py
- common/tests/factories.py
- common/tests/test_business_rules.py
- conftest.py
- footnotes/models.py
- footnotes/tests/test_models.py
- geo_areas/models.py
- geo_areas/tests/test_models.py
- measures/models.py
- measures/tests/test_models.py
- quotas/models.py
- quotas/tests/test_models.py
- regulations/models.py
- regulations/tests/test_models.py
- workbaskets/tests/test_models.py
Adds business rules to Update Types:
- The first update must be of type Create.
- Subsequent updates must not be of type Create. 
- After an update of type Delete, there must be no further updates. 
- Only one version of the object may be updated in a single transaction.
> TP-825 - Add Update Type business rules

- commodities/business_rules.py
- commodities/tests/test_business_rules.py
- common/business_rules.py
- conftest.py
- measures/business_rules.py
* Fixes interpretation of NIG31 – previously this looked at the dates of the additional code and the goods nomenclature, but it should have been looking at the measure.
* Fixes NIG10 to not fire for successors that are deleted (and introduces a new primitive for this).
> Business rule fixes

- package.json
Final fix for today's node update problems. This has been checked using `cf push` and works.
> Use webpack-cli in build script

- .github/workflows/check-pr.yml
- .github/workflows/django.yml
- README.md
- common/business_rules.py
- common/tests/util.py
- importer/tests/test_nursery.py
- measures/views.py
- pyproject.toml
- runtime.txt
- settings/test.py
Same branch as before, just renamed:
Backport typehints to 3.8 so we can use pyston instead of CPython, which completes our tests 30% faster.
Didn't add Pyston to CI, since we still need to make sure things run in CPython as the main runtime, though could add it as an additional interpreter to run at the same time.
This branch, also sets the cache backend to "dummy" during testing, which removes most of the state shared between tests.
> Tp 867 backport typehints to 3.8

- Makefile
- requirements.txt
Use python-xdist[1] to split the tests across many processes.
For a splitting strategy, we choose --dist=loadfile, which loads a file into one process and won't split the tests further, this is pretty conservative and should keep any state that we accidentally share in that file just as we do now.
As a downside `--dist-loadfile` will have slightly worse performance, if one of our files has lots of tests that are especially slow.
I'm anticipating we can move off this later.
[1] python-xdist can split tests over separate machines or processes, using different strategies - in this case we use it to spin up different processes.
> Enable python-xdist with --dist=loadfile

- pyproject.toml
Enable multiple processes when running `python manage.py test`.
> Enable multiprocessing (pytest-xdist) for python manage.py test.

- measures/querysets.py
- measures/tests/test_querysets.py
If we don't set this explicitly they will just output in the order that the components were created which is not always correct.
E.g. sometimes you will get
+ 12.00 GBP / kg 3.00%
when you should get
3.00% + 12.00 GBP / kg
> Make sure duty expressions are ordered correctly

- package-lock.json
Because of the [Dependabot security alert](https://github.com/uktrade/tamato/security/dependabot/package-lock.json/tar/open), I have updated our tar dependency (by running `npm audit fix`).
> Fix tar dependency

- exporter/sqlite/runner.py
There is a problem with the SQLite celery task where shared Python libraries aren't being found. Having confirmed that these libraries do exist where they're expected to in the app environment, I think that what is happening is that the SQLite runner is not accessing them. This PR makes the main process environment available to the SQLite runner, which should help it find libraries located in directories listed in $LD_LIBRARY_PATH.
> TP-859 Make SQLite runner inherit main process env

- common/business_rules.py
- common/tests/util.py
- conftest.py
- footnotes/tests/test_views.py
- workbaskets/models.py
This PR suggests an approach for testing our UI-level functionality by testing views. It introduces a simple primitive that can be used to test the update form for a model. 
These test that:
- when the form is loaded, it shows the correct data
- when the form is submitted, the form knows whether the data is invalid or not
- when the form is submitted, the changes are persisted in the correct way
- any business rules are **not** triggered as part of the form submission
The use of lambdas is to decouple the tests from the factory data… in particular I didn't want the parameters to have to be set out explicitly for each model and duplicate the factory. So instead the current value is passed to each lambda and the result can be mutated (or discarded) as appropriate.
> View-level tests for models

- exporter/sqlite/runner.py
Unfortunately, #356 didn't fully resolve the SQLite problem. By copying over the env variables, the SQLite runner has access to the VCAP_SERVICES env variable, which causes a DB address overwrite (specifically the postgres details it contains): https://github.com/uktrade/tamato/blob/master/settings/common.py#L220 . 
The alternative might be to set `LD_LIBRARY_PATH` explicitly, instead of copying over all the env variables, but I'm concerned this would mean missing out on other hidden ones, and we continue playing 'whack-a-mole' trying to catch the all.
> Prevent SQLite from using the default db

- commodities/business_rules.py
- commodities/tests/test_business_rules.py
- common/models/records.py
The previous version only checked that the parent spanned the code being changed and didn't check that the code being changed continued to span all of its child codes.
> TP-691: NIG2 should check children as well as parents

- common/jinja2/common/edit_description.jinja
We are currently advising users to add colons to HTML links. This isn't correct and produces links that don't work as intended.
> Links should not contain colons

- package.json
The Sass maintainers recommend using Dart Sass instead of Node Sass.
Implementing this change has the added benefit of making Sass work on my
M1 Mac.
* [LibSass is deprecated](https://sass-lang.com/blog/libsass-is-deprecated)
> Replace node-sass with Dart Sass

- common/static/common/js/step-by-step-nav.js
- common/static/common/scss/_step-by-step-nav.scss
- measures/jinja2/measures/create-wizard-step.jinja
In testing, users were confused by the chevrons after the "Show all" / "Hide all" and "Show" / "Hide" links.
Also, the active step indicator does not work.
* The chevrons are removed
* The active step indicator is working.
Additionally
* The styling of the step-by-step navigation has been updated to more closely match the design
NB: the active step indicator does not match the design, but is the default styling of the step-by-step nav component we are using. I think it is a bit more obvious than the indicator in the design.
> Remove show/hide chevrons

- common/business_rules.py
- common/models/mixins/description.py
- common/models/records.py
- common/tests/test_business_rules.py
- exporter/views.py
- importer/utils.py
Previously this only detected a small subset of relations and so didn't run many indirect business rules. It now correctly returns relations and runs all of the appropriate indirect business rules.
> Run all indirect business rules on workbasket clean

- commodities/tests/test_business_rules.py
- conftest.py
- measures/tests/test_business_rules.py
- quotas/tests/test_business_rules.py
In #319 we attempted to stabilize our coverage report by adding some positive test cases to business rule tests. We didn't catch them all, so this commit adds more positive test cases to business rules without them.
Also includes cleaning up some more `raises_if` duplication and unused test code.
> More test cases for fuzzy business rule tests

- manifest.yml
When looking into the disk-space issue for our worker, the Gov PaaS team recommended using the [latest version](https://v3-apidocs.cloudfoundry.org/version/3.97.0/index.html#the-manifest-schema) of the `manifest.py` schema.
> Use v3 syntax for the manifest

- common/views.py
- conftest.py
- workbaskets/admin.py
- workbaskets/models.py
- workbaskets/templates/workbasket_change_list.html
- workbaskets/tests/test_admin.py
- workbaskets/tests/test_models.py
- workbaskets/tests/test_views.py
- Removing code calling upload_workbaskets task from WorkBasket model approve method
- Updating existing tests
- Adding WorkBasket to admin
- Adding custom button Workbasket list page. This button calls the upload_workbaskets task. (See screenshot below)
- Adding tests for custom button
> Tp 929 remove automatic triggering of workbasket export

- common/tests/test_views.py
- common/views.py
- Currently the index page errors if more than one unapproved WorkBasket is found. 
- Instead of throwing an error we should get the most recent unapproved WorkBasket instead.
- Replaces get() with last() when getting unapproved Workbaskets in common/views
- Replaces try / except DoesNotExist block with if statement, since last() will not trigger a DoesNotExist exception
- Adds test for multiple unapproved workbaskets
Original ticket: https://uktrade.atlassian.net/browse/TP-949
> TP-949 - Multiple Workbaskets returned error

- common/models/records.py
This is a fix for bug TP-947 which was caused by an attempt to construct a `GeographicalAreaQuerySet` to include the reverse related descriptions objects.
The underlying mechanism within `TrackedModelQuerySet.with_latest_links()` had recently changed
to include reverse relations that could not by applied to `QuerySet.select_related()`. This fix prevents reverse relations
being applied to `QuerySet.select_related()`.
> Fix for QuerySet.select_related() error in Create Measures

- README.md
- common/jinja2/layouts/_generic.jinja
- settings/common.py
This change is required, in order to support go-live for the service
- In _generic.jinja conditionally add Google Tag Manager script into <head> and noscript into <body> on the basis of whether GOOGLE_ANALYTICS_ID environment variable has been set.
- In settings/common.py add GOOGLE_ANALYTICS_ID environment variable. This should be set in AWS EBS for production only.
- Needs GOOGLE_ANALYTICS_ID to be set as environment variable in AWS EBS prod before deployment.
(Original ticket https://uktrade.atlassian.net/browse/TP-794)
> Tp 794 install google tag manager in to service

- common/tests/test_views.py
- common/views.py
- workbaskets/views/decorators.py
Same error as https://github.com/uktrade/tamato/pull/378
Replaces get() with last() when getting unapproved Workbaskets in require_current_workbasket decorator
> Tp 949 get returned more than one workbasket

- Makefile
- common/tests/factories.py
- common/tests/util.py
- conftest.py
- importer/sheet.py
- importer/tests/test_utils.py
- importer/utils.py
- measures/parsers.py
- measures/patterns.py
- measures/sheet_importers.py
- measures/tests/conftest.py
- measures/tests/factories.py
- measures/tests/test_parsers.py
- measures/tests/test_patterns.py
- measures/tests/test_sheet.py
- requirements.txt
In order to handle a large number of late changes to the tariff that can only be made when the EU have made and published all of their changes to commodity codes, our users need the ability to prepare a bulk set of changes in advance and then upload them all at once. The tactical way to achieve this is to allow them to prepare a spreadsheet offline and then upload it once the commodity codes are present.
This PR introduces a prototype importer that can import measures from a spreadsheet. The structure of the spreadsheet is rigid and has to conform exactly to the spec. For each row in the spreadsheet, one measure is created.
So far this is just the function to run an import, and doesn't include a command line or UI interface because in the basic case we expect this to be run from a …
> TP-904: Import measures from a spreadsheet

- requirements.txt
This is because the way that a new version of pip resolves packages is more strict and doesn't allow wheel only packages anymore. The client team have issued a fix which requires a point version upgrade.
See also: https://ditdigitalteam.slack.com/archives/C1Q2EKZK3/p1633009272197500
- Requires dependency updates? Yes
> Forced upgrade to django-staff-sso-client 3.1.1

- exporter/sqlite/__init__.py
- exporter/sqlite/plan.py
- exporter/sqlite/runner.py
- exporter/sqlite/tasks.py
- exporter/tests/test_sqlite.py
- manifest.yml
- requirements.txt
We've found it too difficult to provision enough temporary disk space on PaaS to create ~3Gb database. 
This commit changes the export to use an in-memory database instad. We've changed wrappers to use apsw instead of the native library so that we can subsequently deserialize the database into bytes and stream it directly to S3.
- Requires migrations? No.
- Requires dependency updates? Yes.
> TP-859: Switch to using an in-memory SQLite export

- measures/filters.py
Updates #405 by removing the `MeasureAutoCompleteFilter` class, because, as @andyhd pointed out, it doesn't make sense to have styling information added to a filter class.
Removes a new `MeasureAutoCompleteFilter` class, replacing it with the standard `AutoCompleteFilter`
> TP-703 (edit) Remove MeasureAutoCompleteFilter

- common/models/records.py
- common/tests/test_models.py
- geo_areas/business_rules.py
We need to purge  the `_getattr_` override in `TrackedModel`. Reasons:
Its sole purpose is to pr
- ovide syntax sugar of sorts, when people can just ask for .current_version when they need to without this overkill override of getattr (that's ALL the override does! - gives you .current_version when you ask for field_current)
- It actually doesn't work well as model.relations would return RelatedManager and ManyRelatedManager in many cases so getattr(self, field_name).current_version would fail there
- It actually could cause recursion issues if a model has a lookup field to itself (as can happen ), because... it calls getattr!  )
- It's only used in one business rule and a couple of tests, so i've swapped out these to call .current_version
- It causes pains when debugging - hasattr calls …
> TP-1039: Get rid of the getattr override in TrackedModel

- settings/common.py
Due to a misconfiguration in our django common settings file, our system currently prints duplicate logs for most modules (because they allow propagation to root logger), and for celery (because celery unnecessarily prints to console as well as celery handler).
- set the propagate attribute to false for each module-specific logger
- make the celery handler the only handler of the celery logger
> TP-1036: Prevent duplicate log outputs

- common/models/mixins/validity.py
- common/tests/test_models.py
- conftest.py
- measures/models.py
- regulations/models.py
At the moment we have a "terminate" method that just works for measures. Actually, termination is something that you can do on anything that is a `TrackedModel` and has a `valid_between` field. So this PR makes this a more general operation that we can use everywhere.
Factors out terminate method, and makes sure that you can call it on every appropriate model (note that it doens't apply to `GoodsNomenclatureIndentNode` because it's not a `TrackedModel`).
- Requires migrations? No.
- Requires dependency updates? No.
> Allow any object with validity dates to be terminated.

- exporter/management/commands/dump_transactions.py
At the moment, the management command in `dump_transactions.py` automatically picks up workbaskets with an APPROVED status.
In the context of HS22, where we may want to lump several workbaskets with EU commodity change imports and MTPO create measures imports, we need to also allow users to select the specific workbaskets they want to package for publishing
- Tweak `Command()` in  the `dump_transactions` management script to accept a list of comma-separated workbasket id-s as an additional optional argument
- Tweak the django db query to fetch the custom workbaskets if the optional argument is provided, and APPROVED workbaskets (existing default behaviour) if not
> TP-1041: Enable selective workbasket xml export

- measures/business_rules.py
- measures/tests/test_business_rules.py
- Currently measure business rule ME12 (If the additional code is specified then the additional code type must have a relationship with the measure type.) uses reverses relationships in its query. This has meant that since measure type 105 has been updated, two measures (20151527, 20151528) are now in violation of the rule.
- Updates the rule to use the through model and adds a test for the scenario described above
> TP-1050: ME12 using reverse relations

- requirements.txt
We now have our own, forked version of the crispy-forms-gds Python package. This package fixes issues in the up-stream version of the package and gives us control over future fixes and changes. We should therefore use our own package.
This PR makes no functional change to the application, but substitutes a like-for-like package (with fixes).
- Requires dependency updates? This is a Tamato dependency update, but doesn't draw in any related dependencies.
See: [uktrade / crispy-forms-gds](https://github.com/uktrade/crispy-forms-gds)
> Point to trade org's crispy-forms-gds package.

- measures/migrations/0009_add_abbrev_to_unit_qualifier_with_code_n.py
When data was present an exception could occur during measures migration.
```python
python manage.py migrate measures    stu@computer  10880  15:02:59 
Operations to perform:
Apply all migrations: measures
Running migrations:
Applying measures.0008_auto_20210628_1641... OK
Applying measures.0009_add_abbrev_to_unit_qualifier_with_code_n...Traceback (most recent call last):
File "/home/stu/.virtualenvs/dit-pyston/lib/pyston3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column measures_measurementunitqualifier.valid_between does not exist
LINE 1: ..._measurementunitqualifier"."trackedmodel_ptr_id", "measures_...
^
The above exception was the direct cause of the following exception:
Traceback …
```
> Fix bug in measures migration when data already present.

- measures/patterns.py
- measures/tests/test_patterns.py
This commit adds a new pattern that can `suspend` and `unsuspend` rates on a code using the common pattern of two additional codes. This is used for policies such as INN, TAPI and UK suspensions for which there is no longer an appropriate EU code.
Modifying these regimes is difficult to get right because there are lots of moving parts – one either needs to delete or restore the original MFN or not depending on the presence of other suspensions. There is also a lot of boilerplate
associated with correctly setting up the measure data.
This code is useful immediately for notebook users making data changes and may also be useful later in the UI.
> Add pattern that helps manage suspensions implemented with additional codes

- additional_codes/models.py
- certificates/models.py
- certificates/tests/test_business_rules.py
- commodities/business_rules.py
- commodities/models/orm.py
- commodities/tests/test_scenarios.py
- common/business_rules.py
- common/models/records.py
- common/models/transactions.py
- common/tests/factories.py
- common/tests/test_models.py
- common/tests/util.py
- conftest.py
- footnotes/business_rules.py
- footnotes/models.py
- footnotes/tests/test_models.py
- geo_areas/business_rules.py
- geo_areas/models.py
- measures/business_rules.py
- measures/models.py
- measures/tests/test_business_rules.py
- quotas/business_rules.py
- quotas/models.py
- quotas/tests/test_models.py
- regulations/business_rules.py
- regulations/models.py
We have a business rule that is applied to all models that ensures, per version group, we only have:
- The first version being a CREATE
- Subsequent versions being an UPDATE or DELETE
- No further versions after a DELETE
At the moment this business rule only expects to be run against the very latest version, and does not work when we run it against earlier versions. This happens routinely when we CREATE and then UPDATE a model in the same workbasket, because when we run the rule against the CREATE it picks up the UPDATE too.
Instead, the business rule needs to be transaction-aware – i.e. only consider data that exists as of a certain transaction.
This PR creates a new filter called `up_to_transaction` – which is simplified using @stuaxo's work on partitions. This is broadly the same …
> Fix update validity business rule to consider transactions in order.

- .github/workflows/django.yml
The `docs` Github Actions build step is misconfigured
> Fix docs upload

- measures/forms.py
- measures/jinja2/measures/create-wizard-step.jinja
- measures/views.py
A recent change allowing users to enter no Condition Codes or Footnotes when creating a Measure meant that the wording on their respective steps did not describe intent accurately to the user. This change updates the wording on those Create Measure steps for Condition Codes and Footnotes and clearly describes optionality.
This PR adds an `info` element to `conditions` and `footnotes` elements of the `MeasureCreateWizard.STEPS` list. The approach maintains consistency with the intent of that list to provide step-specific information that is accessible within templates. The `info` element is rendered as informational text on a step only if it is defined (currently only for Condition Codes and Footnotes).
> TP-1059 Word change on conditions and footnotes

- exporter/sqlite/tasks.py
- exporter/storages.py
- exporter/tests/test_sqlite.py
This is to keep S3VFS a bit of an implementation detail of TaMaTo, and to make sure that that data-flow doesn't attempt to ever read a partially constructed s3vfs SQLite database: if there is a whole single file SQLite database, then it's really unlikely there was an error, or than an export is 1/2 way through.
It also essentially reverts to the same behaviour in terms of communication-via-S3 as before S3VFS was introduced: single-object "regular" SQLite databases are what are transferred via S3.
It first deletes any S3VFS objects from any previous export of the same database that may have failed half way through (which is likely to be seen as a corrupt database)
After exporting the tariff to an S3VFS as it did before this PR, it then serialises this to an object which has a key which is …
> feat: serialize sqlite file for ingest into data-flow

- exporter/sqlite/tasks.py
- exporter/storages.py
- exporter/tests/test_sqlite.py
The change in https://github.com/uktrade/tamato/pull/430 resulted in what seems to be multiple SQLite exports happening at the same time on the same S3VFS database, which caused corruption. The export is triggered every 30 minutes, and there were assumptions that each export would take < 30 minutes and/or multiple export tasks cannot run at the same time. These seemed incorrect.
This fixes the corruption issue by aborting the SQLite export if at least one block has been written to S3, which happens very soon after the start of the export, rather than aborting if the serialized SQLite file has been written, which happens right at the end of the export.
The consequence of this is that exports that fail after the 1st block is written are not automatically recovered from. However, once new …
> fix: sqlite export

- common/filters.py
- common/tests/factories.py
- common/util.py
- exporter/sqlite/plan.py
- measures/business_rules.py
- measures/filters.py
- measures/models.py
- measures/querysets.py
- measures/tests/test_business_rules.py
- measures/tests/test_models.py
A measure can have either an explicit or implicit end date, where the implicit version is specified by the regulation. Our previous algorithm for finding the implicit end date was not correct, because it reported lots of EU measures as still being in force when clearly (as enforced by ME32) they could not be.
This commit fixes the algorithm, and also ensures that when the value is requested from a measure for which it was not pre-loaded, it is calculated in the same way.
The new algorithm has been found through examination of the existing data and comparison with the Online Tariff service as a known good source. E.g. I found EU measures that the system considers still active using:
```python
Measure.objects
.with_effective_valid_between()
.filter(
sid__lt=20000000, # exclude UK measures …
```
> Fix measure effective validity calculation

- measures/business_rules.py
- measures/tests/test_business_rules.py
At some point in the past, ME67 has been disabled, probably due to a faulty implementation that was firing on seed data erroneously.
However, our data does need to abide by ME67 and we have had a number of recent cases where we've failed to do so because this rule is disabled.
This commit restores ME67 and adds to its tests to ensure that it behaves correctly.
> Return ME67 to active service

- common/models/transactions.py
- common/tests/test_transactions.py
At the moment `common.models.transactions.TransactionQueryset.unordered_tracked_model` returns any and all models in the database. 
This is unintended and the filter condition `transaction__in=self` applied later in `ordered_tracked_model` should be moved to this method instead.
Move the  filter condition `transaction__in=self` to the unordered method
> Fix: Unordered Track Models are constrained to those linked to the TransactionQueryset

- common/models/trackedmodel.py
Historically, `TrackedModel._get_version_group()` has only looked at `latest_approved()` versions of a model when looking for a version group.
However, when importing a large taric envelope, it is possible to have the same model created and then updated in the same workbasket.
This ticket is to enable that.
Enhance `TrackedModel._get_version_group()` to support the extra lookup functionality
> TP-1087 Find a version group created in the same draft workbasket

- additional_codes/tests/test_views.py
- certificates/tests/test_views.py
- common/tests/util.py
- footnotes/tests/test_views.py
- geo_areas/tests/test_views.py
- measures/tests/test_views.py
- quotas/tests/test_views.py
- regulations/tests/test_views.py
While there is a bit of duplication here, it's probably better than having one big test in common.
It's also useful to separate these from the detail view tests, even if the code is pretty similar.
In future these tests, and the view tests should probably be refactored and expanded to verify
the expected data is included in the output.
This was split out from TP-1067.
The tests here ensures list views are at the expected locations, and render without raising any exceptions (the simplest / dumbest but still useful test).
This adjusts the infrastructure built for TP-1067, (which is does things like grab every class based view and verify the URL matches some starting string) and generalizes a little to also work with list views.
In theory this could all be one big test, but splitting over …
> TP-1084 Verify list views return 200 and are in available on the expected URLs.

- commodities/import_handlers.py
- commodities/models/orm.py
As part of the TP-1037, we fixed goods nomenclature node end dating issues.
One of the new methods attached to `GoodsNomenclatureIndentNode` (`get_parent_node`) exposes an as_of_transaction argument, which should be used when the method is called from within the date span loop in commodities import handler.
This bug fix addresses that issue as well as a method name issue in the same model.
- call to `get_parent_node` in commodities.import_handler date span loop passes an `as_of_transaction` arg
- the name of the `get_succeeding_node` method is fixed and the property decorator is removed
> TP-1089 fix get parent node call arguments

- additional_codes/tests/test_views.py
- certificates/tests/test_views.py
- commodities/import_handlers.py
- commodities/models/orm.py
- common/models/transactions.py
- common/tests/test_transactions.py
- common/tests/util.py
- footnotes/tests/test_views.py
- geo_areas/tests/test_views.py
- measures/tests/test_views.py
- quotas/tests/test_views.py
- regulations/tests/test_views.py
In some cases, e.g. we import commodity code changes, we may add preemptive transactions to the draft import workbasket, e.g. to deal with side effects on other models and avoid business rule violations.
This ticket enhances workbasket.approve(), which is also responsible for reordering workbasket transactions, to support non-contiguous transaction orders in a workbasket.
Add a new method to TransactionQueryset that assumes all responsibility for reordering workbasket transactions
> TP-1088 Support reordering when workbasket transaction order is not contiguous

- common/models/mixins/description.py
On the tariff changes table the link for a newly created description is empty ("#") and doesn't link to the described model descriptions tab as it should. This is because get_url in DescriptionMixin is looking for a url with a name of the format "'certificate_description-ui-detail", which doesn't exist.
It seemed simpler to add two lines to the DescriptionMixin.get_url method than to create a redirect view and register another url for different description models (e.g. https://stackoverflow.com/questions/63467337/django-hashtags-in-url)
> TP-856: Structure code links in the tariff changes view don't work for descriptions

- commodities/models/orm.py
- commodities/tests/test_util.py
- commodities/util.py
At the moment `GoodsNomenclatureIndentNode._get_restricted_valid_betwen` does not handle well cases with non-overlapping dates, which can legitimately occur. This has emerged as a secondary issue blocking 887.
- `GoodsNomenclatureIndentNode._get_restricted_valid_betwen` now calls `commodities.util.contained_date_range` instead of trying to replicate its logic. The latter method is already well covered with tests, including cases with non-overlapping dates.
- Allow `commodities.util.contained_date_range` to return a customisable fallback value in case of non-overlapping end dates
> use existing util.contained_date_range

- commodities/models/dc.py
- commodities/tests/test_dataclasses.py
- commodities/util.py
- common/util.py
At the moment, when `CommodityCollection._get_snapshot_commodities` selects the matching commodities for a given transaction or calendar moment, it makes a large number of individual select queries involving `GoodsNomenclature`, `TrackedModel`, and `VersionGroup` objects.
As a result, if we need to take a snapshot of a larger branch (e.g. when a 2-level code and all its descendants), this would become a very expensive process
- Implement a more efficient algorithm in `CommodityCollection._get_snapshot_commodities` that has exactly ONE db round trip regardless of the size of the tree.
- Implement an enabling util method `get_latest_versions` that returns only the most recent version of each model within a queryset result 
- As a related necessary change, switch transaction clock in …
> TP-1096 Fix exploding db round trips in commodity tree snapshots

- common/models/mixins/description.py
- measures/business_rules.py
- measures/tests/test_business_rules.py
"Our current implementation doesn't run the rule if there is no certificate, but actually, this rule should still apply. I.e. there should only be one measure condition with "no required certificate" per measure condition code."
- Update ME58 to filter by kwargs set conditionally on whether a measure_condition has a required_certificate
- Add case to business rule test
> TP-1020: ME58 should cover conditions without certificates as well

- common/models/transactions.py
- common/querysets.py
Little docstring update...
This thing *really* confused me, even though I added the infrastructure on which it sits and it just uses it.
Not an indictment on this code: it makes sense, but I think I'd forgotten a bunch of context.
I hadn't thought about the fact that `partitions` are in fact temporal themselves, so `earlier` partition threw me a bit.
I had a bit of a go at condensing some bits of the docstring and splitting others + added context for the temporal bit.
> Iterate docstring in as_at_transaction_filter.

- common/tests/util.py
- conftest.py
- footnotes/tests/test_views.py
- regulations/tests/test_views.py
We have some view tests that try to test update forms. These often based on the date because they try to naively add 1 to a date or month counter, and this often results in invalid dates (e.g. the 32nd March).
This commit changes the system to add amounts to the date using a relative delta. To do this, the model needed to change from being based on a lambda for each field, to a single lambda that returns all of the new form data.
> Fix view tests that fail around month end.

- commodities/models/dc.py
- commodities/tests/conftest.py
- commodities/tests/test_dataclasses.py
- commodities/tests/test_importer.py
- commodities/tests/test_scenarios.py
- common/models/tracked_qs.py
- common/models/trackedmodel.py
- conftest.py
- measures/business_rules.py
- measures/models.py
- measures/snapshots.py
- measures/tests/test_business_rules.py
- measures/tests/test_models.py
- workbaskets/models.py
Our previous implementation of ME32 used the Nodes contained in the Goods Nomenclature tree to check for overlaps between commodities. We have found these Nodes difficult to maintain (it's a 3D-cube of commodity trees!) and subsequently the data structure is wrong in many places.
This leads to false positives and (presumably) false negatives from ME32.
This commit introduces a new implementation of ME32 that does not use the tree and insteadmakes use of the in-memory tree used for the commodity code importer.
- Requires migrations? No.
- Requires dependency updates? No.
> TP-758: ME32 without the materialized tree

- package-lock.json
We need to upgrade json-schema from 0.2.3 to >0.4.0
I ran `npm audit fix` to resolve the issue and update package lock json file to update jsprim and json-schema
> TP-1116 json-schema is vulnerable to Prototype Pollution

- measures/snapshots.py
This is to avoid an AttributeError when self.ancestors[commodity.identifier] is called in commodities/models/dc.
MeasureSnapshot.overlaps returns an empty queryset, if no commodity is found
> TP-1123: MeasureSnapshot.overlaps() should check commodity exists before calling get_branch_measures(commodity)

- commodities/models/dc.py
- commodities/tests/test_dataclasses.py
- common/models/dc/base.py
For 999L we need to be able to work out what the common ancestor of a group of commodities is. This PR adds that function.
Finding a common ancestor is easy when we already have `get_ancestor` and just use sets. But…
Previously it wasn't possible to put `Commodity` objects into containers because they were mutable and therefore unhashable.
This PR makes more use of the dataclass features to automatically generate hashes and string representations, and therefore makes these objects immutable by default.
It also changes to using SIDs as identifiers instead of combinations of other fields which is a more accurate and straightforward way to identify each object.
> TP-1070: Find common ancestors of multiple Commodities

- common/tests/factories.py
- measures/business_rules.py
- measures/tests/test_business_rules.py
In TP-1020 we made it so that users could not add more than one condition with the same certificate. This works for all certificate-based conditions, but it is not correct for conditions with volumes (under e.g. condition code E).
ME58 will now stop users from adding conditions that use volume amounts, because these conditions don’t have certificates and the rule thinks this is a duplicate of the base case where nothing is supplied. 
So this commit fixes the rule to only enforce that the combination of certificate + volume + unit is unique.
> TP-1125: Make ME58 consider volumes and units as well

- measures/parsers.py
- measures/tests/conftest.py
- measures/tests/test_parsers.py
9-type certificates do exist (national certificates)we need to fix the CONDITION_PHRASE_PATTERN in the ConditionSentenceParser to accommodate this
Modify the condition phrase  pattern to allow for 9-type certs and add a test case
> TP-1118 Allow 9-type Certificates

- commodities/models/orm.py
- commodities/tests/test_business_rules.py
"NIG12 is not included in GoodsNomenclature model's direct BR, while it should be (it's only included as an indirect on GoodsNomenclatureDescription model, but that's not enough)."
Adds direct rule to GoodsNomenclature and tests that this is being called
> TP 1122: Add NIG12 to direct BR-s on GoodsNomenclature

- requirements.txt
A vulnerability "affects the package celery before 5.2.2. It by default trusts the messages and metadata stored in backends (result stores). When reading task metadata from the backend, the data is deserialized. Given that an attacker can gain access to, or somehow manipulate the metadata within a celery backend, they could trigger a stored command injection vulnerability and potentially gain further access to the system."
Updates celery[redis] to >=5.2.2 in requirements.txt
Requires you to run 'pip install -r requirements.txt'
https://uktrade.atlassian.net/browse/TP-1156
> update celery to >=5.2.2 in requirements.txt

- commodities/models/dc.py
- measures/business_rules.py
- measures/tests/test_business_rules.py
Previously, the measure set used by ME32 would sometimes only return measures in `latest_approved`, whereas it should always be scoped to the passed transaction.
We had no test that draft data was considered, but now do.
> Ensure ME32 always considers draft measure versions

- package.json
* Tamato is currently pinning to a specific patch-specific version of Node.
* Cloud Foundry no longer makes the pinned version available and so builds are failing (because of the missing version of Node).
* Don't pin to a patch version of Node and npm.
* Pin to a more general version of Node and npm, which (hopefully) guarantees Node and npm availability within buildpacks.
See: [Report to SRE with suggested action](https://ditdigitalteam.slack.com/archives/C1Q2EKZK3/p1642616596104100)
> Remove pinning to an exact minor version of Node.

- package-lock.json
Because of this dependabot alert: https://github.com/uktrade/tamato/security/dependabot/package-lock.json/nanoid/open
I've run `npm update` to fix all known vulnerabilities in the `package.json` file, so it would be worth running `npm install` locally once this is merged.
> TP-2000-48 Fix nanoid npm vulnerability

- Procfile
Increase gunicorn timeout to 120 seconds to stop large uploads timing out.
> Increase timeout to 120 seconds to help large upload.

- commodities/business_rules.py
- commodities/models/orm.py
- common/business_rules.py
- common/models/managers.py
- common/models/mixins/description.py
- common/models/trackedmodel.py
- common/tests/test_models.py
- docs/source/api/index.rst
- docs/source/architecture/index.rst
- measures/models.py
- quotas/models.py
Implements ADR-15.
When tracked models exist in a one-to-many
relationship (such as how one parent object can
have many descriptions) each description object
will hold a foreign key back to the parent object
that specifically links to the version it was
created against.
Parent X (primary key = 1)
Description X (primary key = 2, parent = 1)
Calling the reverse relation on the parent will
correctly discover the descriptions:
parent.descriptions
If that parent object is updated, it receives a
new row in the database, but the descriptions are
not updated. This means that the reverse
relationship now no longer returns any objects,
because the reverse relationship by default tries
to find descriptions that have the primary key of
the *new* parent object:
parent_v2 = parent.new_version(...) …
> Fix reverse relations on all TrackedModels

- common/business_rules.py
- measures/business_rules.py
- measures/tests/test_business_rules.py
- quotas/business_rules.py
- quotas/tests/test_business_rules.py
In the previous implementations of ME66 and ON14, even memberships that had been deleted would be considered as valid memberships that prevented the business rule from triggering.
This implementation abstracts out the common logic in these rules and adds tests that neither will consider a membership that has been deleted.
> Make sure geo exclusion business rules don't consider deleted memberships

- common/models/mixins/description.py
- common/models/trackedmodel.py
If a described_object get_url() returned None an error occured on the index page.
> Bugfix - described objects with no url should not break the homepage.

- conftest.py
- footnotes/tests/test_forms.py
- measures/forms.py
- measures/jinja2/measures/edit.jinja
- measures/models.py
- measures/parsers.py
- measures/tests/conftest.py
- measures/tests/test_forms.py
- measures/tests/test_models.py
- measures/tests/test_util.py
- measures/util.py
The ability to edit duties is in the original designs, but currently missing from editor functionality
- Adds a diff_components method to `Measure` to determine whether to create, update, or delete components 
- Adds logic to `MeasureForm` to ensure that this method is only called when user has changed or added a duty value
- Adds unit tests for three `diff_components` scenarios and form logic
- Adds conftest fixtures to make it easier to create an instance of `MeasureForm`
- Deletes unused measure util, `clean_duty_sentence`
This [bug](https://uktrade.atlassian.net/browse/TP2000-100) was discovered while doing this ticket and so we should let the tariff managers know that until it's fixed the displayed value will look like it's duplicated (see screenshot below)
> Tp 1162 edit duties

- additional_codes/urls.py
- additional_codes/views.py
- certificates/tests/test_views.py
- certificates/urls.py
- certificates/views.py
- common/jinja2/common/index.jinja
- common/paths.py
- footnotes/tests/test_views.py
- footnotes/urls.py
- footnotes/views.py
- geo_areas/filters.py
- geo_areas/jinja2/geo_areas/detail.jinja
- geo_areas/jinja2/geo_areas/list.jinja
- geo_areas/jinja2/includes/geo_areas/list.jinja
- geo_areas/models.py
- geo_areas/tests/bdd/test_browse_geo_areas.py
- geo_areas/tests/test_views.py
- geo_areas/urls.py
- geo_areas/views.py
- measures/jinja2/includes/measures/list.jinja
- measures/urls.py
- quotas/jinja2/includes/quotas/list.jinja
- quotas/urls.py
- quotas/views.py
- regulations/urls.py
We already have a set of naming conventions that we are using the UI for views, e.g. "list" is the page that shows all the things, "edit" is the page that updates a thing, etc. We use these conventions already to name our routes and views, but we also have to list them manually in every url module.
This increases the surface area that needs to be touched every time we need to add new features. If we are about to implement a lot of new views for deletions, this will save needing to update the URLs manually every time.
This commit removes the need to endlessly hardcode our routes by auto-generating the routes based on what views are present. It will silently ignore views we don't have yet, so when we add a new view to do a certain job (e.g. deleting a certificate) no more configuration is …
> Use naming conventions to auto-generate routes

- additional_codes/views.py
- certificates/views.py
- common/models/trackedmodel.py
- common/views.py
- footnotes/views.py
- regulations/views.py
- workbaskets/tests/test_views.py
- workbaskets/views/generic.py
- workbaskets/views/mixins.py
This commit ensures that no database changes are persisted until any business rules are passed as specified by `validate_business_rules`.
This change is necessary because calling `new_version` with `save=False` still creates a transaction, which results in lots of empty
transactions being created. The new behaviour only calls `new_version` when we are sure that the model will be saved.
> TP2000-105: Only persist changes if business rules are passed

- footnotes/tests/test_views.py
- workbaskets/models.py
- workbaskets/tests/test_models.py
Django forms will automatically run clean methods on models. At the moment, our workbasket clean method is running all business rules, so despite running transitions in a background thread the rules are still being checked in a web thread.
This commit changes that so that business rules are not validated as part of a normal `clean` and users will need to call `clean_transactions` specifically to do that.
> TP2000-77: Remove business rule validation from workbasket validation

- common/views.py
- measures/tests/test_views.py
- measures/views.py
MeasureUpdate view, which inherits from TrackedModelChangeView, was no longer calling MeasureForm.save(). So the ui was transitioning as normal and returning the right status codes, but the duties and footnotes weren't being updated correctly.
- Overrides get_result_object on MeasureUpdate view to call form save()
- Updates measure edit view test to check that components are actually updated
- Adds view test to check that MeasureForm.save() is called
> TP-2000-144 - Measure edit form still broken

- workbaskets/models.py
- workbaskets/tests/test_views.py
- workbaskets/views/decorators.py
At the moment, any workbasket in a non-approved state can be selected as the currently active workbasket. This isn't right because users shouldn't be editing baskets once they are `PROPOSED` and shouldn't be stuck editing a basket that is `ARCHIVED`. Essentially, they should only be editing baskets in the `EDITING` state.
This commit makes sure that the current workbasket is in `EDITING` and if not, picks the next available `EDITING` workbasket. If there is none, it creates one as before.
> Only `EDITING` workbaskets should be used for editing

- pyproject.toml
Ignore more directories to speed up startup for testing.
Saves about .5 second when collecting tests locally (these add up when running just one test).
> pytest - pyproject.toml - Ignore more directories to speed up startup for testing.

- requirements.txt
We're seeing APM disconnect timeouts in deployments when Django migrations run. We spotted a few issues in the currently deployed package that may be candidates for causing this issue and have since been fixed..
Upgrade to latest version of `elastic-apm` within our `requirements.txt`.
> Bump elastic-apm version to latest.

- importer/taric.py
We have recently had issues that have prevented our imports from completing successfully. In these cases we've been left with the database in a inconsistent state and in order to reattempt the import we have to restore the database from a backup.
As discussed, this commit changes the behaviour so that now an entire import is run inside a single database transaction. If there is an error that causes the import to bomb out, the changes are removed, and the issue can be fixed and the import reattempted more easily.
This applies to imports at the "chunk" level. Most import jobs will only generate one chunk, so that is equivalent to a single file. For imports that span across multiple independent chunks, each chunk will have to be manually restarted.
> Run imports inside a single database transaction

- additional_codes/tests/test_views.py
- additional_codes/views.py
- certificates/tests/test_views.py
- certificates/views.py
- common/jinja2/includes/common/tabs/descriptions.jinja
- common/paths.py
- common/tests/test_models.py
- package-lock.json
This fixes the 'create descriptions' url for various models. This is an interim fix to allow production service to create new descriptions. 
There is more to be done to clarify the url reversal generation patterns, particularly when integrating the descriptions url lookup. In particular, we need to make sure that the 'create descriptions' url is available on the instances being described rather than on description instances themselves. This will take some work to be done in a way that is consistent with other patterns while also remaining readable. (Linked JIRA ticket https://uktrade.atlassian.net/browse/TP2000-197)
Returns a 'description-create' pattern to the url generation pattern list.
> TP2000-181 add description-create to list of potential actions

- common/util.py
- measures/business_rules.py
- measures/models.py
- measures/querysets.py
- measures/tests/test_business_rules.py
- regulations/models.py
We never implemented this rule because we thought we weren't using replacements in the UK. We're still not, but if a user  accidentally?) selects an EU regulation it's possible for the rule to be broken. Selecting EU regulations is still necessary because the UK has "retained" some EU legislation and it is still valid to choose it.
> Implement ME27 for regulation replacements

- geo_areas/forms.py
- measures/patterns.py
- measures/tests/conftest.py
- measures/tests/test_views.py
- measures/views.py
Component sequence numbers start at 1 not 0, fixing the importer.
Make `test_measure_form_wizard_create_measures` a little more batch oriented making it easier to test this, should save some queries too.
> TP2000-156 - Component sequence number start at 1, fixing the importer.

- measures/views.py
Measure wizard was missing an import for 'render' as used in its 'done' method.
Possibly indicates a gap in our testing too though.
> Fix missing import for 'render' in measure wizard view.

- Procfile
The Gunicorn process appears to be time-out when performing long running measures searches. This change aims to ensure search related queries complete within the timeout period.
Increase the gunicorn process timeout period to 600 seconds.
> Increase gunicorn timeout.

- common/models/mixins/validity.py
- measures/apps.py
- measures/models.py
- measures/patterns.py
- measures/signals.py
- measures/tests/test_business_rules.py
- measures/tests/test_signals.py
- regulations/tests/test_business_rules.py
At the moment it's not possible for users to add or remove end dates to measures because they aren't able to make a corresponding edit to the terminating regulation. This behaviour is also handled in a number of bespoke places in the code base.
This commit unifies that logic into a signal that is fired pre-save, so no matter where the edit to the measure is happening the logic will be applied. This also lets us remove some redundant code.
We also take the changed commodity code handling logic out into a signal.
The ``mute_signals`` decorator is necessary for ME33 and ME34 so that it _is_ possible to create test data that ignore this logic.
> TP2000-206: Automatically select terminating regulations

- common/static/common/js/application.js
- common/static/common/js/autocomplete.js
Autocomplete fields are only used in the client and have no purpose on the server, but current behaviour submits their contents to the server (as URL encoded params on many of Tamato's forms). This can cause undesirable side-effects.
[the auto](https://github.com/alphagov/accessible-autocomplete) allows setting the name attribute of the autocomplete field. This PR allows setting it to an empty value and thereby avoids submitting its value to the server.
> Optionally omit the 'name' attr of dummy autocomplete fields.

- .github/actions/setup-python/action.yml
- common/jinja2/components/measure_condition_action_code/template.jinja
- common/jinja2/components/measure_condition_code/template.jinja
- common/jinja2/components/measure_condition_component_duty/template.jinja
- common/static/common/js/application.js
- common/static/common/js/conditionalMeasureConditions.js
- common/static/common/js/showHideCheckboxes.js
- common/static/common/js/util.js
- measures/forms.py
- measures/tests/test_forms.py
As different measure conditions expect different supporting data, to make data entry easier, this hides any measure condition form fields that are not relevant for a particular `MeasureConditionCode` or `MeasureAction`. _For more information, see: https://uktrade.github.io/tariff-data-manual/documentation/data-structures/measure-conditions.html#condition-codes_
This adds a new JavaScript file that allows for conditional rendering of individual fields in the measure conditions form. (The form will still work without JavaScript, but will not have the option of hiding fields for clarity, so there is some progressive enhancement).
New Jinja templates have been added so that the triggers for hiding particular fields are generated from the `MeasureConditionCode` and `MeasureAction` instances …
> TP2000-214 Add conditional rendering to MeasureCondition form

- measures/forms.py
- measures/tests/test_views.py
- measures/views.py
The duties field on the commodities / duties step of the wizard should not be required because it should be possible to create a measure without a duty amount.
The wizard get_form_initial method also should be update because there is no longer a step called "duties", which means that duty validation is not being called and we are seeing 500 parse errors. This validation should also be called for the "conditions" step.
- Make duties field required on form and update get_form_initial method
https://uktrade.atlassian.net/browse/TP2000-238
> TP2000-238 Duties field is required on Measure create wizard commodities / duties step

- measures/jinja2/measures/create-wizard-step.jinja
* The steps sidebar took up space and didn't provide value
* It also made it necessary for us to code the wizard in such a way that the steps could be completed in any order, adding complexity
* Removing it will simplify this code
* Removes the sidebar from the measure wizard template
* `step_metadata` is still used by other parts of the templates so this stays
- No migrations necessary
- No dependency updates necessary
> TP2000-254 Remove create measures wizard sidebar

- common/tests/test_xml_util.py
- common/tests/util.py
- common/xml/namespaces.py
- common/xml/util.py
- conftest.py
- exporter/apps.py
- importer/apps.py
- importer/management/commands/filter_taric.py
- importer/management/commands/renumber_taric.py
- importer/management/commands/renumber_transactions.py
- importer/taric.py
- quotas/tests/test_xml.py
- settings/common.py
As part of our operational process to keep Production in line with data changes made on engineer machines, it is sometimes necessary to manually renumber or filter TARIC XML files to avoid data created on Production clashing on auto-picked ID numbers.
This PR adds three new tools (`renumber_records`, `renumber_transactions` and `filter_transactions`) that can be run against XML files, and tests for them.
> Tools to filter and renumber TARIC XML files.

- measures/tests/factories.py
The `test_measure_sheet_importer` test has been failing recently on the CI. Gabe had included a fix on his PR, however, hir PR is not ready to merge yet. This PR is literally just taking that fix and putting it in a separate PR.
The tests are failing due to the row missing a geographical area description. The MeasureSheetRowFactory which is a function that makes fake measures sheet rows for us for use in tests is not giving a description or excluded descriptions. This is because the function that goes and gets the descriptions, doesn't have the transaction argument it needs. 
This code just gives it that.
> Amend code in the MeasureSheetRowFactory to include missing argument

- measures/jinja2/measures/create-start.jinja
This PR adds additional text to the create measures start page in order to inform a user of the information they need in order to create a measure. 
This will prevent users from partially completing the form, only to find that they have to go back and lose all their work as they've missed an important piece of data, or didn't create something they needed for this process first. 
Due to the nature of the tool not having drafts, or versioning for creating a measure, the next most appropriate measure is to ensure that the user is adequately prepared to complete this process in one sitting. 
This PR adds text to the page to highlight what information is needed to create a measure. It goes from looking like this: 
...To looking like this:
> New content to be added to the start page of the Create Measures journey

- geo_areas/forms.py
- measures/tests/test_forms.py
Currently users can go through the create measure journey without selecting a geographical area in the measure details form. This causes a 500 on the summary page when trying to render the geographical area's description.
- Add a validation error on the measure details form when a user hasn't selected a geographical area
- Updates tests to include a default erga omnes value
> TP2000-195 Users can get a 500 error if they fail to select a geographical area

- common/tests/test_xml_util.py
- common/xml/util.py
- importer/management/commands/renumber_taric.py
There is a bug in the XML renumbering tools that incorrectly renumbers IDs in records that are CREATEs but that don't actually use the given ID as an identifier and instead use it a foreign key.
For example, if a file updates a measure by CREATEing a `MeasureComponent`, the script will interpret the creation of the component as a new measure and renubmer the SID. Instead, it should ignore it.
This commit adds a parameter to the renumbering function that is the name of the TARIC record that the ID refers to. Only records of that type that are CREATED will cause renumbering to happen.
> Make XML record renumbering be aware of records.

- geo_areas/forms.py
- geo_areas/tests/test_util.py
- geo_areas/util.py
- manage.py
- measures/forms.py
Currently `with_description_string` returns a queryset with duplicate geographical areas where a geographical area has more than one associated description. The old logic which used `structure_description` and was [replaced in this PR](https://github.com/uktrade/tamato/pull/548) accounted for this by calling `descriptions.last()` but this was really expensive in terms of SQL queries and made the page too slow. 
- Renames `with_description_string` to `with_latest_description_string` and adds filtering logic to return only the latest descriptions by `validity_start_date`. (I know we don't normally annotate and filter in `with` methods, but I think the annotation by itself isn't something we want anywhere)
- Adds test for this multiple description scenario
- Updates edit form geo area …
> TP2000-309 GeographicalArea.MultipleObjectsReturned error on measure edit form

- checks/querysets.py
- checks/tasks.py
- checks/tests/test_tasks.py
Archived workbaskets were being included in business rule checks.
This updates requires_check to exclude archived workbaskets by default.
Not done here - is hooking up the `ignore_archived` flag to give control of this through the whole stack, but could be if desired.
> filter archived workbaskets from business rule checks.

- checks/tasks.py
- settings/common.py
update_checks seems to be monopolising the workers stopping other tasks from running.
Rate limit update_checks to only once per minute per worker and trigger it only once per minute.
rate limiting isn't anywhere near the full fix for this, but it's very trivial to add while we put through fixes that need more investigation.
This should help a little towards giving our other tasks a chance to run.
> rate limit to update_checks and only trigger it once per minute.

- checks/tasks.py
- workbaskets/tasks.py
Use the celery logger in celery tasks, adding task information to the log messages.
This adds useful information, such as the task status, which is handy for debugging.
Celery itself also provides some functionality to output these.
During local development celery logs output in the terminal the celery worker is in, and the log level is controllable from the commandline.
> Add task information to logs from celery task by using celerys logger.

- checks/tasks.py
- common/models/transactions.py
- common/models/utils.py
- common/tests/test_models.py
- common/tests/test_models_utils.py
- pii-ner-exclude.txt
Improve logging for transactions outputting a summary transaction and workbasket pk and status.
Info is fetched only during stringification so cost is only incurred if logging is enabled.
In the example below it is easy to see that transactions in archived workbaskets are being checked..
> TP2000-339 - Log transaction summaries including partiton, workbasket, workbasket status.

- measures/forms.py
- measures/tests/test_views.py
- pii-ner-exclude.txt
Whenever the user clicks "save" on the measure edit form we create a new update version of the measure, even if the data hasn't changed. If that measure has a footnote associated with it, the logic in `MeasureForm` save will then create a new footnote association. This leads to duplicate footnotes and causes an ME70 violation. We should instead update the existing association to point at the new, updated version of the measure.
Adds a check in `MeasureForm.save()` to see if an a footnote association exists before creating a new one.
> TP2000-340 Measure edit form creates new FootnoteAssociationMeasure instead of updating the existing

- measures/jinja2/measures/create-review.jinja
- measures/tests/test_views.py
* Checks the exclusions list is populated before trying to iterate over it
* Adds a simple assertion to the wizard test to make sure each step of the wizard returns 200 on GET
> TP2000-345 Fix measure summary 500 when no geo area exclusions

- certificates/forms.py
- certificates/jinja2/certificates/create.jinja
- certificates/tests/test_forms.py
- certificates/tests/test_views.py
- certificates/views.py
- common/jinja2/common/index.jinja
Currently, the Tariff Managers don't have the ability to make new certificates, however we think that's a bit silly. This PR adds a Create Certificates form, and a link on the home page, to allow TM's to make new certificates. 
A new form has been added to the tool, that allows TM's to create their own certificates. It's a very similar process to footnotes, just with certificates instead. Once a certificate has been created, you get a nice looking success message like you do with footnotes, but beyond that nothing else has changed. 
here's a photo for you to enjoy: 
!! psa to anyone reviewing this - please let me know if I've missed out on any tests. I've copied the setup for footnotes, but it feels a bit little. If there's any other tests I could add, or any types of tests I've missed, …
> TP2000 242 build create certificate form

- certificates/forms.py
- certificates/tests/test_forms.py
- pii-ner-exclude.txt
User testing revealed a bug where auto-generation of sid failed because some certificates have a non-numeric sid (e.g. "A01") where our logic expected only integers.
This PR adds an sid field to the form ui and checks that this sid isn't already in use. When a user doesn't input an sid (which we think will be most of the time) we autogenerate the sid, ignoring any non-numeric sids.
> TP2000 242 Build and deploy the create certificates design (pt.2)

- importer/management/commands/import_taric.py
- importer/taric.py
Filtering for only commodity codes wasn't happening everywhere making import_taric -c misbehave.
> Fix commodity import from import_taric commandline.

- data_patches/TP2000_338_set_chunks_status.py
Two imports were created with associated Celery tasks, and import set to `RUNNING`. Those tasks went unserviced before a queue purge, leaving the imports in limbo.
This PR provides a run-once script to transition the stalled tasks to `ERRORED` preparing for a clean re-import.
> Transition stalled imports to ERRORED.

- manage.py
The full warning looks like this:
```
manage.py:28: UserWarning: Not reading .env - it doesn't exist.
dotenv.read_dotenv()
```
This is useful on the first occasion a developer sets up Tamato and has forgotten to create a `.env` file (staging and production servers take their env vars from the OS environment). It clutters the command-line and pollutes our logs the rest of the time.
Ignore the warning via warnings filtering.
> Ignore 'not reading .env' warning.

- exporter/sqlite/__init__.py
- settings/common.py
Attempts to include models in the checks app is causing a check constraint violation. `checks` model instances shouldn't be included in the Sqlite dump since it isn't part of the public data set and they can reference transactions that are not in a published state.
Provide a new settings list attribute, `SQLITE_EXCLUDED_APPS`, that makes provision for excluding domain apps and models from the Sqlite export. Include the `checks` app in this new list attribute.
> Exclude checks app models from sqlite dump.

- common/serializers.py
- exporter/management/commands/dump_transactions.py
- exporter/serializers.py
- exporter/tests/test_util.py
- exporter/util.py
- pii-ner-exclude.txt
Output how long it takes to serialize envelopes.
- Add option to disable envelope splitting by size.
- Add option to specify the maximum envelope size.
- Add option to use the next available envelope id (not super useful yet as we don't use envelope upload)
<pre><font color="#5FD700">❯</font> <font color="#00AA00">python</font> <u style="text-decoration-style:single">manage.py</u> dump_transactions 000313 313 --disable-split-by-size
DIT000313.xml ✅  XML valid.  98 transactions, serialized in 17.21 seconds using 277202 bytes.
</pre>
> dump_workbaskets:  add options to disable splitting, and set max size.   add benchmarking.   fix auto-envelope-id.

- measures/business_rules.py
- measures/tests/test_business_rules.py
The ActionRequiresDuty rule currently sees an applicable duty of 0% as equivalent to a Null duty_amount. This has led to the rule firing on workbasket 332 (TOPS 536 New Exporter Review China). 
Update the rule to look for non Null values and add a test for this scenario
> ActionRequiresDuty business rule doesn't handle 0% duty

- common/models/transactions.py
- common/tests/test_transactions.py
- pii-ner-exclude.txt
Optimise apply_transaction_order and rename to move_to_end_of_partiton:
- Make it use bulk_update to massively reduce query count
- Make this a generalised "move transactions to end of any partition".
- Make it take a partition, instead of partition scheme, since at this point the partition is frozen.
In future this may allow us to remove the hack of using negative "pre-emptive" transactions.
Optimise preorder_negative_transactions by using bulk_update.
(Slightly) future proof  Transaction.approved by instead of checking != DRAFT, checking ! partition <= REVISION
Update tests for apply_transaction_order to work with move_to_end_of_partiton and work with partitions not partition schemes.
These fixes were extracted from the "archived transactions" PR - this are all the optimisations and …
> Optimisations around moving transactions.

- common/jinja2/common/my-workbasket.jinja
- common/static/common/scss/_components.scss
- common/static/common/scss/_text.scss
- common/static/common/scss/application.scss
- common/tests/factories.py
- common/tests/test_views.py
- common/views.py
- pii-ner-exclude.txt
- workbaskets/jinja2/includes/workbaskets/edit-workbasket-list.jinja
- workbaskets/jinja2/workbaskets/select-workbasket.jinja
- workbaskets/urls.py
- workbaskets/views/ui.py
* Implementing new design
* Reuses the workbasket list page and makes a few modifications according to the new design
* Querystring used to change current workbasket when they navigate to the new homepage from the workbasket list
* Querystring used to alter breadcrumbs on the homepage to reflect where the user came from
* Links aren't displayed for published workbaskets because workbaskets with this status can't be set as the current workbasket
> TP2000-366 Edit workbaskets list page

- measures/patterns.py
- measures/tests/test_views.py
- measures/views.py
TP2000-371 Editing a measure changes existing condition sids
Currently when a measure with existing conditions is updated its conditions are also updated and their sids changed, which looks strange because we should never be changing the SID and causes a business rule violation on CDS because conditions with these SIDs have never been created.
We shouldn't update a condition in the first place, if the data hasn't been changed, but, due to a bug with duties, the form will always see changed data. We should create a separate ticket to fix that logic once the duties bug is resolved and get this fix for the changing sids in in the meantime.
- Passes in the existing SID to the create_condition_and_components method on MeasureCreationPattern.
- Updates test to check SID and update_type
- Adds …
> TP2000-371 Editing a measure changes existing condition sids

- commodities/jinja2/commodities/import-success.jinja
- commodities/jinja2/commodities/import.jinja
- common/jinja2/common/confirm_create.jinja
- common/jinja2/common/confirm_create_description.jinja
- common/jinja2/common/confirm_update.jinja
- common/jinja2/common/confirm_update_description.jinja
- common/jinja2/common/create_description.jinja
- common/jinja2/common/delete.jinja
- common/jinja2/common/edit.jinja
- common/jinja2/common/edit_description.jinja
- common/jinja2/common/my-workbasket.jinja
- common/jinja2/layouts/confirm.jinja
- common/jinja2/layouts/detail.jinja
- common/jinja2/layouts/list.jinja
- common/jinja2/layouts/list_vertical.jinja
- common/views.py
- footnotes/jinja2/footnotes/confirm_update_description.jinja
- footnotes/jinja2/footnotes/edit_description.jinja
- geo_areas/jinja2/geo_areas/detail.jinja
- importer/jinja2/importer/create.jinja
- measures/jinja2/measures/confirm-create-multiple.jinja
- measures/jinja2/measures/create-start.jinja
- measures/jinja2/measures/edit.jinja
- regulations/jinja2/regulations/edit.jinja
- workbaskets/jinja2/workbaskets/delete_changes.jinja
- workbaskets/jinja2/workbaskets/delete_changes_confirm.jinja
- workbaskets/jinja2/workbaskets/detail.jinja
- workbaskets/jinja2/workbaskets/select-workbasket.jinja
In my last PR, I incorrectly assumed that all the links pointing to home would want to go to the dashboard still. This was dumb as we now have a workbasket page that builds upon the dashboard, so it should have linked there. This PR undoes all of the index -> dashboard link changing I did but also updates the confirm template to redirect you back to `my-workbasket`.
- All links that originally pointed to index, that were changed over in the previous PR to point to dashboard, have now been reverted to index again and take you to the new landing page (new index). 
- Both the "Go to your tariff changes", and "Return to main menu" buttons / link on the Confirmation page after creating something, now take you back to the `my-workbasket` page. (This is an accessibility issue but not for long at …
> Tp2000 375 workbasket link update

- measures/jinja2/includes/measures/tabs/conditions.jinja
- measures/jinja2/includes/measures/tabs/footnotes.jinja
- measures/jinja2/measures/detail.jinja
- measures/tests/test_views.py
- measures/views.py
* Users need to be able to see measures' associated footnotes on the measue detail page
* Adds an extra tab to display a measure's footnotes
> TP2000-377 Add footnotes tab to measure detail page

- measures/jinja2/includes/measures/tabs/core_data.jinja
- measures/tests/test_views.py
* Users could only see the quota order number SID which wasn't helpful
* Displays the measure's order_number instead of order_number.sid on the details page
> TP2000-179 Add quota order number to measure detail page

- common/forms.py
- common/tests/test_views.py
- common/views.py
- workbaskets/forms.py
- workbaskets/jinja2/workbaskets/create.jinja
- workbaskets/tests/test_forms.py
- workbaskets/tests/test_views.py
- workbaskets/urls.py
- workbaskets/views/ui.py
This PR adds the following so that TM's can make their own workbaskets: 
- A new option to the landing page to create a new workbasket.
- A create a new workbasket form, that takes a title, and a description - both mandatory. 
- A redirect from the create form that takes the user to the my workbasket page for the workbasket they just made.
- Requires migrations? - no 
> Tp2000 374 create workbasket

- common/models/trackedmodel.py
- common/tests/test_models.py
Copy already supports the scenarios outlined in [this PR](https://github.com/uktrade/tamato/pull/458), including the ability to pass in multiple unsaved objects. This PR adds one more: the ability to pass in multiple _saved_ objects. This will be useful for steel quotas work, where we have to copy measures with slightly different sets of exclusions, depending on the validity period. (The new test is based on such a scenario).
- Adds subrecord logic to differentiate between saved and unsaved logic. 
- Fixes bug in unsaved logic, where copies were pointing at the old object, not the new copied one
- Adds test and fixes test for above bug
> Make copy accept saved related models

- geo_areas/models.py
- geo_areas/tests/test_models.py
- measures/forms.py
- measures/tests/conftest.py
- measures/tests/test_forms.py
- measures/views.py
- requirements-dev.txt
At present newly created memberships don't display in the memberships tab when viewing a geo area. Separately we also don't see new geo areas in dropdown menus on the measure create or edit forms.
- Have `get_current_memberships` use the `current` queryset method
- Pass in current transaction to geo area forms, so that latest editing workbasket changes are visible to the user
> TP2000-386 get_current_memberships uses latest_approved instead of approved_up_to_transaction

- geo_areas/tests/test_util.py
- geo_areas/util.py
- geo_areas/views.py
Reverts uktrade/tamato#617
Lots of countries are missing from search (e.g. Erga Omnes 1011, North Macedonia) and the detail view returns a multiple objects returned for countries with multiple descriptions. I think filtering by transaction order works better (my bad for suggesting to change that), but, looking at it again, I'm not sure we want to be changing the main queryset in GeoAreaMixin and using `objects.all()`, as I think this is causing the multiple objects returned errored. Needs a bit more thought and probably we should separate out the filtering logic and annotation logic from with_latest_description_string.
> Revert "TP2000-225 Fix geo area search"

- quotas/business_rules.py
- quotas/tests/test_business_rules.py
It's not currently possible to update a QuotaAssociation and change its sub_quota_relation_type without QA6 seeing the old version as clashing with the new one.
Updates QA6 to use `approved_up_to_transaction` and adds test for bug scenario
> TP2000-434 QA6 should use approved_up_to_transaction

- measures/forms.py
- measures/tests/test_forms.py
We can't currently create measures with a geo area of type GROUP without a 500 on measure create summary page
Ensures that `MeasureGeographicalAreaForm.clean` always returns a list.
This is a quick fix because it's blocking urgent work, but we should probs refactor more of our form tests to use `parametrize` and add more assertions about what's returned in cleaned data. Ticket [here](https://uktrade.atlassian.net/browse/TP2000-438)
> TP2000-437 500 error on measure create summary page

- commodities/jinja2/commodities/import-success.jinja
- common/jinja2/includes/common/main-menu-link.jinja
- common/jinja2/layouts/confirm.jinja
- measures/jinja2/measures/confirm-create-multiple.jinja
- workbaskets/jinja2/workbaskets/delete_changes_confirm.jinja
- workbaskets/tests/test_views.py
* "index" url is gone. We use the workbasket main menu instead
* Replaces any remaining uses of "index" in templates and makes the main menu link into a reusable template
> TP2000-436: Fix use of index url that no longer exists

- additional_codes/forms.py
- certificates/forms.py
- commodities/forms.py
- common/forms.py
- footnotes/forms.py
- footnotes/jinja2/footnotes/edit_description.jinja
- measures/forms.py
- measures/jinja2/measures/create-review.jinja
- measures/jinja2/measures/edit.jinja
- regulations/forms.py
- workbaskets/forms.py
Double clicking a form submit button leads to transactions being created with duplicate composite_key values and causes a 500 integrity error.
Add the govuk prevent double click attribute across submit buttons
> TP2000-446 Implement a guard against double form submits

- quotas/business_rules.py
- quotas/models.py
- quotas/tests/test_business_rules.py
It shouldn't be possible to create an association where the same definition is both the parent and the child.
It shouldn't be possible to create overlapping definitions for the same quota order number.
Therefore, we should formalise the above as business rules.
Adds two new rules, tests, and updates model business rules lists
> TP2000-432 QuotaAssociation objects have been created with the same main and sub quota

- measures/forms.py
- measures/jinja2/includes/measures/tabs/core_data.jinja
- measures/tests/test_views.py
When trying to edit a measure and exclude one area group from another (e.g. ERGA OMNES), we would expect a MeasureExcludedGeographicalArea object to be created for each area in the excluded group. Instead only the first country is getting an exclusion created for it.
Unpack iterator returned by `create_measure_excluded_geographical_areas`. (I thought `next()` was meant to do this and don't know why it doesn't. Can anyone explain?)
> TP2000-410 editing measure exclusions only excludes first country of group

- measures/tests/test_views.py
`measures.tests.test_views.test_measure_update_create_conditions()` assumed an ordering of `MeasureConditionComponent`s in a QuerySet. However, the application of `TrackedModelQuerySet.approved_up_to_transaction()` to a QuerySet prevents the correct application of `Model.Meta.ordering`.
This PR explicitly applies an order on the `MeasureConditionComponent` QuerySet so that the `MeasureConditionComponent.condition.sid` and `MeasureConditionComponent.duty_expression.sid` attributes values can be validated correctly.
> TP2000-452  Incorrect ordering on components queryset

- commodities/assets/commodities_envelope.xsd
- commodities/assets/commodities_taric3.xsd
- commodities/forms.py
- commodities/tests/test_files/invalid.xml
- commodities/tests/test_files/invalid_id.xml
- commodities/tests/test_files/valid.xml
- commodities/tests/test_forms.py
- common/assets/envelope.xsd
- importer/views.py
- pii-ner-exclude.txt
- settings/common.py
Currently we have to manually update the envelope id on files sent to us by the EU before they can be imported
Updates envelope xml schema to expect a 5 digit id.
> TP2000-311 Envelope schema expects a six-digit number to be present, the TARIC file only contains five

- certificates/tests/test_views.py
- certificates/views.py
We're getting MultipleObjectsReturned errors when trying to create a description for a certificate with more than one version.
Updates `CertificateDescriptionCreate.get_initial` to use `objects.current()`
Original sentry error https://sentry.ci.uktrade.digital/organizations/dit/issues/64174/?environment=production&project=200&referrer=alert_email
> TP2000-450 Certificate.MultipleObjectsReturned error on certificate description create

- certificates/tests/test_forms.py
- certificates/tests/test_views.py
- certificates/views.py
Certificate description create view is still buggy (`get_context_data` should use current queryset)
Add proper create view test and update `get_context_data` to use `current`
> TP2000-450 certificate multiple objects returned error on certificate description create (pt. 2)

- measures/forms.py
- measures/patterns.py
- measures/tests/test_util.py
- measures/util.py
`MeasureComponent` and `MeasureConditionComponent` objects should be associated with their parent object's transaction. The component management API, `diff_components()`, currently allows this relationship to be bypassed. 
Make the `diff_components()`'s `transaction` parameter mandatory.
Comment on a previous PR that set up this refactor: https://github.com/uktrade/tamato/pull/638#pullrequestreview-1060043241
> Require the transaction param on diff_components()

- quotas/business_rules.py
- quotas/models.py
- quotas/tests/test_business_rules.py
HMRC have flagged that several recent steel quota definitions have been created with `volume` and `initial_volume` values that do not match. Doug and Tom's investigation has also revealed past instances of this, which shouldn't have been allowed either.
Adds a rule preventing the creation of a `QuotaDefinition` with different `volume` and `initial_volume` values, unless that definition is used as the `main_quota` in a `QuotaAssociation`.
This rule implicitly enforces that, in order for a quota definition to be created with different `volume` and `initial_volume` values, an association will have to be created in the same or earlier transaction with that definition as its `main_quota`
> TP2000-449 add volumes business rule

- workbaskets/tests/test_views.py
- workbaskets/urls.py
- workbaskets/views/ui.py
The WorkBasketList view was removed as part of multi workbasket work. `SelectWorkbasketView` now lives at the `workbaskets` url, but this doesn't provide a view of PUBLISHED or ARCHIVED baskets. This is useful for TMs (and devs) when comparing the changes in a basket to what's visible in TAP.
Restores `WorkBasketList` view, as added by @paulpepper-trade in [this PR](https://github.com/uktrade/tamato/pull/549) and adds a couple of view tests. The jinja is already there.
> TP2000-278 Allow for workbaskets in the TAP page to be selected for inspection

- workbaskets/jinja2/workbaskets/edit-workbasket.jinja
- workbaskets/jinja2/workbaskets/review-workbasket.jinja
* Fixing bug from previous PR
* Uses govukBreadcrumbs on this page rather than breadcrumbs component to avoid duplicate links
> TP2000-462: Fix double home link on workbasket page

- importer/forms.py
- importer/tests/test_forms.py
We can't currently import envelopes
Add missing `self` arg to `process_file` and `form.save()` test
> TP2000-486 Failure "... multiple values for argument 'record_group'" when importing envelope created by dump_transactions

- commodities/jinja2/commodities/import-success.jinja
- commodities/tests/test_views.py
* 500 on import/success page due to incorrect url in template
* Replace with correct url name in template
> TP2000-491: Fix incorrect url name in breadcrumbs

- commodities/models/orm.py
* Users should be able to click through to see a new commodity code in their workbasket
* Modifies the get_url method on commodity models to link to the commodity detail page
> TP2000-506: Add urls for commodities and related objects

- measures/forms.py
- measures/jinja2/measures/create-review.jinja
- measures/tests/conftest.py
- measures/tests/test_forms.py
- measures/tests/test_views.py
- measures/views.py
- pii-ner-exclude.txt
In preparation for the create measure wizard's steps / forms being used to edit measures, the regulation Id and quota order number fields must be separated out from the details step into their own step. 
This PR puts regulation Id and quota order number in their own forms and steps within the create measure wizard, adding related form and view unit tests.
> TP2000-472 and TP2000-473 separate regulation + quota into create measure steps

- workbaskets/jinja2/workbaskets/edit-workbasket.jinja
Since pages have been moved around and new prompts added to the workbasket add/edit page (it's now under a titled tab), the current subheading differs to other tabs and is confusing to screen readers. The subheading should therefore be removed.
Removed subheading from the workbasket add/edit page.
> Remove subheading from workbasket add/edit items page.

- workbaskets/jinja2/workbaskets/violation_detail.jinja
* We want to show the SID not the ID for the object the rule violation relates to
* Displays the SID if available, the ID if not
> TP2000-510: Display object SID on violation detail page

- measures/forms.py
- measures/tests/test_forms.py
It shouldn't be possible to create measures with deleted certificates or certificates currently in a different, EDITING workbasket.
Updates `MeasureConditionsFormMixin.required_certificate` to use current queryset.
> TP2000-534 CertificateDoesNotExist error on measure/create/conditions step

- exporter/management/commands/dump_transactions.py
- exporter/tests/test_exporter_commands.py
- pii-ner-exclude.txt
- workbaskets/validators.py
Normally, it's expected that `dump_transactions` is only called on workbaskets that have had a complete and successful business rule check - i.e. those that are error-free. However, it's currently possible to accidentally export an unchecked workbasket leading to subsequence processing problems when using exported envelope. 
This PR restricts dumping workbaskets to those that are known to have been checked. A flag, `--force-unchecked-rules`, has been added to allow explicit override of this behaviour for more uncommon situations. 
> TP2000-537 Restrict dump transactions to checked workbaskets

- workbaskets/management/commands/me32_clashes.py
TP2000-538 Multi-version support for me32_clashes
The `me32_clashes` Django management command (a command-line tool) will only find clashes for the last, most recent version of a measure.
This PR adds support for checking for ME32 clashes against all versions of a measure in a workbasket by adding a `--workbasket ` flag, without which the old behaviour is preserved.
> TP2000-538 Multi-version support for me32_clashes

- commodities/business_rules.py
- commodities/models/dc.py
- commodities/tests/test_business_rules.py
- common/tests/util.py
- common/util.py
- pii-ner-exclude.txt
NIG2 and the wording surrounding it is a bit of a grey area, we have however observed data coming from the EU that gave us insights that the interpretation we have differs from the interpretation the EU has. This is causing issues when we are getting data from the EU. 
The rule states: "The validity period of the goods nomenclature must be within the validity period of the product line above in the hierarchy."
NIG2 will fail if the "current" parent does not encapsulate the valid between date period, so if a child good nomenclature is valid between 1/1/20202 and 1/2/2022 and the parent is valid between 1/1/2022 and 15/1/2022 (even if there is another parent that would be next in the chain with a valid period of 1/1/20202 and 1/2/2022 or more) the validation will fail (as of today) note : …
> Tops 645 nig2 parent lookup update

- workbaskets/jinja2/workbaskets/delete_changes_confirm.jinja
Next Actions at the bottom of the confirmation page (displayed after removing items from a workbasket) isn't complete or formatted correctly.
Make next actions consistent with other parts of the application.
> TP2000-574 correctly format workbasket removal confirmation page next actions

- common/business_rules.py
- measures/business_rules.py
- measures/tests/test_business_rules.py
- quotas/business_rules.py
- quotas/models.py
- quotas/tests/test_business_rules.py
updated ME6 business rule to prevent nulls
ON4 was missing and has caused issues historically
ME6 (based on taric spec) A measure must be linked to a good id, but we have 300k of unlinked measures. This is an attempt to stop this happening going forward, then we can tidy up the historic issues
Added ON4 business rule
updated ME6 business rule to prevent nulls
> Added ON4 business rule and updated ME6

- common/jinja2/common/app_info.jinja
- common/tests/test_views.py
- common/urls.py
- common/views.py
- pii-ner-exclude.txt
Business rule checks are currently only visible from the workbasket running a specific check - whether in the main UI or the Django admin site. Users currently get the information via an unreliable out-of-band means - usually asking in a Teams channel if anyone is running rules checks.
This PR provides an application-wide view of which workbaskets currently have actively executing business rules checks. Information present on the view:
- WorkBasket ID.
- Rule check start time.
- Celery task ID (used to run the check - useful for debug and investigation).
The view is available on the system-wide route path, `/app-info`, and is restricted to logged in users only.
No checks running:
One active check executing:
> TP2000-576 App info page showing running checks

- commodities/models/orm.py
Envelope 220243 passed business rules but failed at CDS with NIG11
Adds NIG11 to GoodsNomenclature.business_rules (currently only lives on GoodsNomenclatureIndent.indirect_business_rules)
> TP2000-582 NIG11 not firing when it should

- workbaskets/models.py
- workbaskets/tests/test_models.py
We should start using ERRORED state to make it clear that a workbasket approved by tariff managers has been rejected for some reason by CDS. To do this, we need a way of restoring a workbasket to EDITING state, so that fixes can be made.
Adds a `restore` transition method to `WorkBasket` and unit tests existing transition methods
> TP2000-570 ERRORED shouldn't be a final state for WorkBasket

- common/tests/test_business_rules.py
- conftest.py
- measures/business_rules.py
- measures/tests/test_business_rules.py
- pii-ner-exclude.txt
ME119 is now giving false positives
Adds `skip_when_deleted` decorator to ME119 and adds some tests for that decorator and `skip_when_not_deleted`
The tests are not an ideal solution, but I spent quite a bit of time trying different things without success, so created this ticket to refactor at some point https://uktrade.atlassian.net/browse/TP2000-591
> TP2000-583 me40 gives false positives (pt. 2)

- package-lock.json
- quotas/business_rules.py
- quotas/tests/test_business_rules.py
* OverlappingQuotaDefinition correctly filtered deleted models, but did not check latest version of model was current.
* No test to verify if a Quota definition previously deleted would pass through the rule check 
* A production update example caused this issue to prevent an update
* Updates the OverlappingQuotaDefinition business rule to check only current version of model
- Requires migrations? NO
- Requires dependency updates? NO
See: This change will unblock this ticket : https://uktrade.atlassian.net/browse/TOPS-831
See : Original request that identified the issue : https://uktrade.atlassian.net/browse/TOPS-681
> Tops 681 update to OverlappingQuotaDefinition Rule

- .pre-commit-config.yaml
- additional_codes/tests/test_views.py
- additional_codes/urls.py
- certificates/tests/test_views.py
- certificates/urls.py
- common/tests/util.py
- footnotes/tests/test_views.py
- footnotes/urls.py
- geo_areas/tests/test_views.py
- measures/tests/test_views.py
- quotas/tests/test_views.py
- quotas/urls.py
- regulations/tests/test_views.py
- workbaskets/tests/test_views.py
Previously the ReadOnlyModelViewSet views did not have any units tests, this story ensures that this coverage has been addressed
Unit testing API view sets
> TP2000-608 Unit tests for api list views

- .pre-commit-config.yaml
- Procfile
- additional_codes/tests/test_views.py
- additional_codes/urls.py
- certificates/tests/test_views.py
- certificates/urls.py
- common/tests/util.py
- footnotes/tests/test_views.py
- footnotes/urls.py
- geo_areas/tests/test_views.py
- measures/tests/test_views.py
- package-lock.json
- quotas/business_rules.py
- quotas/tests/test_business_rules.py
- quotas/tests/test_views.py
- quotas/urls.py
- regulations/tests/test_views.py
- workbaskets/tests/test_views.py
The rule states : The quota order number origin cannot be deleted if it is used in a measure.
* Rule would reject removal if any measures existed on the order, without checking specific measures for the geographical area
* Updated rule, added test
See: https://uktrade.atlassian.net/browse/TOPS-824
> fix for ON12 not allowing origin to be removed, even if no measures are attached

- quotas/business_rules.py
* ON12 violation error text was missing a space before a new sentence
* Fix missing space
> minor change to ON12 validation error message text.

- checks/tests/test_querysets.py
- quotas/business_rules.py
checks/tests/test_querysets.py::test_current_queryset_returns_correct_results[check of approved transaction with greater approved check transaction] will intermittently fail, roughly 50% of the time. 
* The test would fail 50% of the time (and has presumably for all of its existence) since the parameterised test would set up 2 transactions with the same order number. Incrementing the order number of the second created transaction in the test fixes the issue and the increate in coverage indicates here is additional code that is now being covered that was not before. 
Requires migrations? no
Requires dependency updates? no
> change test so it passes all the time

- measures/business_rules.py
* I can only imagine how frustrating it is for a TM to have to ask a DE / Dev to find out which measure is overlapping when faced with an ME32 message but no other information. 
* All errors should give enough information for a TM to process and update the workbasket in order to resolve a rule violation. This is the first attempt to expose key information that will make TMs work more autonomous 
* Really simple change, adding the measure SIDs to the end of the violation message
* Example : There may be no overlap in time with other measure occurrences with a goods code in the same nomenclature hierarchy which references the same measure type, geo area, order number, additional code and reduction indicator. Clash with Measure SID 20198035. 
- Requires dependency …
> update ME32 rule violation message to include violating measures

- workbaskets/forms.py
- workbaskets/tests/test_forms.py
- workbaskets/tests/test_views.py
- workbaskets/validators.py
Currently the 'Tops/Jira number' field on the create a workbasket page does not provide the user with guidance on where to find this number or in what format it must be inputted. The field also does not validate the input, allowing alphanumeric characters as well as special characters.
Adds help text to the field, explaining where this number can be found and providing other important context.
Adds a numerical-only input validator on the field to prevent invalid input (i.e alphabet and special characters).
Updates workbasket create form tests to reflect addition of numerical-only input validator.
> TP2000-621 Content improvement for the create a workbasket page

- measures/jinja2/includes/measures/list.jinja
- measures/jinja2/measures/delete-multiple-measures.jinja
- measures/tests/test_views.py
- measures/urls.py
- measures/views.py
- pii-ner-exclude.txt
- workbaskets/tests/test_forms.py
In order for TM's to delete multiple measures in one go, I have added the functionality and templates to allow TM's to select the measures they wish to delete from the list view, confirm that they want to delete these measures and delete them.
- Amend the List page to show checkboxes next to each item, make them selectable, and show their start and end dates. 
- Create a MultipleMeasuresDelete view which is responsible for showing the measures the users have chosen on a review page, and deleting those measures. 
- Added templates to accommodate the designs. 
- Added tests for the SelectableObjectsForm as it was missing them.
Added checkboxes to each item, along with start and end dates for the measures on the list page. 
Added Delete multiple measures "review" page, where users can see …
> TP2000-508 multiple measures delete

- commodities/tests/test_migrations.py
- conftest.py
- measures/tests/test_migrations.py
- reports/views.py
Updates to conftest fixture setup_content_types to be a full fixture. Also update to only load available apps and not fail
previous work I created setup_content_types but issues have occurred since relating to this work, so have updated the fixture to be an actual fixture and added a check to verify apps are available before loading them. 
improvements to fixture setup_content_types
See: [[Description](https://example.com/...)](https://uktrade.atlassian.net/browse/TP2000-660)
> update setup content types to be full fixture, and only load available apps

- common/jinja2/common/403.jinja
- common/tests/test_views.py
- common/views.py
- pii-secret-exclude.txt
- urls.py
When a user attempts to access a part of the service to which they don't have the required access rights, a generic 403 error response is displayed without guidance on how to rectify the problem or raise an issue. 
Adds custom 403 error page with a link to a form where the user can request access or raise an issue. 
Before:
After:
> TP2000-654 Create 403 error page

- common/jinja2/common/500.jinja
- common/tests/test_views.py
- common/views.py
- pii-secret-exclude.txt
- urls.py
When a user encounters an unhandled server error, a generic server error (500) response is displayed without guidance on how to raise an issue.
Adds custom server error 500 page with a link to a form where the user can raise an issue.
Maps error 500 and error 403 views to urls for viewing in debug mode only (thought it might be a convenient way to view the error templates but can remove)
Before:
After:
> TP2000-655 Create 500 error page

- quotas/jinja2/includes/quotas/actions.jinja
- quotas/jinja2/includes/quotas/tabs/definition_details.jinja
- quotas/jinja2/includes/quotas/tabs/measures.jinja
- quotas/jinja2/quotas/detail.jinja
- quotas/tests/test_views.py
- quotas/views.py
* Users need to be able to find measures related to a quota order number
* Adds a measures tab to the quota order number detail page that shows currently active measures
* Adds a link to the find and edit measures page that filters by the quota order number
> TP2000-648 Add measures tab

- quotas/jinja2/includes/quotas/tabs/core_data.jinja
At the bottom of the Quota number details tab is the Geographical Area Exclusions field. This field ought to be moved to underneath the related Geographical Area field to make the look of the tab more consistent and make the exclusions easier to read.
Repositions Geographical Area Exclusions underneath Geographical Area in the Quota number details tab
After:
> TP2000-664 Move Geographical Exclusions data in the Quota Order Number details tab

- common/jinja2/common/confirm_create.jinja
- common/jinja2/common/confirm_create_description.jinja
- common/jinja2/common/confirm_update.jinja
- common/jinja2/common/confirm_update_description.jinja
- common/jinja2/components/duty_help.jinja
- common/jinja2/components/measure_condition_action_code/template.jinja
- common/jinja2/components/measure_condition_code/template.jinja
- common/jinja2/includes/common/main-menu-link.jinja
- common/jinja2/layouts/confirm.jinja
- measures/forms.py
- measures/jinja2/measures/confirm-create-multiple.jinja
- measures/jinja2/measures/create-start.jinja
- measures/jinja2/measures/create-wizard-step.jinja
- measures/views.py
- workbaskets/jinja2/workbaskets/delete_changes_confirm.jinja
The current 'Create measure' user journey requires content changes to better explain and reflect actions taken during creation.
- Updates field help text across the forms to describe actual actions to take
- Updates first page content and adds back button
- Adds details component which includes a link to “find and edit quotas" to Quotas form
- Replaces “Help with Geography” dropdown on geo form with field help text
- Adds ‘(optional)’ to all sections that are optional, removing need for unnecessary help text 
- Changes confirmation screen so the buttons and text more accurately reflect where they lead and what has happened in creation
Examples:
> TP2000-669 Changes to 'Create measure' Journey

- common/tests/test_views.py
- common/views.py
Added Total and Active Quota counts to the dashboard so this data can be viewable by tariff managers
> Added active and total quotas to dashboard

- commodities/jinja2/includes/commodities/tabs/core_data.jinja
- commodities/views.py
- Commodities details view incorrectly displays commodity origin data as parent commodity data. 
- Commodities details view displays outdated indent values (TP2000-528).
- Data fields contain spelling errors.
- Fixes parent commodity data.
- Shows only current indent value.
- Corrects spelling errors.
Before:
After:
> TP2000-665 Corrects data fields on commodities details view

- common/jinja2/common/dashboard_overview.jinja
- common/tests/test_views.py
- common/views.py
Dashboard overview is missing total and active counts for certificates.
Adds counts for certificates
> Add certificates counts

- common/forms.py
- common/jinja2/common/dashboard_overview.jinja
- common/tests/test_views.py
- common/urls.py
- common/views.py
the overview dashboard can only be accessed via the url
a link on the home page to the overview dashboard 
See: [Trello Ticket](https://trello.com/c/sHZ2HMgi/18-link-to-overview-page)
> Firebreak   Data overview link

- workbaskets/jinja2/workbaskets/macros/detail_tabs.jinja
- workbaskets/tests/test_views.py
There occurs a 500-series error owing to missing version control templates on WorkBasket changes view.
Amends incorrect version control template path to use common template
Adds test for WorkBasket Changes view
> TP2000-675 Fix version control tab template paths

- quotas/jinja2/includes/quotas/tabs/suspension_periods.jinja
- quotas/jinja2/quotas/detail.jinja
- quotas/tests/test_views.py
- quotas/views.py
- Users are unable to view details of any suspension periods in place for a quota.
- Adds suspension periods tab, showing active or upcoming suspension period.
- Adds unit test for suspension periods tab.
Example:
> TP2000-647  Add suspension periods tab to Quota detail view

- common/jinja2/components/sort_by.jinja
- quotas/jinja2/includes/quotas/tabs/measures.jinja
- quotas/views.py
- Tariff Managers have indicated that the ability to sort by commodity code would help them to compare the list of commodity codes attached against other data easier.
- Make commodity code list sortable (in ascending or descending order) by user.
Before:
After:
> TP2000-673 Sort by commodity code in Quota measures tab

- common/tariffs_api.py
- common/tests/factories.py
- common/tests/test_models.py
- common/tests/test_tariffs_api.py
- conftest.py
- quotas/jinja2/includes/quotas/actions.jinja
- quotas/jinja2/includes/quotas/tabs/definition_details.jinja
- quotas/jinja2/quotas/definitions.jinja
- quotas/tests/test_views.py
- quotas/views.py
- requirements.txt
* Some data on quotas is not held in TAP so we get this data from the [Trade Tariff API](https://api.trade-tariff.service.gov.uk/reference.html#trade-tariff-public-api-v2)
* Adds status and balance data for quotas and definition periods
* If the API is unreachable we omit this data from the page
* Adds a link to the quota on the Trade Tariff API in the sidebar
* Adds support for testing async functions with pytest
- Requires migrations? ❌ 
- Requires dependency updates? ✅
> TP2000-602: Get Trade Tariff API quota data

- measures/forms.py
- measures/jinja2/includes/measures/list.jinja
- measures/jinja2/measures/edit-multiple-measures-enddates.jinja
- measures/jinja2/measures/edit.jinja
- measures/tests/test_views.py
- measures/urls.py
- measures/views.py
Due to the create measures form having some quirks, it's not a bright idea to make a multiple measures edit form based on it. We've decided as a team that it needs some extra thought and planning, along with some time spent polishing up the create form. As an interim, we've got this 'MVP' version allowing TM's to edit the end dates of multiple measures cause that would be a lifesaver as a minimum. 
This is only an interim change, that's been implemented until the polished article can come out. This PR adds a button to the MeasureList page, next to the delete button to edit the end dates. This takes you to a new page, similar to the multiple delete review page, except it has an end date form on it. This form has no visible validation on it, as that's coming later in a separate ticket as we …
> TP2000-672 Add multiple measures edit end date form

- quotas/views.py
The measures queryset used in the measures tab on a quota detail view returns duplicated data for some quotas.
Adds latest_approved() to the query to return only the current version of an object and not its historical updates.
Before:
After:
> TP2000-693 Fix duplication in Quota measures tab

- common/static/common/scss/_layout.scss
- quotas/jinja2/includes/quotas/tabs/sub_quotas.jinja
- quotas/jinja2/quotas/detail.jinja
- quotas/tests/test_views.py
- quotas/views.py
Users are unable to view details of any sub-quota data for a given quota.
Add sub-quotas tab to Quota detail view, showing details of any active sub-quotas.
> TP2000-645 Add sub-quotas tab to Quota detail view

- notifications/tests/test_tasks.py
- workbaskets/tests/test_views.py
- workbaskets/views/ui.py
…or editing.
Although the workbaskets list view shows those in `EDITING` and `ERRORED` states, it isn't possible to select an errored workbasket for editing. Although the browser is redirected to a workbasket summary page when selecting a workbasket that is in `ERRORED` state, it isn't for the selected workbasket - because only workbaskets in `EDITING` state may be edited. This is confusing behaviour for the users.
This PR transitions a workbasket's status to `EDITING` if it was `ERRORED` when selected. This is a more likely user intention and has much less chance of being a surprise to the user than being dropped into a different editable workbasket. Includes a unit test to ensure the status transitions as expected.
> TP2000-713 Transition to EDITING if required

- publishing/models.py
Envelopes were being created by `pop_top()` for a packaged workbasket at position 1 before the top packaged workbasket's envelope had been processed by HMRC. This was due to `pop_top()` being called from within the `begin_processing` transition when the top instance's `processing_state` had not yet settled to `CURRENTLY_PROCESSING`.
Envelopes were not being generated for next queued instances upon completing processing of the top instance (i.e. upon `processing_succeeded` and `processing_failed`)
Move the call to `pop_top' into a decorator that wraps the `begin_processing` transition, allowing `processing_state` to arrive at its final state - it then calls `pop_top`.
Add decorator to start generating the next envelope upon `processing_succeeded` and `processing_failed` transitions …
> Correctly start envelope creation.

- publishing/storages.py
- settings/common.py
S3 credentials for envelope and loading report storage must be pulled from VCAP_SERVICES on PaaS.
This PR implements pulling S3 credentials for envelope and loading report storage from VCAP_SERVICES on PaaS.
> Pull S3 creds from VCAP_SERVICES

- settings/common.py
It's preferable to take the application base URL from the preconfigure application environment rather than provide it from a secret store.
Pulls the first valid application URI from the VCAPS_APPLICATION environment variable if one is available.
> Take BASE_SERVICE_URL from VCAP_APPLICATION if available.

- publishing/forms.py
- publishing/jinja2/includes/queue-unpaused.jinja
- publishing/jinja2/includes/warning_help.jinja
- publishing/jinja2/publishing/complete-envelope-processing-confirm.jinja
- publishing/jinja2/publishing/envelope_queue.jinja
- publishing/views.py
Small content amendments could be made to improve users' understanding of actions taken throughout the packaging automation journey. 
Amends the following content:
- 'Add to queue' warning text
- 'Pausing and unpausing' dropdown detail text
- 'How to process an envelope' dropdown detail text
- Accept or reject envelope warning text
- Envelope rejection confirmation text
> TP2000-696 Content amendments packaging automation UI

- workbaskets/views/ui.py
The workbasket list all view is accessible to all user groups. This page should only be viewable to users who have permission to select, edit and create workbaskets.
- Adds `PermissionRequiredMixin` to `WorkBasketList` view
> TP2000-736 Add permission check workbasket finder

- measures/jinja2/includes/measures/list.jinja
- measures/tests/test_views.py
- measures/views.py
Now that users can select measures across multiple pages #809, it would be useful for them to see a running list of their selections.
- Adds a dropdown detail component to show a running list of a user's measure selections
> TP2000-694 Add list of selected measures

- common/jinja2/includes/common/tabs/version_control.jinja
- common/static/common/scss/_layout.scss
- measures/jinja2/includes/measures/tabs/version_control.jinja
- measures/tests/test_views.py
- quotas/jinja2/includes/quotas/tabs/version_control.jinja
- regulations/jinja2/includes/regulations/tabs/version_control.jinja
The version control tab always shows the same activity date for multiple versions
- Uses the latest timestamp for an object's transaction instead of its version group creation date
- Updates unit test
- Fixes tab visual bug
Before:
After:
Linked issue: TP2000-403
> TP2000-756  Fix version control activity dates

- checks/checks.py
- workbaskets/management/commands/override_check.py
- workbaskets/management/commands/override_check_successful.py
- workbaskets/tests/test_commands.py
Very occassionally a measure fails its rule check (TrackedModelCheck) as a result of what appears to be an internal error - i.e. these aren’t business rule check errors. Until the root cause of these failures is found and fixed, they prevent their container workbaskets from being queued, sent to HMRC and published.
Interim data fixes have been applied several times via a Python shell on the Production service. To reduce the chance of mishap when repeating this, and to allow any engineer perform the fix, this PR introduces a new Django management command under the workbaskets application to perform the data fix:
`python manage.py override_check_successful <workbasket-id> <tracked-model-check-id>`
Including workbasket ID reduces the chance of an incorrect `TrackedModelCheck` ID being …
> TP2000-757 Command to override broken check

- measures/forms.py
- measures/tests/test_forms.py
- measures/views.py
The quota order number page in the create measure journey requires small content amendment to make it consistent with the other pages. 
- Amends title (adds optional to title, uses lowercase)
- Removes now redundant sentence in help text
- Extends unit test coverage
Before:
After:
> TP2000-758 Update quota order number page in create measure journey

- common/jinja2.py
- pii-secret-exclude.txt
- requirements-dev-jupyter.txt
- requirements.txt
Dependabot has raised two alerts for the WerkZeug package used by Tamato. The auto-generated PR breaks Tamato's CI checks so it's necessary to make additional manual changes. 
This PR:
Updates the WerkZeug package to a version that resolves the Dependabot alerts.
Resolves clashing requirements dependencies.
Manual testing in a staging environment (Training) didn't uncover any breaking changes to the Tamato.
- Requires dependency updates? Yes
> TP2000-759 Fix werkzeug dependabot alerts

- settings/common.py
Thanks to a Security audit, it was Identified that when creating a username and password the old fashioned way without Staff SSO, the password manager would accept anything as a password. We don't use this functionality much, but it is in practice when staff SSO is not enabled in the project such as spinning up a local host. God knows how the auditors found that though. 
This PR adds some simple settings to have a mandatory 12 character minimum for passwords, and checks the passwords against 20K odd similar passwords, under the recommendations of the pen test. 
- Requires migrations? - nah
- Requires dependency updates? - nope
> TP2000-682 Amend weak password policy

- measures/forms.py
- measures/jinja2/measures/create-formset.jinja
- measures/tests/test_forms.py
The commodity and duties form in the create measure journey is lacking an error message to say that a selection is required if a user tries to continue without selecting a commodity.
- Overrides `non_form_errors()` to provide a more meaningful error message
- Adds unit test
> TP2000-763 Add error message to commodity and duties form

- measures/conditions.py
- measures/constants.py
- measures/jinja2/measures/edit-multiple-start.jinja
- measures/tests/test_views.py
- measures/views.py
* Users need to be able to edit the quota order number on multiple measures
* Adds an extra step to the multiple measures edit wizard to allow editing of quota order number
> TP2000-749: Add quota step to multiple measures edit form

- common/jinja2/layouts/layout.jinja
- workbaskets/jinja2/includes/workbaskets/edit-workbasket-list.jinja
- workbaskets/jinja2/includes/workbaskets/workbasket-list.jinja
* Macros in govuk-frontend mark content assigned to "html" params as safe. If we're not careful this can leave us vulnerable to XSS
* Unless absolutely necessary we should use the "text" param instead of "html" in macros
See: https://github.com/alphagov/govuk-frontend/blob/main/src/govuk/components/table/template.njk#L32
> TP2000-700 Fix XSS vulnerability

- measures/parsers.py
The duty sentence parser doesn't allow users to enter certain valid measurement units (for example "m2").
- Adds EOF flag parser to measurement units without qualifiers
> TP2000-764 Correct duty sentence parser to allow all available measurement units

- measures/filters.py
- measures/forms.py
* Users need to quickly return all the measures for commodity codes under a certain chapter in the search page for multiple editing
* Adds an extra filter field for commodity codes starting with given digits
* Renames the existing commodity code filter field to 'Specific commodity code' for clarity
> TP2000-791 Enable filtering by commodity code chapter

- commodities/tests/test_commodity_tree_snapshot.py
- common/models/tracked_qs.py
- measures/tests/test_measure_snapshot.py
`TrackedModelQuerySet.approved_up_to_transaction()` was updated to exclude ARCHIVED workbaskets from the queryset, which degraded response times.
All ARCHIVED workbaskets have been cleared and removed as part of [a separate task](https://uktrade.atlassian.net/browse/TOPS-1090). ARCHIVED workbaskets should never be used again now that the use case for their use has gone - single, system-wide workbaskets that needed to be swapped in and out of EDITING status. The problematic `exclude()` has therefore now been removed from `TrackedModelQuerySet.approved_up_to_transaction()`. Two tests that considered the use of ARCHIVED workbasket have also been amended.
> TP2000-793 fix slow approved_up_to_transaction() filtering

- measures/models.py
ME16 has been causing intermittent issues and now needs to be temporarily overridden (removed) to allow a data fix for HMRC, which relies upon overlapping measures with and without additional codes.
Remove the ME16 rule check from Measure's set of business rule checks. The rule will be re-instanted when there's less immediate pressure to support HMRC with this change - on another ticket.
> TP2000-794 Remove ME16 rule from Measure

- publishing/jinja2/includes/envelope-queue.jinja
- publishing/jinja2/includes/packaged-workbasket-queue.jinja
- publishing/jinja2/publishing/envelope_queue.jinja
- publishing/views.py
When multiple pages are necessary to display all queued items on the packaging and envelope queue views, the following issues appear:
- Two rows of page navigation are shown on the envelope queue page.
- On pages beyond the first page, the top-most row of the packaging queue page displays the “GENERATING ENVELOPE” notice.
- On pages beyond the first page, the top-most row of the envelope queue page displays the “GENERATING ENVELOPE” notice and the “Accept” and “Reject” placeholders.
Remove the extra page navigation from the envelope queue page.
Display correct information on the top-most queued item row for pages > 1.
> TP2000-792 Queue multi-page display quirks

- measures/jinja2/measures/search.jinja
The “create a new measure” link on the Find and edit measures page (measures/search) resolves to an incorrect url (measures/search/create), resulting in a page not found 404 error.
- Corrects the url that 'create a new measure' link uses
> TP2000-799 Amend "create a new measure" link on Find and Edit measures page

- publishing/views.py
`page_by = 2` was added to `EnvelopeQueueView` when testing. It should have been removed.
Remove the `EnvelopeQueueView.page_by` override.
> Remove EnvelopeQueueView.page_by - added during testing

- measures/forms.py
- measures/tests/test_forms.py
Users should not be able to add the same footnote more than once in the footnotes form step of the create measure journey.
- Displays an error if the same footnote is added multiple times
- Adds missing unit tests for the form
> TP2000-767  Prevent duplicate footnote selection

- measures/conditions.py
- measures/constants.py
- measures/forms.py
- measures/tests/test_views.py
- measures/views.py
Users need to be able to edit duties for multiple measures.
- Adds duties step to multiple measures edit wizard to allow editing duties
> TP2000-772  Add duties to multiple measures edit journey

- common/forms.py
- common/tests/test_views.py
- publishing/forms.py
- publishing/jinja2/includes/queue-paused.jinja
- publishing/jinja2/includes/queue-unpaused.jinja
- publishing/jinja2/publishing/complete-envelope-processing-confirm.jinja
- publishing/jinja2/publishing/envelope_queue.jinja
- publishing/jinja2/publishing/packaged_workbasket_queue.jinja
This PR holds a couple of content changes around the automation process. This includes things such as: 
- changing DIT to DBT
- changing pause and unpause to stop and start on the queue buttons
- renaming a couple of H1s an H2s from Order and Package workbaskets to Package Workbaskets
- Requires migrations? - no
> TP2000 775 automation copy changes

- measures/tests/test_views.py
- measures/views.py
When a measure is updated through the multiple measures edit journey, footnote associations present on the measure aren't being preserved on the new version of the measure because the association is based on the old measure's pk.
- Updates existing footnote associations with the new version of the measure. 
- Adds unit test
> TP2000-814 Preserve footnote associations on measures edit

- workbaskets/views/ui.py
The 'Review measures' view on the workbasket page is limited to 1000 measures. It has been proposed that this limit can now be removed.
- Removes paginator class that set the limit from ReviewMeasuresWorkbasketView
> TP2000-526 Remove measures limit in workbasket review view

- common/jinja2/includes/common/actions.jinja
- common/jinja2/includes/common/tabs/core_data.jinja
- common/jinja2/includes/common/tabs/descriptions.jinja
- geo_areas/jinja2/geo_areas/detail.jinja
- geo_areas/jinja2/includes/geo_areas/tabs/core_data.jinja
- geo_areas/jinja2/includes/geo_areas/tabs/memberships.jinja
Content on geo areas view could be improved to contextualise the data presented to users.
- Adds area code to page title of a geo area
- Adds area code column to memberships tab
- Adds memberships table description
- Adds action pane to tabs
> TP2000-798  Update geo areas view

- settings/common.py
[Since Django 3.2](https://docs.djangoproject.com/en/3.2/ref/settings/#std-setting-DEFAULT_AUTO_FIELD), if a primary key is not explicity specified on a model and no value is given for `DJANGO_AUTO_FIELD` in `settings.py`, then the following type of error is output by Django when its checks are executed:
```
importer.ImportBatch: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
HINT: Configure the DEFAULT_AUTO_FIELD setting or the AppConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
```
This PR adds the `DEFAULT_AUTO_FIELD` setting to TAP's settings file, assigning it the default value, `"django.db.models.AutoField"`, that would have been created if Django …
> TP2000-829 Add DJANGO_AUTO_FIELD spec to settings

- geo_areas/forms.py
- geo_areas/tests/test_forms.py
- geo_areas/tests/test_views.py
- geo_areas/views.py
Users are unable to edit an end date for a geographical area.
- Adds form to allow editing an end date for a geo area (accessible via 'Edit this geographical area' link on geo area view or /geographical-areas/SID/edit)
- Adds unit tests
##
> TP2000-800  Implement geo area end-date editing

- common/tests/test_models.py
- geo_areas/models.py
- geo_areas/tests/test_models.py
- measures/tests/test_views.py
* URL did not work
* Content was not very helpful/descriptive
* Updates the `__str__ `method to get the proper description for geo area memberships
* Adds GetTabURLMixin to get the proper URL for geo area memberships
> TP2000-768 Show proper description and url for geo area memberships in workbasket

- geo_areas/forms.py
- geo_areas/tests/test_views.py
- geo_areas/views.py
Users are unable to add countries or regions to geographical area groups to create new geographical memberships.
- Extends `GeographicalAreaEditForm` to allow adding a single country or region as a member of a single area group
- Adds tests
##
When editing an area group:
When editing a country or region:
> TP2000-802  Add memberships to geo area editing

- common/jinja2/common/accessibility.jinja
- common/jinja2/layouts/layout.jinja
- common/tests/test_views.py
- common/urls.py
- common/views.py
- pii-secret-exclude.txt
TAP must include a link to its accessibility statement.
- Creates new page to host accessibility statement (viewable at /accessibility-statement)
- Adds accessibility statement link to footer
- Adds test
#
> TP2000-488  Include accessibility statement

- additional_codes/tests/test_views.py
- additional_codes/views.py
- certificates/tests/test_views.py
- certificates/views.py
- common/jinja2/common/delete.jinja
- common/jinja2/includes/common/tabs/descriptions.jinja
- common/views.py
- footnotes/tests/test_views.py
- footnotes/views.py
- geo_areas/tests/test_views.py
- geo_areas/views.py
When additional codes, certificates, footnotes and geo areas have only one description, TAP allows users to delete it, which results in a business rule violation. 
- Hides delete link from description tab if only one description is available
- Adds `DescriptionDeleteMixin`, used by delete forms to prevent the only description from being deleted
- Styles the cancel link as a button
- Adds tests
> TP2000-826  Prevent only description deletion

- common/views.py
- geo_areas/forms.py
- geo_areas/tests/test_forms.py
- geo_areas/tests/test_views.py
- geo_areas/views.py
Form validation for editing the end date of a geographical area needs to cover where the validity period of the geographical area would no longer span the validity period of a linked quota order number origin.
- Adds validation to `GeographicalAreaEndDateForm`
- Adds test
~~Adds the ability to `BusinessRulesMixin` to run indirect business rules for `TrackedModelChangeViews`~~
~~Adds indirect business rule ON6 to geo area update view~~
##
> TP2000-830  Expand validation for editing geo areas

- publishing/storages.py
- publishing/tests/test_tasks.py
When an envelope is rejected during packaging process, its ID is recycled for use by the next envelope. Currently, the S3 object name of an envelope is the same its external envelope file name (i.e. the name seen when downloading an envelope through the TAP UI). If S3 versioning is not enabled, then this S3 object naming policy results in rejected envelopes being overwritten and lost within S3.
This PR decouples the S3 object name from the external envelope file name by introducing a time stamp as part of the S3 object name. An envelope's file name remains unchanged when downloading via the TAP UI.
> TP2000-820 Decouple envelope name from S3 object key

- commodities/jinja2/includes/commodities/list.jinja
- commodities/jinja2/includes/commodities/tabs/core_data.jinja
- commodities/models/orm.py
- commodities/tests/test_views.py
- commodities/views.py
Both suffix and indent data is missing from the find commodities view. Displaying this data would help users more easily find a relevant commodity code. 
- Adds suffix and indent columns to find commodities view
- Update test
##
> TP2000-844  Add suffix and indent columns to find commodities view

- common/jinja2/common/app_info.jinja
- common/views.py
- workbaskets/jinja2/workbaskets/summary-workbasket.jinja
- workbaskets/models.py
- workbaskets/tests/test_models.py
- workbaskets/views/ui.py
Users are not able to see the progress of a rule check.
- Adds `rule_check_progress` function to `WorkBasket` model to provide progress of a rule check for the workbasket
- Displays rule check progress on workbasket summary and application information pages.
##
Workbasket summary:
Application information:
> TP2000-738 Display rule check progress

- quotas/filters.py
- quotas/forms.py
- quotas/tests/test_views.py
The 'search and filter' form on the 'find and edit quotas' view is missing options to filter by "active" and "terminated" quotas.
- Adds `ActiveStateMixin` to `QuotaFilter`
- Adds test
##
> TP2000-849  Add active state filter to quota search

- common/forms.py
- common/templates/common/widgets/nested_radio.html
- common/tests/test_forms.py
- measures/forms.py
- measures/jinja2/measures/create-footnotes-formset.jinja
- measures/jinja2/measures/edit.jinja
- measures/models.py
- measures/tests/test_forms.py
- measures/tests/test_views.py
- measures/views.py
* When a single measure needed to be edited its geo area exclusions were not prepopulated meaning the user would have to fill these in again even if editing a different field on the measure. This was time consuming and error prone
* Updates the FormSet class and BindNestedForms mixin to properly add initial data to formsets
* Also updates the display of exclusions in the workbasket to show which area is excluded
> TP2000-477 Prepopulate geo exclusions

- measures/migrations/0014_action_pair_data_migration.py
- settings/common.py
The scheduled sqlite dump of TAP data is failing due to a data migration failure. Migrations are run as part of the sqlite database creation process, before it has been populated with data. The migration failure causes the dump to fail.
This PR guards against using non-existent data in the data migration `measures.migrations/0014_action_pair_data_migration.py`, preventing a failure within the Sqlite dump process.
> TP2000-860 Sqlite dump and upload failing

- measures/forms.py
- measures/tests/test_forms.py
When selecting a single country as the geographical area, TAP is assigning the selection as both the area to be selected and the geographical exclusion.
Re added the exclusion specific Mapping constant as the select specific geo area does not have an exclusions field.
Previous PR: https://github.com/uktrade/tamato/pull/889
>  Exclusion created on Single Geo area selection Fix

- common/paths.py
- measures/forms.py
On the measure edit view, the delete button for the footnote form redirects the user to /measures/<sid\>/**edi-footnotes**  causing a page not found (404) error.
- Fix `self.path` so that "-footnotes/" is appended to an unsliced `path` (e.g /measures/<sid\>/edit).
> TP2000-861 Fix footnote delete button on measure edit view

- measures/business_rules.py
- workbaskets/jinja2/workbaskets/violation_detail.jinja
- workbaskets/views/ui.py
TAP is generating false (incorrect) violations during rule checking around commodities with a specific indent arrangement.
At least one comm code (code: 0406901300, suffix: 80) has multiple indents with historic indent creation, all within the same transaction. When a measure is applied to the comm code, indent selection can be incorrect.
The root cause requires a fix. In the interim, a rule check override that is accessible only to users with superuser status needs to be made available.
This PR implements a capability, only available to users with superuser status, to override failing rules checks.
- Requires dependency updates?
> TP2000-870 Superuser rule check violation override

- commodities/views.py
* Old query was not showing the correct version of measures that had an end date of December 2020
* Uses current() instead of as_at_today() for the measures queryset
> TP2000-853 Fix for measures as defined tab

- common/jinja2/includes/common/tabs/descriptions.jinja
- common/static/common/js/addNewForm.js
- geo_areas/forms.py
- geo_areas/jinja2/geo_areas/confirm-create-membership.jinja
- geo_areas/jinja2/geo_areas/confirm-create.jinja
- geo_areas/jinja2/geo_areas/create-membership-formset.jinja
- geo_areas/jinja2/geo_areas/create.jinja
- geo_areas/jinja2/includes/geo_areas/tabs/memberships.jinja
- geo_areas/tests/test_forms.py
- geo_areas/tests/test_views.py
- geo_areas/urls.py
- geo_areas/validators.py
- geo_areas/views.py
- workbaskets/jinja2/workbaskets/edit-workbasket.jinja
Now that the ‘Edit Geographical area’ journey has been implemented, we should complete the final journey, ‘Create a new geographical area’, which will allow users to create their own geographical areas without the need to involve data engineers.
- Adds `GeoAreaCreate` view and `GeographicalAreaCreateForm`, enabling users to create new geo areas
- Adds `GeographicalMembershipCreate` view and `GeographicalMembershipBaseFormSet`, enabling users to create multiple new memberships for a geo area (TP2000-858)
- Adds 'create a new geo area' link to workbasket menu
- Adds 'create a new membership' link to memberships tab of a geo area
- Adds view and form unit tests
##
> TP2000-857  Implement geo area create journey

- README.rst
- sample.env
When copying from sample.env to set up local dev environment, packaging automation fails to run locally because some environment variables that are needed to mock s3 upload with minio are missing.
- Adds `S3_ACCESS_KEY_ID`, `S3_SECRET_ACCESS_KEY`  and `S3_ENDPOINT_URL` to sample.env
> Add missing env variables to sample.env for local development setup

- commodities/jinja2/commodities/detail.jinja
- commodities/jinja2/commodities/measures-declarable.jinja
- commodities/jinja2/commodities/measures-defined.jinja
- commodities/jinja2/commodities/measures.jinja
- commodities/tests/test_views.py
- commodities/urls.py
- commodities/views.py
* Users need to be able to see what measures apply to a given commodity when the measure has been defined on a commodity code higher in the tree
* Uses `MeasureSnapshot.get_applicable_measures` to return the list of measures that apply to a commodity for the commodity tree at a given moment in time
* Displays a sortable paginated list of measures like the Measures as defined tab
* Also tidies up some naming and template organisation
> TP2000-854: Measures on declarable commodities

- geo_areas/forms.py
- geo_areas/static/geo_areas/scss/_geo_areas.scss
On the Add memberships page (geographical-areas/\<sid\>/membership-create/), the layout goes a bit askew when a form field has an error message.
- Adds a CSS class so that form input remain inline
##
Before:
After:
> TP2000-872 Fix 'Add memberships' form error message alignment

- Procfile
- README.rst
- common/celery.py
- docker-compose.yml
- manifest.yml
- settings/common.py
- CPU usage on a single worker is exceeding over 100% in production so load should be reduced
- The rule check can execute multiple tasks and can be log running seperating out the worker ensure that these tasks will not hold up other tasks or vise versa
- Celery routing updated to route to specific queue's standard & rule-check
- This routing is then set up locally using multiple docker instances each running a different queue
- Procfile updated to include new worker (will not run until scaled)
- Updating this page with infrastructure details https://readme.trade.gov.uk/docs/playbooks/trade-tariff-management.html
> Tp2000 780  separate rule check worker

- quotas/forms.py
- quotas/jinja2/includes/quotas/actions.jinja
- quotas/validators.py
- quotas/views.py
* Users need a way to edit quota order numbers
* This lays the groundwork for editing certificates and geographical areas that will be done in another PR
* Adds an edit page and form for order numbers allowing users to change validity period and category
> TP2000-884: Add quota edit form for validity period, category

- common/forms.py
- measures/forms.py
- measures/jinja2/measures/create-conditions-formset.jinja
- measures/tests/conftest.py
- measures/tests/test_forms.py
- measures/tests/test_views.py
- measures/validators.py
When we automated the creation of the negative action code for use in the Create Measures journey, we removed the negative actions from the UI menu.
Unfortunately this has also removed them from the Edit Measures journey, meaning that a user can’t complete the journey as the required UI setting is missing.
- Edit Measure condition form - field action - queryset updated to include all actions
- New validation for edit measure condition forms that checks that all fields are blank when a negative action code is selected.
- formset errors now appear in edit formset for conditions
- Formset validation now counts negative actions seperately so the form can successfully submit when editting negative actions too
>  Edit Measure Conditions Fix

- commodities/models/dc.py
- settings/common.py
- workbaskets/tasks.py
As per TARIC3, it's valid to have multiple instances of an indent that provide different start dates within the same transaction. This arrangement of indents in TAP data isn't catered for in commodity tree snapshot code, causing incorrect commodity extent values and therefore ancestor commodities within the tree.
In addition to ordering indents by transaction when loading the commodity collection, also apply a secondary ordering of `start_date`. This ensures correct indent selection when constructing a commodity tree snapshot.
> TP2000-891 Multi-version + same transaction indent causes ME32

- publishing/models/tap_api_envelope.py
- publishing/tariff_api/client.py
- publishing/tariff_api/interface.py
- publishing/tasks.py
- publishing/tests/test_tasks.py
- sample.env
- settings/common.py
An envelope becomes "stuck" in currently processing state if the previous publishing task fails to transition it to a new publishing state and/or set any published timestamps.
- Extends API Client to include GET request for an envelope
- Handles API envelope stuck in currently processing state
- Adds tests
TP2000-777
> Handle currently processing state

- common/tests/test_validators.py
- common/validators.py
- settings/common.py
Password validation in the admin (applies only to local, non-SSO created accounts) must take into account password policy.
- Adds `PasswordPolicyValidator` that is used in addition to existing password validators.
- Adds test
> TP2000-682  Add password policy validator

- common/forms.py
- common/templates/common/widgets/formset_field.html
- common/tests/test_forms.py
- common/widgets.py
- geo_areas/constants.py
- geo_areas/forms.py
- geo_areas/tests/test_utils.py
- geo_areas/utils.py
- measures/forms.py
- measures/tests/test_forms.py
- quotas/constants.py
- quotas/forms.py
- quotas/jinja2/includes/quotas/tabs/core_data.jinja
- quotas/models.py
- quotas/tests/test_forms.py
- quotas/tests/test_views.py
- quotas/views.py
* Users need to be able to edit quota origins for some upcoming policy implementation
* Adds an origin section to the quota edit form
* Allows editing of the origin validity, geographical area and exclusions
* Currently it's only possible to edit quotas with one origin, not multiple
* Also updates the quota detail UI to better represent quota origin data
> TP2000-894: Quota origin edits

- common/static/common/js/autocomplete.js
Autocomplete doesn't handle results which contain new lines characters consistently. Results which contain new line characters (for example, the descriptions for commodity codes 8708942000 & 8414302030) are considered as a new query when selected, causing results to be repopulated again unnecessarily through an additional fetch request. 
If a user selects one of the results and submits a form before the fetch request has resolved, then the user's selection can sometimes be "forgotten" by the server. This intermittent issue can be seen occurring during the create a new measure (TP2000-823) and multiple measure edit journeys (TP2000-905). 
- Adds a new function to remove new line characters from autocomplete results
- Fixes another issue with autocomplete where a previously selected result …
> TP2000-905  Remove newline characters from autocomplete results

- common/static/common/js/addNewForm.js
- common/static/common/js/autocomplete.js
A TypeError introduced by https://github.com/uktrade/tamato/pull/932, caused by attempting to remove new line characters from an undefined value, is preventing the Add new button from working when the autocomplete field is empty. 
- Attempts to remove new line characters only if original value is not null
- Fixes unrelated TypeError spotted when trying to add a new form for forms without duties input
> Fix autocomplete TypeError

- measures/jinja2/includes/measures/list.jinja
- measures/jinja2/includes/measures/tabs/core_data.jinja
- measures/jinja2/includes/measures/workbasket-measures.jinja
- workbaskets/tests/test_views.py
To provide a richer data experience to users, links could be added to commodity codes on the following: find and edit measures view, workbasket measure review view and measure details view.
- Hyperlinks commodities to their respective commodity detail view on the above views
##
Find and edit measures search results view:
Workbasket review measures view:
Measure details view:
> TP2000-514 Add commodity links in find and edit, review measures views

- measures/forms.py
- measures/jinja2/measures/create-review.jinja
- measures/tests/test_forms.py
- measures/tests/test_views.py
- measures/validators.py
- measures/views.py
Create a new measure journey lacks validation to prevent ME40 violations.
- Fixes the displaying of duties under conditions on the review page
- Commodities and conditions forms check if duties are permitted for the selected measure type
- Review form checks if mandatory duties are missing for the selected measure type
- Updates and adds tests
#
> TP2000-888  Add ME40 validation to create a new measure journey

- common/jinja2/layouts/confirm.jinja
- common/models/trackedmodel.py
- common/tests/factories.py
- common/tests/util.py
- geo_areas/tests/test_utils.py
- geo_areas/utils.py
- measures/forms.py
- quotas/forms.py
- quotas/jinja2/includes/quotas/quota-edit-origins.jinja
- quotas/jinja2/includes/quotas/tabs/core_data.jinja
- quotas/jinja2/quota-origins/confirm-update.jinja
- quotas/jinja2/quota-origins/edit.jinja
- quotas/jinja2/quota-origins/macros/origin_display.jinja
- quotas/models.py
- quotas/tests/test_views.py
- quotas/urls.py
- quotas/views.py
* Users need to be able to edit multiple quota origins to support upcoming tariff changes
* Uses the single origin edit form added previously
* On the quota order number edit form page, multiple origins are listed with links to their own separate edit forms where these can be edited individually
> TP2000-909: Multiple quota order number origin edits

- measures/jinja2/includes/measures/list.jinja
- measures/jinja2/includes/measures/tabs/footnotes.jinja
- measures/jinja2/includes/measures/workbasket-measures.jinja
- measures/jinja2/measures/delete-multiple-measures.jinja
- measures/jinja2/measures/edit-multiple-measures-enddates.jinja
- measures/jinja2/measures/edit-multiple-start.jinja
* What was displayed in the UI was not matching the latest version of the measure stored in the db
* Use footnoteassociationmeasure_set.current() to get the most up to date version of footnotes via the footnote association for the measure
> TP2000-911: Fix measure footnotes display

- common/jinja2/macros/footnotes_display.jinja
- measures/jinja2/includes/measures/list.jinja
- measures/jinja2/includes/measures/workbasket-measures.jinja
- measures/jinja2/measures/delete-multiple-measures.jinja
- measures/jinja2/measures/edit-multiple-measures-enddates.jinja
- measures/jinja2/measures/edit-multiple-start.jinja
* Some footnote display was wonky because we were using the footnote association object and not the footnote itself
* Uses association.associated_footnote to get the correct display for footnotes
* Also creates a reusable macro for this
> TP2000-911: (Another) footnotes display fix

- importer/jinja2/includes/taric_importer_list.jinja
- importer/urls.py
- importer/views.py
- workbaskets/tests/test_views.py
- workbaskets/views/ui.py
A link on the import list view should redirect the user to an import's workbasket if the import has status 'COMPLETED'.
- Extends `SelectWorkbasketView` to allow specifying which tab to redirect to in a workbasket view
- Adds test
- Shows a link (to import's workbasket) for completed imports only
- Removes `CommodityImportDetailURLResolverView` since we no longer need dynamic linking for imports of varying status
> TP2000-915 Redirect imports with completed status to workbasket

- measures/business_rules.py
- measures/tests/test_buinsess_rules/test_ME67.py
- measures/tests/test_business_rules.py
added tests to verify the change not only passes existing tests but extends and verifies and passes additional scenarios that were incorrectly failed in production previously
* ME67 did not pass in valid scenarios.
* Unit test coverage missed some data configurations that were valid.
* Updated the logic for ME67 to verify the date range of the change against the data
* Added tests to cover additional scenarios, observed as incorrectly raising violations in production
- Requires migrations? NO
- Requires dependency updates? NO
See: [Description](https://uktrade.atlassian.net/browse/TP2000-914)
> Updated ME67 and added additional unit tests 

- importer/jinja2/eu-importer/import-success.jinja
- importer/models.py
- importer/tasks.py
When the parser has completed its work it must, depending on its whether it has succeeded or failed, transition the related ImportBatch instance status to SUCCEEDED or FAILED.
Upon the parser completing it correctly transitions the `ImportBatch.status` via the `succeeded()` and `failed()` transition functions. The workbasket associated with the import is also managed correctly, transitioning its state depending upon the outcome of the import. Info log messages have also been added to help with any debugging / investigation where necessary.
Comments also added to the parser code while exploring required work.
> TP2000-921 transition import status to succeeded and failed

- geo_areas/tests/test_utils.py
- geo_areas/utils.py
- measures/patterns.py
- measures/tests/test_patterns.py
The `get_all_members_of_geo_groups` function  (used when editing a quota order number origin to update any exclusions) doesn't use the latest version of `GeographicalMembership` queryset. This is causing an issue where an end-dated member of the passed in geo group is still ultimately added as an exclusion.
Also, the function doesn't guard against geo groups sharing members, sometimes resulting in a member/geo area being added multiple times as an exclusion.
When testing this PR, another issue had also been identified this time in the create measure journey concerning geo area member exclusions. `create_measure_excluded_geographical_areas` like `get_all_members_of_geo_groups` does not use the latest version of `GeographicalMembership`, causing a server 500 error on attempted measure …
> TP2000-929  Fix quota form geo area member exclusions

- quotas/models.py
- quotas/tests/test_models.py
Autocomplete results for quota order numbers don't distinguish multiple versions of the same quota order numbers with different validity periods. 
- Adds validity period to quota order number autocomplete label to help users identity the correct quota order number for their use
##
Before:
##
After:
> TP2000-936 Add validity period to quota order number autocomplete label

- publishing/tests/test_util.py
- publishing/util.py
There is a condition where a measurement may not be present in the XML if there is no associated measurement unit qualifier. 
This issue currently prevents an existing workbasket from correctly producing an envelope as it fails at the count of expected elements. 
This fix updates the logic used to count the expected elements and corrects the issue. Tests also added
* Added a method to conditionally count measurements if the measurement is in the workbasket, and there is an associated unit qualifier 
* Updates tests to check correctly for this
> Fix for envelope export, when a measurement unit is created.

- common/jinja2/macros/inline_filter_links.jinja
- conftest.py
- importer/filters.py
- importer/jinja2/eu-importer/select-imports.jinja
- importer/tests/test_views.py
- importer/views.py
There's a need to filter imports on the list page by not only their status but  in combination with their linked workbasket's status too.
5 filters have been added to the import list page (beyond the all status): 
Importing - This filters for imports with a status of IMPORTING. 
Completed - This filters for imports with a status of SUCCEEDED and a linked workbasket status of EDITING
Published - This filters for imports with a status of SUCCEEDED and a linked workbasket status of PUBLISHED
Empty - This filters for imports with a status of SUCCEEDED and a linked workbasket status of ARCHIVED
Errored - This filters for imports with a status of FAILED
I've also added tests to check that the right filters are rendered, and that their links do what they say on the tin 🌻  …
> TP2000-920 Add additional filters to the import list page

- measures/business_rules.py
- measures/tests/test_buinsess_rules/test_ME67.py
When checking against exclusions, the rule check historically looked at the old version of the measure (e.g the one linked to the exclusion, not the potentially most recent version in the same or previous transaction based on the workbasket).
* TP2000-944
* ME67 was not behaving correctly 
* Valid changes may raise business rule violations incorrectly
What is this PR doing, e.g. implementations, algorithms, etc.?
* Update ME67 to query the latest version of the measure based on the transaction / workbasket
See: [JIRA](https://uktrade.atlassian.net/browse/TP2000-944)
> TP2000-944 : Update ME67 to look at measure based on transaction

- conftest.py
- importer/chunker.py
- importer/tests/management/commands/test_chunk_taric.py
- importer/tests/test_forms.py
Follow-up PR to https://github.com/uktrade/tamato/pull/961 to fix some unit tests that fell through the net. 
- Mocks `CommodityImportStorage.save()` to fix `CommodityImportForm` test
- Calls `build_dependency_tree()` directly to populate `dependency_tree` (previously showing as empty) to fix `test_write_transaction_to_chunk_exceed_max_file_size`
- Fixes test_chunk_taric.py test by passing in pk of preceeding batch
> TP2000-933 Fix failing importer tests

- geo_areas/tests/test_views.py
- geo_areas/views.py
Attempting to create a description for the Geographical Region Saint Helena raises `MultipleObjectsReturned` error.
- Updates `GeoAreaDescriptionCreate` view and `GeoAreaCreateDescriptionMixin` to use `current()` in queryset to get the latest version of a geo area
- Adds test for creating a geo area description
> TP2000-946  Fix geo area description create error

- .gitignore
- importer/goods_report.py
- importer/management/commands/generate_goods_report.py
- importer/models.py
`ImportBatch` instances must have an Excel format goods reporting capability. Reports in this format may then be downloadable by TAP users via a UI intergration. Ideally, other formats, such as csv and markdown, should also be supported.
This PR:
- Provides a library capability for parsing and generating reports of goods-related items in TARIC3 files.
- Offers report output formats of CSV (in Excel dialect) and Excel file (xslx).
- Provides a Django management command, `generate_goods_report`, to access report file generation capabilities, with a variety of options (generate from TARIC3 file on the file system, generate from ImportBatch instance, etc).
> TP2000-807 Goods file reporting

- importer/goods_report.py
- importer/urls.py
- importer/views.py
- workbaskets/jinja2/workbaskets/review-goods.jinja
- workbaskets/views/ui.py
Users require the ability to download a report of goods changes resulting from an import in Excel file format.
- Adds view to serve a downloadable goods report in Excel format
- Make 'Download as Excel' button visible only for workbaskets that have an associated import batch
> TP2000-953  Downloadable goods report

- importer/tests/test_forms.py
One failing test remains in importer-mega-branch: `importer/tests/test_forms.py::test_commodity_import_form_valid_envelope`
- Mock calls to `chunk_taric` and `run_batch` to prevent task from being triggered during the form test
> TP2000-933 Fix remaining failing test

- importer/goods_report.py
- importer/management/commands/generate_goods_report.py
The goods reporter lacks support for outputting a representation of a goods report in Markdown table format.
- Adds support for generating a report in Markdown table format
- Cell padding is added to prettify unwrapped output string
Raw output string when unwrapped
Same output string when rendered as Markdown:
|update_type  |whats_being_updated                     |goods_nomenclature_code  |suffix  |validity_start_date  |validity_end_date  |containing_transaction_id  |containing_message_id  |
|:------------|:---------------------------------------|:------------------------|:-------|:--------------------|:------------------|:--------------------------|:----------------------|
|CREATE       |Goods nomenclature description          |1234567890               |80      |                     | …
> TP2000-956 Generate goods report in Markdown table format

- measures/views.py
* If a measure already has edits in the current workbasket, the edit link on the measure detail page is hidden. This was because the measure-edit-update url did not exist
* Add MeasureEditUpdate view that inherits from MeasureUpdate as an initial fix. This view should be updated to support "real updates" in future
> TP2000-961: Fix missing edit-update measure view

- measures/patterns.py
- measures/tests/test_views.py
- measures/views.py
from a previous story we removed the ability to select "negative" actions and we automatically generate them instead. 
Out of this there is an emerging requirement that we need to create a negative action when a certain action is selected for a given measure type.
- When you create a measure with type 112 Autonomous tariff suspension with a condition that has an action code 01 you will see an automatically generated negaitve code 07 in the workbasket summary. Like the current measure type 115 automatic condition generation implementation.
- Note currently you will not see this in the create conitions form or the review screen this is pending work to refactor measure conditions
> TP2000-896 Create measure condition action automatically

- importer/forms.py
- importer/tests/test_forms.py
Tariff managers typically use the TGB file name in the description of an import's workbasket. This description could be prefilled so that it doesn't have to be manually updated later. 
- Prefills the import batch's workbasket description in the format "TARIC [file_name] commodity code changes" as seen with other imports' workbaskets
> TP2000-967  Prefill workbasket description for an import

- measures/forms.py
- measures/parsers.py
- measures/patterns.py
- measures/tests/test_forms.py
- measures/tests/test_views.py
- measures/util.py
- measures/validators.py
- measures/views.py
Users are experiencing performance-related issues when creating measures with 50+ commodities and duties.
The issue appears to be caused by a combination of how the duty sentencer parser is being used and how the form wizard fetches cleaned data for a step:
1) A new duty sentence parser is loaded each time to validate a duties field in the formset
2) The same duty sentence may be parsed multiple times
3) A new duty sentence parser is loaded for each measure created
4) `get_cleaned_data_for_step()` revalidates a form before returning the cleaned data (exacerbating 1). This is used both in `get_form_kwargs()` and on the summary page to populate the template. It can become a recursive call if a form's kwargs depends on the cleaned data of another form, as happens with commodities step …
> TP2000-949  Improve measure creation performance

- common/static/common/js/checkboxes.js
- workbaskets/jinja2/includes/workbaskets/workbasket-selectable-items.jinja
- workbaskets/tests/test_views.py
- workbaskets/views/ui.py
* A user can make multiple selections across multiple pages and the remove button removes those objects successfully
* Clearing down a workbasket can be made a single option button, with a confirmation page.
* Pagination number bumped from 10 to 50
* Fixes a bug with persisting object selection across different pages
* Replaces the "select all across X pages" checkbox with a "remove all" button
> TP2000-400: Workbasket page fixes

- importer/goods_report.py
- importer/management/commands/generate_goods_report.py
- workbaskets/views/ui.py
Comments help to provide Tariff Managers with supplementary information (such as details of new descriptions and indent numbers) from the TGB file not displayable in other columns of the goods report.
- Adds comments column to goods report generation
- Uses tabulate library to generate Markdown table representation of report
- Updates workbasket review goods tab to include new column
##
| update_type   | whats_being_updated                   |   goods_nomenclature_code |   suffix | validity_start_date   | validity_end_date   | comments                                     |   containing_transaction_id |   containing_message_id |
|:--------------|:--------------------------------------|--------------------------:|---------:|:----------------------|:--------------------|:--------------------- …
> TP2000-968  Add comments column to goods report

- Procfile
- common/celery.py
- docker-compose.yml
- settings/common.py
The current parser capability relies on a shared caching resource (referred to as the nursery in the TAP codebase), which is not name-spaced between import processor. This is an issue when imports run in parallel, causing invalid objects to appear in an importer’s cache (nursery).
- A seperate worker for importing has been set up to process importing tasks
- worker set up with a concurrency of 1 so tasks are only processed one at a time in the order they are recieved
- local celery worker set up
> TP2000 926 Enforce a maximum of one active import per service instance

- importer/goods_report.py
- importer/management/commands/generate_goods_report.py
- importer/tests/management/commands/test_generate_goods_report.py
- importer/tests/test_files/goods_xml_report.md
- importer/tests/test_goods_report.py
Follow-up to #967 to implement unit test coverage for goods report generation.
- Tests that `GoodsReport` parses record elements and outputs to formats
- Tests `generate_goods_report` management command parses available arguments
> TP2000-954  Goods report unit tests

- geo_areas/tests/test_forms.py
As of today there is a failing unit test: `FAILED geo_areas/tests/test_forms.py::test_geographical_membership_edit_form_invalid_end_date`
The test uses whatever is the current day’s date to set not only the validity period of the area group but also the end dates in the form. When the date is the 31st, the test fails because it attempts to add 1 to it, resulting in an invalid date of 32nd.
- Use `date_range.earlier` and `date_range.later` fixture to avoid adding/subtracting whatever is the current date
> TP2000-985 Fix failing geo area form test

- importer/jinja2/includes/taric_importer_list.jinja
- importer/tests/test_views.py
- importer/views.py
When successfully importing a TARIC3 file containing goods-related elements, the import status shows SUCCEEDED, and the goods status column provides a navigation link to the related workbasket into which the goods objects have been saved.
However, when successfully importing TARIC file containing no goods-related elements, the import status correctly shows SUCCEEDED, but the goods status column is empty. This can leave some uncertainty about the status of the import.
This PR:
* Factors out display decision logic into a view function.
* Populates the goods status column with "0 goods items" if an TARIC file is successfully imported but contains no goods-related elements.
* Adds unit tests to validate that correct goods status column contents are rendered on the goods importer list view.
- …
> TP2000-987 - Add '0 goods items' support on importer list view

- importer/tests/management/commands/test_generate_goods_report.py
A `goods.xlsx` file is left hanging around after importer test runs. Specifically, the test for the xlsx report format generates a file - one of the formats tested by `test_generate_goods_report_output_format`.
Factor out the test for the xlsx report format and conditionally mock the `file()` built-in when applied to opening the `goods.xlsx` file.
> TP2000-997 - Prevent dangling goods.xlsx after test runs

- importer/forms.py
- importer/tests/test_forms.py
No workbasket is associated with an ImportBatch that has been created via the master importer. The workbasket is needed in order to correctly transition the import state during the parse phase of the import (asynchronously executed on a background task via Celery). The result is an import hung in IMPORTING state.
This PR associates ImportBatch instances with a workbasket within the master importer form save processing. The associated unit test has also been updated to account for this change.
> TP2000-993 - Master importer status updates stall

- geo_areas/views.py
Creating a new geographical membership via the ‘Create a new membership' link on the 'Memberships’ tab of a geographical area detail view does not show the membership association creation in the workbasket summary if the current workbasket has no previous transactions. It erroneously uses the workbasket's last transaction or the most recent global transaction.
- Uses a new transaction in the current workbasket for each membership being created
> TP2000-1008 Fix geo membership creation

- commodities/jinja2/includes/commodities/tabs/measures-declarable.jinja
- commodities/jinja2/includes/commodities/tabs/measures-defined.jinja
- commodities/jinja2/includes/commodities/tabs/measures-vat-excise.jinja
- commodities/tests/conftest.py
- commodities/tests/test_views.py
- commodities/urls.py
- commodities/views.py
- common/jinja2.py
- common/tariffs_api.py
- common/tests/test_tariffs_api.py
- common/tests/util.py
- conftest.py
- quotas/jinja2/includes/quotas/actions.jinja
- quotas/tests/test_views.py
- quotas/views.py
* Users want to be able to see VAT & excise measures related to a commodity code that aren't held in TAP
* Adds a VAT & excise measures tab to the commodity detail page
* Adds the commodity endpoint to the tariffs api module
> TP2000-912: Commodity VAT & excise measures

- measures/business_rules.py
- measures/jinja2/includes/measures/tabs/core_data.jinja
- measures/tests/test_business_rules/test_ME67.py
Update ME67 and add a test to verify it handles deleted measures correctly
* In production deleting a measure still triggers ME67 which fails because it cant find the measure .... becuase its deleted
* Altered the query in ME67 to find the measure, if it cant find it - its fine, dont check. 
* Added test to verify (which also failerd before update)
* All rules passing ion workbasket that originally seeded the ticket 
- Requires migrations? No 
- Requires dependency updates? No 
See: [Description](https://uktrade.atlassian.net/browse/TP2000-1009)
> TP2000-1009

- reports/reports/quotas_cannot_be_used.py
We are filtering out “09xxxx”, these are effectively EU quotas and they’re slowly being closed down.
During the query against the db, we are excluding quota order numbers that begin with 09.
> fix: TP2000-980 filter 09 quotas from quotas cant be used report

- requirements.txt
The [GitHub - uktrade/sqlite-s3vfs: Python writable virtual filesystem for SQLite on S3](https://github.com/uktrade/sqlite-s3vfs)  repo now automatically installs the aspw-wheels dependency (see this commit: [Merge pull request #21 from uktrade/build/automatically-install-apsw · uktrade/sqlite-s3vfs@98da943](https://github.com/uktrade/sqlite-s3vfs/commit/98da943566704277fafa9590be076a7a2d2686b8) )
The direct dependency included in Tamato’s requirements.txt should therefore be removed.
Update requirements.txt
> bump: sqlite-s3vfs to 0.0.35 and remove apsw-wheels

- measures/jinja2/includes/measures/tabs/footnotes.jinja
It was previously displaying the first footnote description in the queryset of associated footnotes when this was the oldest and not current one.
CD624 current footnote description:
Updated to display the last footnote description rather than the first.
> TP2000-1011 - Updating measure footnote details to show the latest description

- measures/filters.py
- measures/tests/test_filters.py
This is a bugfix for the Certificates filter on the find and edit measures page introduced in [PR 1014](https://github.com/uktrade/tamato/pull/1014)
The previous filter assumed that there was a direct link between Measures and Certificates. There is not.
This filter uses the link via MeasureCondition and adds tests.
No migrations or dependencies.
[TAP Bug comment thread](https://teams.microsoft.com/l/message/19:fdd22c5d3132421cbffc1ba7454f7d10@thread.tacv2/1693817104622?tenantId=8fa217ec-33aa-46fb-ad96-dfe68006bb86&groupId=16ae1baa-31cc-4fda-8ea7-cfcd00d254ed&parentMessageId=1693817104622&teamName=Tariff%20Team&channelName=TAP%20Bugs&createdTime=1693817104622&allowXTenantAccess=false)
> TP-2000-1025 - Bugfix - Certificate is not a valid field in MeasureList view

- common/forms.py
Goods importer journey selection is visible to all users
The “Import EU Taric files” journey is visible as a selection from the TAP home page to all users. The journey should be resricted to those users with the relevant permissions only - similar to other journeys that have a creational, edit or deletion action.
Following the same logic of the view and only exposing the link to users with permission to add or change trackedmodel
> feat: hide Import EU Taric files

- requirements.txt
http://sentry.ci.uktrade.digital/organizations/dit/issues/83955/?project=200
Caused by latest apsw release: https://pypi.org/project/apsw/#history
As we removed the direct relation in this PR:
https://github.com/uktrade/tamato/commit/7f4df66963001241be2a590775d637479faf3428
And the dependency from [sqlite-s3vfs](https://github.com/uktrade/sqlite-s3vfs/commit/98da943566704277fafa9590be076a7a2d2686b8) does not specify a version. So we need to pin it and perhaps resolve this in sqlite-s3vfs at a later date (I think we are the only team actively using this package so will ask DI)
> fix: add apsw package back in due to latest update causing failure

- additional_codes/tests/test_views.py
- additional_codes/views.py
- footnotes/tests/test_views.py
- footnotes/views.py
`FootnoteDescriptionCreate` view raises a `MultipleObjectsReturned` error when it encounters a footnote with more than one version.
- Uses current() to return the current version of the object only
- Prevents the same issue from occurring in `AdditionalCodeDescriptionCreate`
- Adds view unit tests
> TP2000-1054  Fix DescriptionCreate MultipleObjectsReturned error

- common/tests/factories.py
- conftest.py
- notifications/models.py
- notifications/tests/conftest.py
- notifications/tests/test_models.py
- notifications/tests/test_tasks.py
- publishing/models/crown_dependencies_envelope.py
In the notification model when accepting an envelope theres a bug that cause the notification to fail
- Added unit tests for those models
- Fixed the `.get` syntax
> fixed get packaged workbasket bug

- common/static/common/js/util.js
Footnote descriptions that contain line break characters (`\r\n`) interfere with the autocomplete field, causing some selections to become unselected. This issue was previously seen with commodities (#932).
- Adds `\r` character to the `newLine` regex used to clean autocomplete field results
> TP2000-1030 Fix footnote autocomplete selection

- common/jinja2/common/app_info.jinja
- common/tests/test_views.py
- common/views.py
There is no simple one-stop location to find all active Envelope generating Celery tasks. It’s currently important to present this information in TAP in order to show queue state and avoid deployment mishaps.
This PR adds information about all active Celery tasks that are generating Envelope instances. The details are made available to all users able to view the page.
> TP2000-1068 Envelope generation celery task info

- common/static/common/js/application.js
- common/static/common/js/buttonDebounce.js
- measures/jinja2/measures/create-review.jinja
The preventDoubleClick functionality has a time out on it. Occasionally, we exceed this timeout and the user is then able to double click the button, creating 2x the number of intended measures.
We have duplicated the data-prevent-double-click functionality, extending the timer to 5 seconds. Should we discover that some events are taking longer than 5 seconds, we can extend this timer again.
> adding debounce to submit new measure

- measures/forms.py
- measures/jinja2/includes/measures/conditions.jinja
- measures/jinja2/includes/measures/list.jinja
- measures/models.py
- measures/tests/test_forms.py
- measures/tests/test_models.py
- measures/tests/test_views.py
- measures/validators.py
- measures/views.py
There's an edge case condition where a duty should be applied if there is no certificate present. The negative actions in a condition currently block you populating the certificate, price or applicable duty fields. This requires remove from the edit screen to support.
- removed validation on fields certificate, price or applicable duty on the negative action code conditions in the edit measures screen
- removed condition_string as it is redundant and causing display bugs for single duty values (3.5%) and measures without additional codes.
- set .current() for conditions_list so it will display changes in the current worbasket when viewing conditions in list displays
> Tp2000 1070  address negative action edge case

- measures/jinja2/includes/measures/list.jinja
Swapping round the conditions and regulations columns in the Measure list page cause it looks nice
- Requires migrations? - no
> Swap round conditions and regulations on the measure list table

- manifest.yml
#TP2000-1082 Update Paas Unbuntu
[GOV.UK](http://gov.uk/) PaaS with SRE assistance are upgrading the version of Ubuntu used across applications and services. The change moves the PaaS platform from a [Ubuntu 18.04-based stack (cflinuxfs3)](https://github.com/cloudfoundry/cflinuxfs3) to [Ubuntu 22.04-based stack (cflinuxfs4)](https://github.com/cloudfoundry/cflinuxfs4).
This PR specifies the stack in the manifest.yml file to determine which version of cflinuxfs we should be using
- Requires migrations? - no
> TP2000-1082 Update Paas Unbuntu

- conftest.py
- publishing/tests/test_migrations.py
Migration tests fail due to stale `ContentType` cache, causing references to non-existant content type instances in the database.
Override the `migrator_factory` and `migrator` fixtures from the [django-test-migrations](https://github.com/wemake-services/django-test-migrations/) package in order to clear the `ContentType` cache in a timely manner - prior to performing migrations in migration tests. This ensures correct `ContentTypeManager` state when manipulating migrations in unit tests.
Links to relevant material:
https://code.djangoproject.com/ticket/10827
https://github.com/wemake-services/django-test-migrations/blob/93db540c00a830767eeab5f90e2eef1747c940d4/django_test_migrations/migrator.py
> Clear ContentType cache before applying migrations in unit test.

- quotas/forms.py
- quotas/jinja2/includes/quotas/actions.jinja
- quotas/jinja2/quota-definitions/confirm-create.jinja
- quotas/jinja2/quota-definitions/create.jinja
- quotas/tests/test_views.py
- quotas/urls.py
- quotas/views.py
* Users need the ability to create new definition periods for an existing quota order number
* Link to create a new definition on the quota order number detail page under the "Actions" list
* Single page form to create a new definition
* Success page
> TP2000-980: Quota definition create

- certificates/views.py
- workbaskets/forms.py
- workbaskets/jinja2/includes/workbaskets/navigation.jinja
- workbaskets/jinja2/workbaskets/macros/load_more_pagination.jinja
- workbaskets/jinja2/workbaskets/macros/transaction_details.jinja
- workbaskets/jinja2/workbaskets/transaction_order.jinja
- workbaskets/static/workbaskets/scss/_workbaskets.scss
- workbaskets/tests/test_views.py
- workbaskets/urls.py
- workbaskets/views/ui.py
A feature improvement to workbaskets is to introduce the capability to reorder workbasket transactions, allowing users to resolve business rule violations related to transaction ordering.
**This PR is based on the experimental branch created by Paul**: [EXPERIMENTAL--move-tranx-within-workbasket](https://github.com/uktrade/tamato/compare/master...EXPERIMENTAL--move-tranx-within-workbasket)
- Creates a new tab on workbasket detail view to allow users with the requisite permissions to view transactions and reorder transactions in workbaskets in an editing state
- Adds view unit tests
- Stops an empty transaction from being left behind when creating a new certificate
> TP2000-1078  Implement transaction order tab

- workbaskets/jinja2/workbaskets/macros/transaction_details.jinja
- workbaskets/tests/test_views.py
- workbaskets/views/ui.py
To move a transaction to the top or bottom of a workbasket currently requires pressing 'Move up' or 'Move down'  buttons many times. The addition of 'Move to top' and 'Move to bottom' actions would make this easier for users to achieve.
- Adds 'Move to top' and 'Move to bottom' actions to transactions listed in Transaction Order tab
- Handles in the view setting the transaction order of the moved transaction to be either first or last in the workbasket, updating other transactions accordingly
- Refactores transaction reordering form action unit tests into a single parametrised test
##
> TP2000-1099 Add 'Move to top' and 'Move to bottom' transaction reordering actions

- common/static/common/scss/_badges.scss
- common/static/common/scss/_text.scss
- importer/forms.py
- importer/jinja2/components/create-status-tag.jinja
- importer/jinja2/eu-importer/import-success.jinja
- importer/jinja2/eu-importer/select-imports.jinja
- importer/jinja2/includes/taric_importer_list.jinja
- importer/tests/test_views.py
- importer/views.py
In order to align TAP to GDS standards, a few tweaks to the importer pages have been added: 
- Change the status labels to rainbow colours (very cute) 
- Change status label text from 'Completed' to 'Ready'
- Change status label text from 'Errored' to 'Failed'
- Change top filters to match the new status name
- Rename Importer Status column to Status and add "Action" to the last column which was previously nameless
- Swap around the form fields on the upload page
- Update the copy on the success page
- Requires migrations? - no
> Tp2000 1055 update import status labels

- Makefile
- README.rst
- docker-compose.yml
- sample.env
- settings/envs/docker.env
When working with TAP DB's you may not always want to work with just a single db or run a db dump everytime you need to clear down the database. This is especially relevant to data engineers 
- added two new make commands `docker-import-new-db` which imports a new db into a template name & `docker-restore-db` which loads a template into the db (deafult name tamato)
- updated readme
- corrected sample.env around minio
> docker db managing improvements

- workbaskets/views/ui.py
The transaction order view only loads 20 transactions at a time. This number is too low for larger workbaskets. 
- Sets the view's paginate_by value to 100
> TP2000-1131 Increase pagination value for transaction order view

- geo_areas/forms.py
- geo_areas/tests/test_forms.py
Geo areas that were once members of an area group but have been end dated are unable to be re-added with new validity periods.
- Uses `current().as_at_and_beyond()` when checking if a geo area is already a member to allow for members to be re-added only with non-overlapping validity periods.
- Adds validity period to dropdown labels to help users distinguish between old and new when selecting to edit an existing membership
##
> TP2000-1133  Fix editing geographical memberships to allow members to be re-added

- measures/tests/test_forms.py
- measures/tests/test_measure_snapshot.py
A few unit tests fail intermittently requiring CI tests to be rerun:
`FAILED measures/tests/test_forms.py::test_measure_geographical_area_form_quota_order_number` [Example](https://github.com/uktrade/tamato/actions/runs/6615735968/job/17968517801)
`FAILED measures/tests/test_measure_snapshot.py::test_get_branch_measures` [Example](https://github.com/uktrade/tamato/actions/runs/6893445289/job/18753027522)
`FAILED measures/tests/test_measure_snapshot.py::test_init` [Example](https://github.com/uktrade/tamato/actions/runs/6639741721/job/18038725097)
`test_measure_geographical_area_form_quota_order_number`
- Use sets not lists to store geographical area objects allowing data comparisons based on value alone not value and order.
`test_get_branch_measures` and `test_init`
- Use a more specific …
> TP2000-1115 Fix flaky unit tests in measures/tests

- workbaskets/jinja2/workbaskets/edit-workbasket.jinja
the import com code journey now properly begins on the TAP homepage
- remove link from commodity code import link from add/edit workbasket tab on the view workbasket page
> Remove import com code link from add edit workbasket

- workbaskets/models.py
- workbaskets/tests/test_models.py
- workbaskets/tests/test_views.py
- workbaskets/views/ui.py
A workbasket that has previously been packaged, and then removed from the packaging queue, will have a non-nullable PackagedWorkBasket instance associated with it, preventing deletion owing to a ProtectedError exception. Users should however be given the appearance of a successful workbasket deletion.
- Adds a Django FSM condition to prevent non-empty workbaskets from being archived
- Checks whether a PackagedWorkBasket exists for a workbasket, archiving the workbasket instead of attempting to delete it if so.
> TP2000-1084 Archive empty, previously queued workbaskets on attempt to delete

- common/forms.py
- common/jinja2/common/workbasket_action.jinja
- common/jinja2/layouts/layout.jinja
- common/tests/test_views.py
- common/views.py
* Now that we’ve made the Workbasket finder (in the footer) a useable feature within TAP, with functionality to reorder items, review changes and provide a full audit trail. We should remove the Workbasket finder from the footer and replace it with a selectable option for specific user groups (for now).
* Adds an option to "Search for workbaskets" to the homepage that links to workbaskets/list-all 
* Removes this link from the footer
* Accessibility fixes for heading levels
* Content fixes. Use sentence case as per GDS guidelines
> TP2000-1128: View all workbaskets option, accessibility and content fixes

- additional_codes/forms.py
- common/jinja2/components/description_help.jinja
- Standardise formatting across tap and simplify the help text
- Simplifies the help text on the additional code create page
> TP2000-1107 Update content for additional code creation page

- common/forms.py
- common/tests/test_views.py
- workbaskets/views/ui.py
Users with HMRC profiles are unable to see the "Search for workbaskets" radio option on the workbasket actions form on the home page.
- Amends the requisite permission for the "Search for workbaskets" radio option to `workbaskets.view_workbasket`
- Updates unit tests
> TP2000-1143  Fix permission for Search for workbaskets home form action

- commodities/business_rules.py
- commodities/models/orm.py
- commodities/tests/business_rules/test_NIG11.py
- commodities/tests/business_rules/test_NIG5.py
- commodities/tests/business_rules/test_NIG5_origin.py
- commodities/tests/test_business_rules.py
- notifications/tests/test_models.py
- publishing/tests/test_model_envelope.py
* NIG5 should not be triggered when an origin is added, but validate on the goods transaction not the origins transaction
* NIG11 should not trigger if a goods is being deleted
* Full details on ticket 
* Both NIG5 and NIG11 recently triggered false positives for an EU update. 
* Upon investigation it was observed that NIG5 was associated with Goods origins as an indirect business rule, but the validate method used the goods transaction not the origins transaction so would fail if both goods and origin were not present in the same transaction. 
* NIG11 triggered and failed on a goods deletion
* Updated the query for the validation method for NIG5 to use the current transaction 
* Added an NIG5_origin rule, to run against …
> Updated NIG5 to correctly handle only goods create and update and NIG5_origin to only handle origin deletions. Also added NIG11 skip delete

- publishing/models/packaged_workbasket.py
- settings/common.py
The `publish_to_api` task is unable to publish envelopes to the Channel Islands. It expects the currently erroring envelope ID either to match the seed envelope ID (0001) or to be equal to the previous envelope ID + 1. Because of an issue detailed in TP2000-1157 together with the change in year (2023 -> 2024), the current envelope ID does not meet either of these conditions. 
- Use `HMRC_PACKAGING_SEED_ENVELOPE_ID` env variable as opposed to a hardcoded value in `next_expected_to_api()`, applying the value set in prod (until it can be amended in time for next year) or otherwise defaulting to 0001 as intended.
- Remove `int` conversion of `HMRC_PACKAGING_SEED_ENVELOPE_ID` env variable from settings so that it can be used to compare to an envelope ID (a str). The int conversion for this env …
> TP2000-1160 Fix publish_to_api task envelope ID error

- common/serializers.py
- common/tests/util.py
- exporter/tests/test_exporter_commands.py
- exporter/tests/test_exporter_tasks.py
- measures/tests/test_xml.py
- publishing/tests/test_tasks.py
- publishing/tests/test_util.py
- publishing/util.py
* A while back a PR contained a validation step for export that checked that record code + subrecord code were ordered within a transaction. There is no documentation about this requirement and upon research from EU data 95% + taric updates from the EU do not respect this ordering.
* Removing this check will still produce valid taric data and  it's unclear why this was initially introduced. 
* It is not a TARIC requirement for the records to be in sequential order. 
* Because of the way that goods nomenclature description periods are created (and other description periods) on export, if two description updates exist in the same transaction this issue will occur again because both the description and the description period are generated by one template, so we could easily end up with …
> TP2000-1161 : Update to remove validate_taric_xml_record_order as a requirement for export / publishing of TARIC data

- reports/jinja2/generics/export_report_to_csv.jinja
- reports/jinja2/reports/report_table.jinja
- reports/tests/test_report_views.py
- reports/urls.py
- reports/views.py
We want to allow users to export the data they can view in a report to a CSV file so they can manipulate it and build it out as they please
Integrating CSV package to the reports app to allow users to export the data. Exposing the endpoint via urls
> feat: Allow table reports to be exported as a CSV

- reports/reports/expiring_quotas_with_no_definition_period.py
- reports/tests/test_expiring_quotas_with_no_definition_period.py
Generating a report where a definition period on a quota is about to expire (in say five week times) and there isn't another future definition period
Create new report with similar logic to that of the Quota Missing Data report to capture this.
> feat: Quotas Definitions' That Are Expiring Soon

- Procfile
- docker-compose.yml
- manifest.yml
- measures/bulk_handling.py
- measures/views.py
- settings/common.py
Currently, bulk editing occurs within the context of a web worker. Because an edit can take many seconds and even minutes to complete, the confirmation web page presented to a user is bounded at the lower end by the amount of time an edit takes. It’s not the best approach to performing this type of computation for a number of reasons, including:
- Generally, users are accustomed to web pages loading in the order of milliseconds or a few seconds in the worst case, so a long delay is frustrating.
- Errors may be accumulate through spurious UI interaction with an in-progress creation process.
- Proxy server time-outs may occur during edit measure processing - the TAP team and SRE do not have the necessary access permissions to extend the proxy server’s timeout period.
This PR contains the …
> TP2000 1147 bulk edit celery task

- workbaskets/jinja2/includes/workbaskets/review-quota-blocking-periods.jinja
- workbaskets/jinja2/includes/workbaskets/review-quota-suspension-periods.jinja
- workbaskets/jinja2/includes/workbaskets/review-sub-quotas.jinja
- workbaskets/jinja2/workbaskets/review-quotas.jinja
- workbaskets/jinja2/workbaskets/review.jinja
- workbaskets/tests/test_views.py
- workbaskets/urls.py
- workbaskets/views/ui.py
Users are unable to review changes to sub-quotas, blocking periods and suspension periods on the workbasket review view.
- Adds new views and templates for sub-quotas, blocking periods and suspension periods nested review tabs
- Adds the nested review tabs under the quotas review tab
- Updates review view unit test
##
> TP2000-1168 Add sub-quota, blocking period & suspension period nested review tabs

- common/static/common/scss/_button.scss
- reports/jinja2/reports/report_chart_timescale.jinja
- reports/reports/expiring_quotas_with_no_definition_period.py
- reports/tests/test_report_views.py
- reports/urls.py
- reports/views.py
We don't currently have the functionality to export data for charts as we do for tables, this PR is here to implement the ability to export charts in either an excel format with a graph already built, or csv which will just be a table of all the data, which users can then turn into a chart easily in their preferred application.
Using openpyxl package and the csv import, I am writing two functions for the users to either:
- export to csv which is a simple writer of the data the report contains
- export to excel, using openpyxl to initialise a bar graph. In future if we start using other kinds of graphs, some more work will have to be done on this function to identify the type of graph and plot correctly.
> feat: Add both CSV and excel types for charts exporting

- reports/reports/base_table.py
- reports/reports/expiring_quotas_with_no_definition_period.py
- reports/reports/quotas_cannot_be_used.py
- reports/tests/test_report_utils.py
At the moment if a quota appears in the report (or its relevant dependants) its too difficult to figure out and track down why/create something to fix the quota and remove it from the report. So I'm adding in links to make it easier for users to click through and journey to the relevant part of TAP.
Creating a new versatile function that can be used across multiple reports that will navigate a user to the quota detail list and an optional argument to get them to a specific tab within this quota detail. Also adding some tests and updating a previous report I worked on to be more explicit about the model in which we're using.
> feat: implement URLs for quota reports to ease navigation

- measures/forms.py
- measures/views.py
MeasureFootnotesFormSet requires serialization support.
This PR:
- Moves the SerializableFormMixin above forms where it's required.
- Adds greater flexibility to selecting which keys are used from `Form.data` during serialization`.
- Add support for `MeasureFootnotesFormSet` serialization.
- Add support for `MeasureConditionsWizardFormSet` serialization.
> TP2000-1182 Serialize footnotes and conditions formsets

- common/serializers.py
- common/tests/test_serializers.py
- measures/forms.py
- measures/models.py
- measures/tests/test_forms.py
- measures/views.py
Complete support for serialization / deserialization of `MeasureConditionsWizardStepFormSet` required.
Support for serialization / deserialization of `MeasureCommodityAndDutiesFormSet` required.
Supporting capability for serializing dates and associated tests required.
Further refinement of form serialization is desirable.
Removal of debug / temporary test capability is desirable.
This PR:
- More flexible handling of form data key serialization. `SerializableFormMixin.ignored_data_key_regexs` is now used to represent the default list of keys that should be skipped.
- Adds `SerializableFormMixin.get_serializable_data_keys()` which is used to get the non-ignored data keys of a Form instance.
- Provides unit test for `SerializableFormMixin.get_serializable_data_keys()`.
- Adds supporting …
> TP2000-1179 Serialize commodities and duties formset

- taric_parsers/parsers/taric_parser.py
* urgent bugfix for production issue encountered.
* the changes have been tested and the issue is resolved.
What is this PR doing, e.g. implementations, algorithms, etc.?
* change the way that linked models are filtered, previously the current date was used to filter models validity, where in some circumstances this is not the correct approach, especially when origins and successors are redirecting goods that are also being end dated. The filter now takes the approach of using the most recent version of a model. 
- Requires dependency updates? No 
See: [Description](https://uktrade.atlassian.net/browse/TP2000-1210)
> update importer model matching to account for end dated objects.

- govuk_frontend_jinja/flask_ext.py
- govuk_frontend_jinja/templates.py
- requirements.txt
* https://github.com/LandRegistry/govuk-frontend-jinja got updated, and the commit we were pinned to for this project was removed. 
* The git commit we were pinned to was no longer available - the project won't build / deploy
What is this PR doing, e.g. implementations, algorithms, etc.?
* committed a copy of the code required into TAP and removed the git reference in requirements
- Requires migrations? No 
- Requires dependency updates? No 
See: [Description](https://uktrade.atlassian.net/browse/TP2000-1211)
> Tp2000 1211

- measures/forms.py
- measures/models.py
- measures/views.py
- settings/common.py
The geo areas wizard step's form data and kargs require serialization support.
This PR:
- Adds serialization support to the form used at the wizard geo areas step.
- Additionally, adds support to allow either synchronous or new asynchronous creation of measures. The is managed through the use of a feature flag, `MEASURES_ASYNC_CREATION`, that is set via an environment variable (though Vault when controlling the feature in production or a staging environment).
- Factors out some undocumented Form manipulation code into a class method that can be executed by a caller that is not an instance of `MeasureCreateWizard`. This allows consistently applying the wizard's form data from both web and Celery process contexts.
- Requires dependency updates?
> TP2000-1178 Serialize geo areas form

- .profile
- common/jinja2/common/maintenance.jinja
- common/jinja2/layouts/layout.jinja
- common/tests/test_views.py
- settings/common.py
The recent activation of maintenance mode raised the following errors:
1. `ImproperlyConfigured("settings.DATABASES is improperly configured. ")`
2. `AttributeError: 'WSGIRequest' object has no attribute 'user'`
1. Skips running python migrate command in the custom initialisation task script upon deployment since the database routes have been removed in maintenance mode
2. Disables `ProtectAllViewsMiddleware` in maintenance mode, preventing attempts to access the missing user attribute from the request object as a result of `AuthenticationMiddleware` being disabled too
> TP2000-1219  Prevent maintenance mode errors

- common/models/user.py
- workbaskets/forms.py
- workbaskets/views/ui.py
The queryset used to populate selectable users for workbasket user assignment includes inactive and duplicate user profiles. 
- Adds `.filter(is_active=True)` to the users queryset to filter out inactive users
- Adds `.distinct()` to prevent duplicate user objects being included in the queryset (users who belong to both TM and TM Lead user groups)
> TP2000-1226 Fix workbasket user assignment assignable users queryset

- Procfile
- common/jinja2/components/breadcrumbs.jinja
- common/models/user.py
- common/tests/test_models.py
- common/util.py
- manifest.yml
- measures/forms.py
- measures/jinja2/includes/measures/create-task-list.jinja
- measures/jinja2/measures/cancel-bulk-processor-task-done.jinja
- measures/jinja2/measures/cancel-bulk-processor-task.jinja
- measures/jinja2/measures/create-process-queue.jinja
- measures/models/__init__.py
- measures/tests/test_views.py
- measures/urls.py
- measures/views.py
- settings/common.py
Past experience of using Celery to perform asynchronous processing tells us that we should provide a means of cancelling tasks that "get stuck" or in some way fail, leaving tasks in an incomplete state.
This PR adds a journey, accessible to superusers from the measures process queue, that allows measures bulk creation tasks in one of the queued states to be cancelled. Specifically, this PR:
- Adds a view asking the user to confirm whether they would like to cancel a task.
- Adds a done view, displayed after a user has confirmed cancelling a task.
- Adds unit tests for views, testing scenarios with various combinations of processing state and user capability.
**Cancel process confirmation form**
**Cancel process done view**
> Tp2000-1243 Cancel task journey

- conftest.py
- measures/views.py
- publishing/tests/test_views.py
- workbaskets/models.py
- workbaskets/tests/test_models.py
- workbaskets/tests/test_views.py
- workbaskets/views/ui.py
We recently introduced the ability for users to be assigned workbaskets, where assignments are created using `UserAssignment` and `Task` models.
Separate from assigned workbaskets, users may have a `current_workbasket`. The method used to save a workbasket instance as the user’s current workbasket is `assign_to_user(self, user: User)`.
To avoid confusion between user assignments and current workbaskets, the method might be more suitably renamed.
- Renames all occurrences to `set_as_current()`
> TP2000-1250 Rename assign_to_user() to avoid confusion with user assignment

- workbaskets/tests/test_views.py
- workbaskets/views/ui.py
Users with the requisite permission are able to delete a workbasket with `EDITING` status once its `Transactions` and `TrackedModels` have been removed. However, a workbasket that has previously been assigned to a user will have a non-nullable `Task` instance associated with it, preventing deletion.
- Archives empty, previously assigned workbaskets, giving the appearance of workbasket deletion while preventing a `ProtectedError` from being raised
> TP2000-1249 Archive empty, previously assigned workbaskets upon deletion

- measures/filters.py
- measures/jinja2/measures/create-process-queue.jinja
- measures/tests/test_filters.py
- measures/views.py
The new Task Queue view page requires users to be able to filter tasks by `ProcessingState`
- adds functionality to filter for tasks which are Processing, ie. have a `ProcessingState` of `CURRENTLY_PROCESSING` or `AWAITING_PROCESSING`
- uses TamatoFilter to filter for the other states using the TamatoFilter
- tests that applying the filters displays the relevant task
Note: This PR has a work around for tasks which are Processing. We should investigate a refactor of/addition to the TamatoFilter that will allow querying using multiple parameters on the same filed, eg. a query of `?processing_state=AWAITING_PROCESSING&processing_state=CURRENTLY_PROCESSING` would return relevant tasks.
> TP2000-1119 List view filtering

- .gitignore
- certificates/tests/test_views.py
- certificates/views.py
- measures/filters.py
- measures/tests/test_filters.py
This PR addresses the UI side of an issue where when viewing measures connected to a certificate (via the related measure condition) some measures were missing. This is due to how versioning works in TAP and how we were retrieving the measures for a particular certificate. 
Simply for a particular certificate it's related `MeasureCondition` has a field `dependent_measure` which is a foreign key to a `Measure`. The `dependent_measure` connected to a `MeasureCondition` **DOES NOT** have to be the latest version of the measure but when we return measures we should returned the **latest** version of the `Measure`.
In a sketch:
```
measure v1 --- measure condition v1 --- certificate
measure v2 
```
As the above shows the measure condition has the relationship to the first version of the …
> TP2000-1101 Missing measures in certificate results fix

- common/jinja2/common/homepage.jinja
- common/tests/test_views.py
- common/views.py
The ‘Currently working on’ card, which details a user’s assigned workbaskets, is shown to all users with the ‘view workbaskets' permission. However, not all users who can view workbaskets can be assigned to them.
- Changes permission from 'can_view_workbasket' to 'can_edit_workbasket' (i.e 'workbaskets.change_workbasket') so that only the users who can be assigned to work on and to review workbaskets can see card
> TP2000-1255 Correct homepage card permission

- common/pagination.py
- common/static/common/js/openCloseAccordion.js
- measures/jinja2/includes/measures/list.jinja
- measures/jinja2/measures/list.jinja
- measures/pagination.py
- measures/views.py
Searching for measures using the end date filter can result in slow loading times and eventual timeouts: (1) calls to the view's paginator are duplicated many times over and (2) performing a `.count()` operation on a measure queryset chained with the filter `.with_effective_valid_between()` (added to enable filtering by end date) appear to be contributing to performance issues.
- Caches `limit_breached` and `count` paginator methods
- Caches the view's `paginator` property
- Evaluates the paginator's queryset to determine its length as a faster alternative to the slow count() operation (and without affecting non-end-date-filtered searches)
- Chains a `.select_related()` filter on the queryset to fetch objects used in the template
- Removes `object_list` from the view's context as the …
> TP2000-1236  Improve measure search performance

- reports/reports/expiring_quotas_with_no_definition_period.py
Requested by product manager, small change to add a new column to show users the quota's associated origins for the expiring soon report
Adding in a new element to the existing array in the python script that generates the expiring soon report
> feat: add origins to quotas expiring soon reports

- settings/common.py
The sqlite dump is scheduled to run at around 3am. This doesn’t coordinate well with the data workspace process timing to pick up the file, which runs at around 12am, while the dump currently take something in the order of 4:45 hours to complete.
Move the dump task to 7pm, allowing the dump time to run and complete before the data workspace process starts execution.
- Requires dependency updates?
> TP2000-1297 Change sqlite dump schedule

- common/jinja2/common/homepage.jinja
- common/jinja2/layouts/layout.jinja
- common/tests/test_views.py
Users need a way to easily navigating to the “Measures process queue”.
This PR:
- Adds a "Processing queues" card to the home page.
- Add a link to the "Measures process queue" page within the card.
- Adds explanatory text below associated link.
- Includes a check for the link in an existing unit test.
> TP2000-1289 Process queue link on home page

- reports/reports/base_table.py
- reports/reports/expiring_quotas_with_no_definition_period.py
- reports/views.py
For easability of report usage, we are allowing users to have a follow-through journey to the relevant geo area of related origins. CSV export was also giving the whole link values for both quota order number and quota origins so have fixed that.
Simple update of logic so picks up if the row is a link and only grabs the value using regex. Also adding a new function that renders a link for quota order number origins.
> feat: link geo areas to origins on expiring quotas report

- .gitignore
- Dockerfile
- Dockerfile.pytest
- README.rst
- checks/tests/test_checkers.py
- common/tests/util.py
- pyproject.toml
- requirements.txt
- runtime.txt
Platform migration requires a minimum of Python version 3.9.
This PR:
- Provides an initial, intermediate upgrade step unblocking other upgrade activities that require 3.9 or greater.
- Upgrades Python in Docker config files.
- Upgrades Python in Cloud Foundry config.
- Fixes module imports and requirements dependencies.
- Pins the set of Sphinxcontrib packages to the latest version requiring Sphinx versions less than version 5. This is because Sphinx does not pin its dependencies and Python version 3.9 or greater causes Sphinx's most recent dependencies to be used, which in turn pulls in Sphinx version 5. However, only one version of the dependent package govuk-tech-docs-sphinx-theme exists and it requires versions of Sphinx less than 5.
- Requires dependency …
> TP2000-1279 Upgrade to Python version 3.9

- common/jinja2/common/homepage.jinja
- common/static/common/js/application.js
- common/static/common/js/masonry.js
- common/static/common/scss/_components.scss
Gaps in between cards on the homepage can appear inconsistently sized depending on which cards are conditionally displayed and whether the "Currently working on" card adjusts its height to fit content.
- Uses JavaScript to adjust out-of-position cards in the masonry layout to ensure a consistent margin no matter the permutation or size of homepage cards.
> TP2000-1324 Fix homepage card masonry layout

- common/jinja2/common/maintenance.jinja
- common/tests/test_views.py
The recent activation of maintenance mode raised an unhandled `UndefinedError ('WSGIRequest object' has no attribute 'user')` that prevented the custom maintenance mode page from being displayed.
- Extends `_generic.jinja` instead of `layout.jinja` to ensure `maintenance.jinja` no longer inherits references that rely upon accessing the user attribute of a request object (which has been removed in maintenance mode).
- Updates the maintenance mode unit test to provide coverage for this scenario.
> TP2000-1338 Prevent maintenance mode UndefinedError exception

- common/celery.py
- docker-compose.pytest.yml
- docker-compose.yml
- requirements-dev-jupyter.txt
DBT Platform migration requires Celery worker health check support from host environments.
This PR:
- Exposes a health check interface with the help of DBT's Copilot library.
- Adds a `healthcheck` section to each Celery service, including test and timing details.
In addition to health check capabilities, the PR splits out docker-compose pytest support into its own `docker-compose.pytest.yml` file, allowing the web service to be easily started without also running unit tests.
- Requires dependency updates? Yes, if you rely upon the `requirements-dev-jupyter.txt` file for Jupyter support.
> TP2000-1298 Celery health check support

- Dockerfile.pytest
- common/tests/test_migrations.py
The following commands fail when executed in a development environment:
1) `$ pytest common/tests/test_migrations.py::test_missing_current_version_fix`
2) `$ pytest common/tests/test_migrations.py::test_timestamp_migration`
3) `$ docker-compose --file docker-compose.pytest.yml up --build pytest`
-  Passes the `ID` of the transaction as a foreign key value to create the measurement unit.
- Uses `DateTimeTZRange` to set the valid_between values of the tracked models to match the column's expected data type.
- Creates the factories in `test_timestamp_migration` using the current DB state based on the applied migration.
- Adds support for `amd64` node binary package in `Dockerfile.pytest`
###
> TP2000-1325 Fix failing migration unit tests in dev environment

- taric_parsers/parsers/commodity_parser.py
* Updates import key identity fields for GoodsNomenclatureDescriptionV2 for the importer so that it also matches on the SID which is actually the description periods SID but for matching this works. 
* Import failed for TGB24095 due to multiple object matches, the importer needs updating to better identify the correct record in this specific scenario. 
* Updates import key identity fields for GoodsNomenclatureDescriptionV2 for the importer so that it also matches on the SID which is actually the description periods SID but for matching this works. 
- Requires migrations? No 
See: [Jira](https://uktrade.atlassian.net/browse/TP2000-1353)
> Update importer V2 to handle issues raised from TGB24095 (multiple matches on GoodsNomenclatureDescription

- common/jinja2/components/measure_condition_action_code/template.jinja
- common/jinja2/components/measure_condition_code/template.jinja
- common/jinja2/components/measure_condition_component_duty/template.jinja
If the measure conditions form in the measure creation journey contains validation errors, an empty form, cleared of all previously submitted data, is redisplayed to the user making it so all form data has to be re-inputted.
- Adds a conditional expression to display the form field's submitted data if it exists (otherwise fallback to the field's initial value which may be an empty value) to the templates used to display the form's fields.
> TP2000-1379 Redisplay measure conditions form data on validation error

- Procfile
- docker-compose.yml
- exporter/management/commands/dump_sqlite.py
- settings/common.py
`ValueError` log entries are created by the Celery Beat process. A component of Celery configuration is overriding the 'celery' logger's log level. This PR is a first attempt at helping with issue investigation.
This PR:
- Sets the log level of the Beat process to `info` via a command line flag, making the Beat process consistent with other Celery processes.
- Enables the Beat process `sqlite_export` schedule to be set from config rather than hard coded, allowing flexible configration when testing in different environments (including Docker).
> TP2000-1381 Celery logging config error pt.1

- measures/forms.py
- measures/tests/test_forms.py
- measures/tests/test_views.py
- measures/views.py
The measure end date form in the bulk measure editing journey requires an end date otherwise it raises a validation error, preventing end dates from being removed.
- Refactors both `MeasureStartDateForm.clean()` and `MeasureEndDateForm.clean()` as the forms already normalise their respective field data to a datetime object
- Adds `required=False` to the `end_date` field on `MeasureEndDateForm` to allow empty values to be submitted
- Makes `MeasureEndDateForm` set its end date cleaned data to `None` if no end date was inputted
- Changes how `MeasureEditWizard.done()` gets the new start/end date for the edited measures
- If end date key is in cleaned data, then use its value to set as the new end date (even if the value is `None` as that means the end date is intended to be removed)
- If …
> TP2000-1384 Allow end dates to be removed when bulk editing measures

- common/models/transactions.py
- common/tests/factories.py
- common/tests/test_querysets.py
There is no direct capability to filter only published transactions - those that have been approved and are associated with a PUBLISHED workbasket. Having a filter to narrow down transactions to those that are published is required by TP2000-1389.
This PR provides part of the solution to fixing issue TP2000-1389, by allowing the sqlite dump process to check for "published" transactions. (Additional filtering capability is required on `TrackedModel`s to include only those that have been "published" when accumulating data for inclusion in the sqlite dump.)
Specifically, this PR:
- Adds a new `TransactionQueryset.published()` queryset filter.
- Adds a new `EditingWorkBasketFactory` factory.
- Unit tests the newly added filter.
> TP2000-1389 Add published() filter to TransactionQueryset

- quotas/jinja2/includes/quotas/tabs/core_data.jinja
- quotas/models.py
- quotas/tests/test_models.py
- quotas/views.py
An origin that should be associated to quota order number 058801 doesn't appear on the quota's detail view nor does it appear as an existing origin when editing the quota.
- Changes the queryset to find current/existing origins using the order number SID not PK as a way to catch associations that may have been lost when a quota's version has changed
> TP2000-1403  Fix missing quota origin associations

- common/jinja2.py
- common/jinja2/common/app_info.jinja
- common/models/tracked_qs.py
- common/models/transactions.py
- common/static/common/scss/_text.scss
- common/tests/factories.py
- common/tests/test_querysets.py
- common/tests/test_views.py
- common/util.py
- common/views.py
- exporter/sqlite/plan.py
- exporter/sqlite/tasks.py
- exporter/sqlite/util.py
- exporter/tests/test_sqlite.py
Approved transactions are used to determine whether the sqlite dump process should be run and also to create the data for those dumps. This is incorrect because approved transactions include queued, unpublished transactions. Only transactions that are approved **and** associated with a workbasket in PUBLISHED status should be used.
There is also poor visibility of the most recent sqlite dump files in S3. This makes it unnecessarily difficult to identify when problems occur with sqlite dump creation.
This PR:
- Adds a custom queryset filter `TrackedModelQuerySet.published()` to retrieve `TrackedModel` instances associated with approved Transactions and workbaskets that are have PUBLISHED status.
- Adds unit tests for the new `TrackedModelQuerySet.published()` filter.
- Extends unit test …
> TP2000-1389 Restrict sqlite dump to published only

- common/jinja2/common/homepage.jinja
- common/tests/test_views.py
- common/views.py
TP2000-1382 Change workbasket id to tops number in the list of workbaskets assigned to the current user
The user does not immediately recognised the workbasket ID, and prefers to see the description.
> TP2000 1382 change workbasket id to tops number

- conftest.py
- measures/duty_sentence_parser.py
- measures/forms.py
- measures/jinja2/includes/measures/macros/duty_amount.jinja
- measures/tests/test_forms.py
- measures/tests/test_lark_parser.py
- measures/tests/test_views.py
The measure conditions form doesn't currently take full advantage of the new duty sentence parser because the 
the reference price field doesn't permit compound duties and the parser cannot be limited to simple duties.
- Adds `compound_duties: bool` attribute/param to duty sentence parser, which determines the start symbol of the grammar used by the parser instance so that parsing can be limited to ad valorem and specific duties only (if required)
- Hooks up new duty sentence parser in `MeasureConditionsFormMixin.conditions_clean()` to parse and validate duties inputted in the reference price field of the measure conditions form
- Fixes the display of condition duties both on the measure review view and on the measure detail view conditions tab to measurement units
- Updates unit tests …
> TP2000-1378  Add option to new duty sentence parser to limit parsing to simple duties

- README.rst
- common/fields.py
- common/tests/test_migrations.py
- common/util.py
- measures/tests/test_migrations.py
- pyproject.toml
- requirements.txt
- setup.py
- taric_parsers/tests/commoditiy_parsers/test_footnote_association_goods_nomenclature_parser.py
A new major version (3) of the psycopg Python package was released some years ago. The previous version (2), currently used by Tamato, is now relatively inactive and should be replaced by the current, active version, allowing Tamato to take advantage of optimisations and fixes.
In this PR:
- Bump psycopg version numbers in config, docs and settings.
- Swap to using equivalent date types introduced by psycopg 3.
- Correctly handle new `value` param behaviour in `Model.from_db_value()` as a result of new psycopg behaviour.
- Update test to use pscopg 3's changed exception message.
- Requires dependency updates? Yes
> TP2000-1262 upgrade psycopg package

- common/forms.py
- common/jinja2/layouts/confirm.jinja
- quotas/forms.py
- quotas/jinja2/includes/quotas/actions.jinja
- quotas/jinja2/quota-suspensions/confirm-create.jinja
- quotas/jinja2/quota-suspensions/create.jinja
- quotas/tests/test_forms.py
- quotas/tests/test_views.py
- quotas/urls.py
- quotas/views.py
- requirements.txt
There is currently no way to create quota suspension or blocking periods in the UI.
- Adds `QuotaSuspensionOrBlockingCreate` view & form
- Adds `QuotaSuspensionConfirmCreate` & `QuotaBlockingConfirmCreate` views
- Links to the create form on the actions menu on the quota detail view
- Adds view and form unit tests
---
---
---
---
> TP2000-1402  Implement journey to create quota suspension or blocking periods

- common/tests/test_util.py
- common/util.py
- importer/forms.py
- requirements.txt
External entity expansion hasn't been disabled when calling `etree.parse()` within `parse_xml()`.
- Bumps `lxml` to 5.2.2 (latest version), which no longer expands external entities by default as of version 5.0.0
- Explicitly disables entity expansion in `parse_xml()` and `xml_fromstring()`
- Uses `werkzeug.utils.secure_filename` to validate the file name of uploaded taric files to guard against path traversal
- Updates unit tests
- Requires dependency updates? **Yes**
> TP2000-1268  Resolve XML external entity expansion alert

- measures/views.py
- publishing/views.py
Some redirect URLs may incorporate unvalidated user input.
- Uses string concatenation instead of f-string formatting to form the redirect URL in `MeasureList.form_valid()` to compensate for false positive alert (see comment in [UrlRedirectCustomizations.qll](https://github.com/github/codeql/blob/main/python/ql/lib/semmle/python/security/dataflow/UrlRedirectCustomizations.qll#L103))
- Replaces `request.build_absolute_uri()` with functionally equivalent calls to `reverse(viewname)` in both `EnvelopeQueueView` and `PackagedWorkbasketQueueView`
> TP2000-1270  Resolve URL redirection from remote source alerts

- footnotes/views.py
An uncaught `MultipleObjectsReturned` exception is raised on the measures tab of the footnote detail view if a footnote has multiple versions.
- Chains `current()` to the queryset to get the latest version of the footnote
> TP2000-1443 Fix MultipleObjectsReturned error on Footnote measures tab

- workbaskets/views/ui.py
Uncaught exceptions are raised and a generic server error page is displayed when attempting to access the workbasket checks view (`/workbaskets/current/checks/`) or workbasket violations view (`/workbaskets/current/violations/`) without a current workbasket.
- Uses `require_current_workbasket` decorator on both `WorkBasketsChecksView` and `WorkBasketsViolations`, redirecting users without a current workbasket to the `NoActiveWorkbasket` view, where users are invited to create or select a new workbasket (like other views that require a current workbasket do)
> TP2000-1444 Require a current workbasket on workbasket checks and violations views

- measures/forms.py
- measures/tests/test_bulk_processing.py
* Bug was missed on last code merge due to missing test coverage
* Changes MeasureGeographicalAreaForm.deserialize_init_kwargs back to a class method
* Adds missing test coverage for MeasuresBulkCreator.get_forms_cleaned_data
> Fix measure bulk create error

- common/tests/test_validators.py
- common/util.py
- common/validators.py
- importer/forms.py
- measures/tests/test_views.py
The filenames of TARIC files uploaded in the importer form could use some validation and sanitisation.
- Adds two new functions, `validate_filename` and `validate_filepath`, that can be used to guard against malicious filenames and path traversal attacks
- Validates the filename of uploaded TARIC files
- Sanitises the name used to create an `ImportBatch` based on the uploaded TARIC file
> TP2000-1269 Resolve uncontrolled data used in path expression alert

- .pre-commit-config.yaml
- common/util.py
- publishing/jinja2/includes/envelope-queue.jinja
- publishing/jinja2/includes/packaged-workbasket-queue.jinja
- publishing/models/packaged_workbasket.py
- publishing/tests/test_models.py
- publishing/views.py
A race condition can occur during concurrent requests to create/promote/demote/process packaged workbaskets, resulting in duplicate or non-contiguous queue positions that stop the queue from functioning.
- Uses [select_for_update()](https://docs.djangoproject.com/en/4.2/ref/models/querysets/#select-for-update) queryset operation to lock affected packaged workbasket rows while queue position are being updated
- Makes queue position update queries non-blocking (`nowait=True`), catching the raised exception if a conflicting lock is already acquired
- Returns early without updating queue positions if the selected packaged workbasket is no longer a queue member (position=0)
- Prevents accidental double-clicking of buttons in the packaging queue
<details><summary>Shared queue positions after …
> TP2000-1434 Prevent packaging queue race conditions

- common/static/common/js/components/GeoAreaForm/ErgaOmnesForm.js
- common/static/common/js/components/GeoAreaForm/GeoAreaField.js
- common/static/common/js/components/GeoAreaForm/index.js
- common/static/common/js/components/GeoAreaForm/tests/index.test.js
- measures/jinja2/includes/measures/geo_area_script.jinja
- measures/views/wizard.py
* Jersey and Guernsey are not part of the erga omnes geo area group. This prevents users from selecting them as exclusions and causing an error
* Passes the list of erga omnes members to the react component as a new prop to populate the select options
> TP2000-1458: Limit erga omnes exclusions to erga omnes group members

- settings/common.py
Migration to DBT Platform moves performance telemetry capture from Grafana to Sentry.
Support enabling Sentry tracing and trace sampling rate via the environment variables `SENTRY_ENABLE_TRACING` and `SENTRY_TRACES_SAMPLE_RATE`, respectively. The values loaded from these variables (with sensible default parameters to support current platform) are passed into the `sentry_sdk.init()` function via `enable_tracing` and `traces_sample_rate`.
> TP2000-1461 Enable Sentry tracing

- scripts/web-worker-entrypoint.sh
- wsgi.py
OTEL is no longer in use, this was also causing an issue where the application was hanging
Only on DBT Platform is this configuration implemented, remove this.
> Remove unused OTEL configuration

- commodities/jinja2/includes/commodities/tabs/hierarchy.jinja
- commodities/tests/test_views.py
- commodities/views.py
The commodity code hierarchy tree in the Commodity Codes view, currently shows commodity codes that are no longer active (have been end dated)
TAP should only show “live” or Commodity Codes that either:
- Don’t have an end date or,
- Have an end date greater than todays date.
Commodity code hierarchy has been corrected to:
- not include end dated commodities
- not display at all if you're viewing it for an end dated commodity
> TP2000-1465 Have commodity hierarchy only show active comm codes

- quotas/tests/test_views.py
- quotas/views.py
Resolves an issue where, if a user duplicates a QuotaDefinition in a fresh workbasket, it will be associated with the last transaction, rather than creating a new transaction.
Adds a `workbasket` property to the `QuotaDefinitionDuplicatorWizard`
Assigns the transaction for `models.QuotaDefinition.objects.create()` and `models.QuotaAssociation.objects.create()` as `self.workbasket.new_transaction`
Refactors the QuotaAssociation creation to take place within the `create_definition()` function.
> Bugfix-QuotaDefinition duplicator transaction

- quotas/forms.py
- quotas/jinja2/includes/quotas/actions.jinja
- quotas/jinja2/quotas/definitions.jinja
- quotas/jinja2/quotas/tables/definitions.jinja
- quotas/jinja2/quotas/tables/sub_quotas.jinja
- quotas/tests/test_views.py
- quotas/urls.py
- quotas/views.py
Currently the View Definition Periods view allows a user to view definition periods by default. If a user wants to view associations, blocking and suspension periods, they need to select the option via a radio button in a hidden menu. This is a legacy practice from a previous iteration of TAP. Instead we should show the various options as tabs.
This PR:
- replaces the old radio button form on the view definitions page with tabs
- adds a test
> TP2000-1474 Amend view definition periods

- publishing/models/crown_dependencies_envelope.py
- publishing/tests/test_model_crown_dependencies_envelope.py
When a `CrownDependenciesEnvelope` fails to be published, its `publishing_state` is transitioned to `FAILED_PUBLISHING`. If that envelope fails to be published once more, a `TransitionNotAllowed` exception is raised. While this unhandled exception alone does not prevent an envelope from being published, it can obscure the real cause of the publishing failure.
- Adds `FAILED_PUBLISHING` as a valid source state in the `publishing_failed()` transition method on the `CrownDependenciesEnvelope` model
- Adds a unit test for the transition methods
> TP2000-1495 Prevent CrownDependenciesEnvelope TransitionNotAllowed exception.

- quotas/forms.py
- quotas/serializers.py
In `deserialize_definition_data`, the values for `initial_volume` and `volume` were assigned incorrectly.
Correctly assigns the relevant volume values.
Adds help text to the volume fields.
> Fix for flipped volume and initial_volume

- reference_documents/tests/test_preferential_quota_order_number_forms.py
The unit test `test_clean_coefficient_no_main_order` in `reference_documents/tests/test_preferential_quota_order_number_forms.py` failed following a recent merge to master.
A `ReferenceDocument` object had attempted to be created with an `area_id` matching an existing `ReferenceDocument` object, raising an `IntegrityError`: `duplicate key value violates unique constraint "reference_documents_referencedocument_area_id_key". DETAIL:  Key (area_id)=(PX) already exists.`
In the test, the `ReferenceDocument` objects are created indirectly via ` PreferentialQuotaOrderNumberFactory()`'s sub-factories. `ReferenceDocument.area_id` is generated randomly from $26^2$ possible combinations.
- Removes superfluous call to `PreferentialQuotaOrderNumberFactory()` in the test, removing the possibility of …
> TP2000-1498 Fix intermittent unit test failure

- common/forms.py
- common/jinja2/layouts/create.jinja
- common/static/common/js/components/QuotaOriginFormset/index.js
- common/static/common/js/components/QuotaOriginFormset/tests/__snapshots__/index.test.js.snap
- common/static/common/js/components/QuotaOriginFormset/tests/index.test.js
- quotas/forms.py
- quotas/jinja2/includes/quotas/quota-create-origins.jinja
- quotas/tests/test_forms.py
- quotas/tests/test_views.py
- quotas/views.py
* Fixes a workbasket transaction error caused by trying to update a quota and origins after creating a quota and origins in different transactions
* Brings the create form in line with the edit form
* Reuses the react quota origins and exclusions form used on the quota edit page and adds it to the quota create page as well
* More tests to improve coverage
> TP2000-1352: Add react origins form to quota create page

- quotas/business_rules.py
- quotas/forms.py
- quotas/tests/test_forms.py
- quotas/tests/test_views.py
- quotas/views.py
If a definition period for either the main or sub quota in an association is deleted, then the association object must also be deleted in that same transaction.
This PR:
- updates the definition delete view to also delete any linked associations in the same transaction
- adds a test
- updates QA6 so it doesn't fail when an association gets deleted as there aren't any left
> TP2000-1515 Deleting definition deletes association too

- quotas/jinja2/quota-associations/confirm-delete.jinja
- quotas/jinja2/quota-associations/delete.jinja
- quotas/jinja2/quotas/tables/sub_quotas.jinja
- quotas/tests/test_views.py
- quotas/urls.py
- quotas/views.py
There is a requirement for TMs to be able to delete a QuotaAssociation between two QuotaDefinitions while maintaining the QuotaDefinitions
This PR follows the standard Delete journey, enabling a TM to delete a QuotaAssociation object without deleting either the main or sub-quota definition:
- Adding a Delete link in the Sub-quotas view (image 1 below)
- Following the standard delete journey (images 2 & 3)
- Adding tests
There are some minor copy changes as requested by Ash/Rachel during an initial review:
- On the Quota Data/sub-quotas page: changing table headings from `Quota definition sid` to `Quota definition SID` and `Relation type` to `Relationship type`
Note: on the confirm delete page, we currently link back to the sub-quota definition. Once this ticket is in production, should …
> Tp2000 1516 delete quota association

- common/jinja2/layouts/detail.jinja
- quotas/jinja2/includes/quotas/actions.jinja
- quotas/jinja2/includes/quotas/tabs/blocking_periods.jinja
- quotas/jinja2/includes/quotas/tabs/core_data.jinja
- quotas/jinja2/includes/quotas/tabs/definition_details.jinja
- quotas/jinja2/includes/quotas/tabs/measures.jinja
- quotas/jinja2/includes/quotas/tabs/sub_quotas.jinja
- quotas/jinja2/includes/quotas/tabs/suspension_periods.jinja
- quotas/jinja2/quota-definitions/sub-quota-definitions-updates.jinja
- quotas/jinja2/quotas/definitions.jinja
- quotas/jinja2/quotas/detail.jinja
- quotas/jinja2/quotas/tables/definitions.jinja
- quotas/jinja2/quotas/tables/sub_quotas.jinja
- quotas/tests/test_views.py
- quotas/views.py
Implement updates to the QuotaDetail and QuotaDefinitionList 
- Adding a title caption based on the quotas' status as a main or sub-quota
- Displaying main and sub-quotas on relevant tabs
- Add an action column with Edit/Delete columns on the Quota data view
- Change tab title from `Sub-quotas` to `Quota associations`
- Further changes as requested by UR team as detailed on ticket 1517, including changes to Actions column as requested by @SteveCN7
> Tp2000 1517 implement improved quota views for users

- common/forms.py
- common/jinja2/common/delete.jinja
- quotas/forms.py
- quotas/jinja2/quota-suspensions/confirm-delete.jinja
- quotas/jinja2/quota-suspensions/confirm-update.jinja
- quotas/jinja2/quota-suspensions/delete.jinja
- quotas/jinja2/quota-suspensions/edit.jinja
- quotas/jinja2/quotas/tables/suspension_periods.jinja
- quotas/models.py
- quotas/tests/test_forms.py
- quotas/tests/test_views.py
- quotas/urls.py
- quotas/views.py
- Users can create a suspension periods for quotas, but they can’t edit existing periods. This allows editing so that it can be done by the user and not data engineers.
This PR:
- implements edit capability for quota suspension periods including the update, edit-update and edit-create journeys
- implements the ability to delete quota suspension periods
- adds form and view tests
- moves _Cancel_ button from generic delete from from template to form so it can be inline with the delete button
---
---
---
> TP2000-1477 Edit capability for suspension periods

- commodities/tests/test_views.py
- commodities/views.py
The commodity code hierarchy currently shows all versions of commodities. Therefore if one has multiple versions it will appear multiple times in the tree which is incorrect.
This PR:
- adds current_only so only current commodities are shown
- adds a test to account for this
> TP2000-1501 Fix comm code hierarchy bug

- common/tests/test_models.py
- quotas/jinja2/includes/quotas/tabs/sub_quotas.jinja
- quotas/jinja2/quotas/tables/sub_quotas.jinja
- quotas/views/definitions.py
There are some issues with the current quota association view:
- it errors if someone loads the page without a workbasket
- if a sole definition has been edited in the workbasket, it currently links to an update-edit form which errors - as while an update-edit would be appropriate for the definition this does not work for the unedited association
- there is an edit link for main quota associations which doesn't reflect where the link goes (currently to the edit page of whatever the most recently edited sub quota was)
This PR:
- adds require_workbasket_decorator to quota definition list view to catch and redirect anyone without a workbasket
- removes the actions column (thus edit link) for main quota associations since the form in question only handles sub quota association edits
- ensures …
> TP2000-1562 Quota association view update

- tasks/jinja2/tasks/includes/task_queue.jinja
- tasks/jinja2/tasks/macros/item_actions.jinja
- tasks/jinja2/tasks/macros/reorder_actions.jinja
- tasks/jinja2/tasks/workflows/template_detail.jinja
- tasks/models/workflow.py
- tasks/static/tasks/scss/_tasks.scss
- tasks/tests/test_views.py
- tasks/views.py
Users require the ability to reorder task templates within a workflow template.
- Adds new macro to display move up/down buttons  for reordering task templates
- Overrides `TaskWorkflowTemplateDetailView.post()` to handle template reordering form actions
> TP2000-1545  Add task template reordering capability to workflow template detail view

- common/static/common/js/components/QuotaOriginFormset/QuotaOriginForm.js
- common/static/common/js/components/QuotaOriginFormset/tests/__snapshots__/index.test.js.snap
- common/static/common/js/components/QuotaOriginFormset/tests/index.test.js
- common/static/common/scss/_quota-definitions.scss
- quotas/constants.py
- quotas/forms/react_forms.py
- quotas/forms/wizards.py
- quotas/jinja2/includes/quotas/quota-create-origins.jinja
- quotas/jinja2/quota-definitions/sub-quota-definitions-selected.jinja
- quotas/jinja2/quota-definitions/sub-quota-duplicate-definitions-start.jinja
- quotas/views/wizards.py
- workbaskets/jinja2/workbaskets/edit-workbasket.jinja
To maintain consistency across TAP we should remove the accordions from the quota create journey.
We should also make other content changes to the Create quota associations journey for a better user experience.
This PR:
- Removes accordions from the create quota journey and makes some minor content updates
- Makes content updates to the Create associations journey - renaming steps, updating help text and adding styling to the table
-
> TP2000 1570 & 1571 Update quota create layout and quota content changes

- quotas/forms/definitions.py
- quotas/jinja2/includes/quotas/tabs/sub_quotas.jinja
- quotas/jinja2/quotas/tables/sub_quotas.jinja
- quotas/tests/test_views.py
- quotas/views/definitions.py
At the moment, a current workbasket is required to view the quota definition data page. This is because the association list view needs to check current updates in order to display the latest data if a quota definition was updated.
This is not ideal as detail views should not mandate a workbasket. Some stakeholders like HMRC may want to view this page and won't have one.
This ticket solves that issue by ensuring that whenever a quota definition is updated, an updated association object is created too. This ensures that associations listed all point to updated quota definitions and show the latest data rather than previously when unedited associations were pointing to old instances of quota definitions.
This PR:
- removes the current workbasket requirement for the quota definition list …
> TP2000-1565 Create an association update object when definition updated

- common/jinja2/common/homepage.jinja
* At the moment, there is no straight forward navigation to task workflow related pages for non-dev users
* As task workflow functionality increases, there needs to be an easier way for non-dev users to find and view task workflow related pages
* A new TEMPORARY navigation tile has been added to the homepage which links to tasks list views
* WorkflowTemplates list view is WIP so '#TODO' has been set as a placeholder
- Requires migrations? - No
- Requires dependency updates? - No
> Tp2000 1589  - temporary list views tile

- tasks/migrations/0012_taskworkflow_assign_summary_task.py
- tasks/models/workflow.py
- tasks/tests/test_workflow_models.py
The [task-workflow megabranch](https://github.com/uktrade/tamato/pull/1298) has a failing test following changes to `TaskWorkflow` model: `tasks/tests/test_workflow_models.py::test_create_task_workflow_from_task_workflow_template`
- Adds `summary_data` param to `TaskWorkflowTemplate.create_task_workflow()` to populate the details of the `TaskWorkflow.summary_task` instance (since it has become a required field), replacing the old way of using the workflow template's title and description
- Updates unit test based on the above change
- Fixes application of `tasks/migrations/0012_taskworkflow_assign_summary_task.py` by saving the modified object instances in the forward migration operation
- Requires migrations? Yes
> Update TaskWorkflowTemplate.create_task_workflow() method and unit test

- tasks/views.py
Both `TaskWorkflowDetailView` and `TaskWorkflowTemplateDetailView` share common logic for handling queue item reordering that could be factored out into a mixin.
- Adds a new mixin, `QueuedItemManagementMixin` providing helper functions for promoting/demoting queue items
> Refactor TaskWorkflow & TaskWorkflowTemplate detail views

- tasks/views.py
The unit test `test_workflow_template_create_view` is currently failing.
This PR overrides `TaskWorkflowTemplateCreateView.form_valid()` so that the required `user` parameter can be included in the call to `form.save()`.
> Include user param in form.save() call

- conftest.py
- measures/duty_sentence_parser.py
- measures/tests/test_lark_parser.py
- measures/tests/test_util.py
Entering the duty sentence `9.10% MAX 1.00% + 0.90 GBP / 100 kg`  in the Commodities & Duties step of the Create Measures journey raises the following form error: `Duty expressions must be used in the duty sentence in ascending order of SID`. 
- Removes the matched duty expression SID in addition to SIDs of a lower order when tracking applicable duty expressions, ensuring expressions are applied in ascending SID order:
- For example, the duty expression SID order for the above parsed duty sentence was showing as 1, 17, 4; 
- The new SID order would be applied as 1, 17, 19
- Refactors duty sentence parser related fixtures and tests catering for duty expression SID ordering
- Modifies both `plus_percent_or_amount` and `maximum` fixtures to return a list of objects for each possible SID
- …
> TP2000-1584  Fix duty sentence parser error with MAX expression

- quotas/jinja2/includes/quotas/tabs/sub_quotas.jinja
- quotas/jinja2/quota-associations/delete.jinja
- quotas/models.py
- quotas/views/base.py
Issues identified:
- When viewing the measures tab on a quota order number details view. The user should be able to see newly created measures. This normally involves using the .current method, rather than latest approved transaction.
- There are 2 cancel buttons on the delete association page and one doesn't work
This PR:
- update the measures tab on quotas to include draft measures (.current()) as well are future measures (.as_at_today_and_beyond())
- Removes the second cancel button from the association edit page
- Overrides get_url() for QuotaAssociation objects to ensure the cancel button redirects to the right page (previously it was going nowhere)
> TP2000-1596 Quotas - small fixes

- workbaskets/models.py
User testing of the auto end-dating measures in UAT found that the page times out with a 504 error. This does not happen locally but it can take about 15 seconds to load.
This PR moves the .effective_valid_between() part of the function to the end so that it is applied on the final smallest queryset. As this is the most time consuming bit of the query it reduces the time to load the page.
> TP2000-1503-speed-up-auto-end-measures

- additional_codes/tests/test_business_rules.py
- certificates/tests/test_business_rules.py
- commodities/tests/business_rules/test_NIG11.py
- commodities/tests/business_rules/test_NIG5.py
- commodities/tests/business_rules/test_NIG5_origin.py
- commodities/tests/test_business_rules.py
- common/tests/test_business_rules.py
- footnotes/tests/test_business_rules.py
- geo_areas/tests/test_business_rules.py
- measures/tests/test_business_rules.py
- measures/tests/test_business_rules/test_ME16.py
- measures/tests/test_business_rules/test_ME32.py
- measures/tests/test_business_rules/test_ME67.py
- pyproject.toml
- quotas/business_rules.py
- quotas/tests/test_business_rules.py
- regulations/tests/test_business_rules.py
- requirements.txt
* Add pytest mark to all business rules for easier testing business rules in isolation 
* Add test to check deleted associations are not being incorrectly checked
* Update QA5 
* The rule incorrectly raised rule violations 
* No test checked that deleted associations were not being checked
* Update QA5 
* Test to verify the rule is operating correctly
See: [Description](https://uktrade.atlassian.net/browse/TOPS-1874)
> Updates to QA5 to prevent False positives from deleted associations

- measures/jinja2/includes/measures/conditions.jinja
- measures/jinja2/includes/measures/list.jinja
- measures/jinja2/includes/measures/workbasket-measures.jinja
- measures/views/search.py
- workbaskets/jinja2/workbaskets/compare.jinja
HMRC users noticed they could not see conditions and footnotes on measures in workbasket 2020.
This was because it was filtering current conditions by current workbasket rather than the workbasket they were viewing.
This PR:
- Updates conditions_list macro so that it takes a workbasket argument. This allows specification of whether the current conditions should be queried in the current workbasket or another one (in this case if you're reviewing measures in workbasket X, workbasket X will not necessarily be your current workbasket)
- passes workbasket argument in places conditions_list is used - that is, review measures tab, measures search and worksheet checker
> TP2000-1625 Measure conditions and footnotes not showing on review measures

- measures/forms/mixins.py
- measures/tests/conftest.py
- reference_documents/tests/test_ref_quota_definition_range_forms.py
- reference_documents/tests/test_ref_quota_definition_ranges_model.py
A few unit tests have begun to fail because of hardcoded dates.
<details><summary>Examples</summary>
<p>
```
FAILED measures/tests/test_forms.py::test_formset_measure_forms_serialize_deserialize[conditions_form] - AttributeError: 'NoneType' object has no attribute 'filter'
FAILED measures/tests/test_forms.py::test_formset_measure_forms_serialize_deserialize[commodities] - AttributeError: 'NoneType' object has no attribute 'filter'
FAILED reference_documents/tests/test_ref_quota_definition_range_forms.py::TestRefQuotaDefinitionRangeCreateUpdateForm::test_clean_start_year[0-Start year is not valid, it must be a 4 digit year greater than 2010 and less than 2124] - AssertionError: assert ['Start year ...ss than 2125'] == ['Start year ...ss than 2124']
At index 0 diff: 'Start year is not …
```
> TP2000-1636 Fix date-related failing unit tests

- publishing/management/commands/publish_to_api.py
- publishing/models/packaged_workbasket.py
- publishing/tests/test_publishing_commands.py
- settings/common.py
Tamato is failing to publish new envelopes, beginning with this new year’s 25xxxx envelope ID naming pattern, to the tariffs-api service. This is because the last envelope of 2024 was rejected but was still being considered as the last published envelope.
This PR:
- Makes a bare call to Tamato's `publish_to_api` Django management benign. Instead of performing a publishing action it now lists (with additional detail) the envelopes that are awaiting publishing to tariffs-api.
- Adds the `--publish-now` and `--publish-async` flags to `publish_to_api`. The former now runs the publishing process in the context of the console session, allowing an engineer to immediately see logs. The latter performs the publishing action asynchronously.
- Changes a function name from …
> TP2000-1639 new year envelope publishing failure

- quotas/forms/base.py
When users create a new suspension or blocking period, sometimes they cannot see any/all of the quota's definitions in the dropdown on the form.
This is because the form is querying all definitions on that _version_ of the quota instead of all versions of the quota (linked by their SID).
This PR updates the form queryset so it gets all definitions on quotas with the same SID as the quota in question. It also changes ordering to be date ascending.
> TP2000-1518 Blocking and suspension period create bug

- tasks/admin.py
* Adding view-only admin support for Task Workflow Templates and Task Templates provides our users with a straightforward interface for viewing all existing instances of task workflow templates and task templates
* Simple summary information is provided for both, such as 'title', 'description', and 'creator' for workflow templates and 'title, 'description', and 'task workflow template ID' (if available) for task templates
* Task templates have a one-to-one relationship with task template items. Task template items are associated with workflow templates, which define the relationship between task templates and associated workflow templates.
* For greater flexibility, task templates can be created standalone without an …
> Tp2000 1542  workflow template admin support

- quotas/forms/wizards.py
Missed correcting the display for the measurement unit qualifier on the previous PR.
Corrects the display for the measurement unit qualifier to be `Code - Description` as per the screenshot below on the Bulk Quota definition create wizard (initial information and edit pages)
> TP-2000-1647 Correcting measurement_unit_qualifier fields

- tasks/admin.py
It would be useful to see at a glance the associated items of workflows and workflow templates in the admin view.
- Adds task and task template counts for both workflow and workflow templates on their admin list views
- Displays associated items inline for both workflow and workflow templates on their admin detail views
<details><summary>Count added to admin list view</summary>
<p>
</p>
</details> 
<details><summary>Inline items displayed on admin detail view</summary>
<p>
</p>
</details>
> TP2000-1652  Enhance workflow, workflow template admin views

- common/models/transactions.py
- workbaskets/tests/test_models.py
- workbaskets/tests/test_views.py
If a workbasket has 2 updates of the same object and it is queued and dequeued, revert_current_version() incorrectly assigns the current version to one of the updates which is about to be turned to draft.
Current version should be either the latest approved version or None.
This PR updates revert_current_version() so when it's querying existing approved versions to revert to, it does not include those in the same workbasket. Also adds a test to confirm the fix works.
> TP2000-1672 Measure current version bug

- workbaskets/tasks.py
- workbaskets/tests/test_tasks.py
* No point checking for missing measures against a comm code that has ended
* Checks comm code validity when checking for missing 103 measures and skips if the end date is in the past
> TP2000-1667: Skip checking of comm codes in workbasket that have already ended

- quotas/views/definitions.py
When viewing quota associations on a quota they sometimes do not show up. This is because the query is filtering for associations on the latest version of the quota. Once the quota gets updated the associations no longer appear as they were added to an older version.
This PR updates all the querysets on the quota data view to filter by SID rather than objects on the latest instance of a quota.
> TP2000-1675 Fix quota association view versioning bug

- workbaskets/jinja2/includes/workbaskets/workbasket-business-rules.jinja
- workbaskets/tests/test_views.py
* When rule check and measures check were both successful it looked as if the rule check reset to not having been run
* Moves logic for measures check in template
> TP2000-1456: Fix logic that displays packaging queue button on rule check page

- measures/duty_sentence_parser.py
- measures/forms/mixins.py
- measures/tests/test_forms.py
- measures/tests/test_lark_parser.py
Currently, the duty sentence parser returns a float value of the inputted number. If the inputted number cannot be accurately stored as a float, this results in it being replaced with a near approximation with many decimal places. This is causing form validation to fail with an unhelpful error message due to too many decimal places, even if the user only inputted a number with 3 decimal places.
For example, 6.5 GBP / kg or 6.75 would be fine but something like 6.667 would get converted to 6.66699999999999981526 (20 decimal places) and then error.
This PR:
- changes the duty sentence parser to return the duty sentence as a Decimal rather than float object
- updates tests to account for it being a decimal now
- adds a check in the form of how many decimal places there are and raises an …
> TP2000-1678-Measure-condition-duty-bug

- measures/duty_sentence_parser.py
- measures/forms/mixins.py
- measures/tests/test_forms.py
- measures/tests/test_lark_parser.py
The validation applied to the `applicable_duty` field in the measure condition form could be applied to all duty sentence fields.
Also the test I previously wrote could be consolidated into an existing test as a new parameter.
This PR:
- moves the check for no more than 3 decimal places from the MeasureCondition form to the Duty Sentence Parser so it can be applied to all duty sentence fields
- moves a test to be a parameter of an existing test
> TP2000-1678 Measure condition duty bug update

- .github/actions/setup-python/action.yml
GitHub `actions/cache@v1` is soon to be deprecated on 1 March 2025.
<details><summary>CI/CD workflow error</summary>
<p>
</p>
</details> 
- Upgrades `actions/cache` from `v1` to `v4` in `.github/actions/setup-python/action.yml`
- https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down
- https://github.com/actions/cache/discussions/1510
> TP2000-1692 Upgrade GitHub actions/cache version

- common/jinja2/common/app_info.jinja
- common/jinja2/common/homepage.jinja
- common/tests/test_views.py
- common/views/pages.py
Application information is a useful tool for us as a product team to check on a number of processes and build information. 
We provided user access as rule checks running weren’t visible, now that we have a rule check queue, we can return this to original settings
This PR makes being a superuser a requirement to view the Application Info page.
> TP2000-1655 Hide application info page

- workbaskets/jinja2/workbaskets/checks/missing_measures.jinja
- workbaskets/tasks.py
- workbaskets/tests/test_checks_views.py
- workbaskets/tests/test_tasks.py
* Some measures that would normally use a measure type 103 instead use a 105 for policy reasons
* Adds measure type 105 to missing measures check. If a comm code has only a measure type 105 the check will now pass
> TP2000-1679-105: Add type 105 to missing measure check

- common/jinja2/common/homepage.jinja
- common/tests/test_views.py
* Users need to be able to access our new Tickets task management functionality
* Providing a 'Tickets' tile for TMs and Superusers navigation
* Modifying text of previous 'Tasks and Workflows' tile to reflect new terminology changes 
* 'Workflows' --> 'Tickets', 'Workflow Templates' --> 'Ticket Templates'
* Conditional rendering based on permissions - the Tickets tile is only visible to TMs and Superusers and 'Ticket Templates' link is only visible to Superusers
* URLs remain unchanged and redirect to 'workflow' related pages
* Parametrized unit test to check that 'Tickets' tile is only visible to TMs and Superusers
* Parametrized unit test to check that 'Ticket Templates' link on 'Tickets' tile only visible to superusers, not TMs
Optionally let reviewers know they need to run migrations …
> UI text changes for new 'tickets' tile on homepage

- checks/models.py
- workbaskets/jinja2/workbaskets/checks/missing_measures.jinja
- workbaskets/models.py
- workbaskets/tests/test_views.py
- workbaskets/views/ui.py
* We already have an override for business rule checks for superusers. This brings the new missing measures check in line with that
* Adds an override button to the missing measures check page that is only visible to superusers. This deletes all associated `MissingMeasureCommCode`s and sets the `MissingMeasuresCheck.successful` to `True`
> TP2000-1668: Add override functionality for superusers

- tasks/jinja2/tasks/workflows/delete.jinja
- tasks/tests/test_views.py
- tasks/views.py
* New UI design changes have renamed 'workflows' to 'tickets', and this PR reflects this change in the delete view
* UI references to 'Workflows' have been changed to 'Tickets' in 'Delete' and 'Confirm Delete' templates
* Updates delete view unit tests
<details>
<summary>Ticket Delete View</summary>
<br>
</details>
<details>
<summary>Ticket Confirm Delete View</summary>
<br>
</details>
- Requires migrations? - No
- Requires dependency updates? - No
> Tp2000 1726  delete ticket view

- common/static/common/scss/_components.scss
- common/util.py
- tasks/forms.py
- tasks/jinja2/tasks/includes/task_list.jinja
- tasks/jinja2/tasks/workflows/confirm_update.jinja
- tasks/jinja2/tasks/workflows/detail.jinja
- tasks/jinja2/tasks/workflows/edit.jinja
- tasks/tests/test_forms.py
- tasks/tests/test_views.py
- tasks/views.py
Users need to be able to edit the new fields that have recently been added to the `TaskWorkflow` (Ticket) model.
- Adds EIF date and policy contact as editable fields to the update form
- Renames "workflow" as "ticket" in UI
- Adds back link on form per design
- Updates related view and form unit tests
- Updates detail view template to display EIF date and policy contact values
- Removes step column headers on ticket detail view following design iteration
<details><summary>Ticket edit view</summary>
<p>
</p>
</details> 
<details><summary>Ticket detail view (displaying new field values)</summary>
<p>
</p>
</details>
> TP2000-1724  Redesign ticket edit view

- measures/jinja2/includes/measures/conditions.jinja
HMRC have reported a bug when searching for measures gives a 500 response. This is because the conditions macro looks for the latest transaction in the workbasket to determine the conditions to show and HMRC users do not have a workbasket.
This PR updates the conditions macro to only check for the latest transaction if a workbasket is present. If not it will set the latest transaction to None which makes the `approved_up_to_transaction` default to the latest approved.
> TP2000-1765-Fix-measures-search-conditions-bug

- tasks/forms.py
- tasks/jinja2/tasks/includes/task_list.jinja
- tasks/models/task.py
- tasks/tests/conftest.py
- tasks/tests/test_forms.py
- tasks/tests/test_models.py
- tasks/tests/test_views.py
- tasks/views.py
Users need the capabilities to add an assignee when creating a new ticket and to edit an assignee of an existing ticket.
- Handles user assignment on ticket create form & view
-  Creates an assignee for the (ticket) summary task in addition to all other associated task instances (steps)
- Handles user assignment on ticket edit form & form
- Same as creation, except task instances (steps) marked as done are not reassigned
- Updates view and form unit tests
- Adds a new queryset method to filter out task instances (steps) that are marked as done
<details><summary>Ticket create form</summary>
<p>
</p>
</details> 
<details><summary>Ticket edit form</summary>
<p>
</p>
</details>
> TP2000-1741  Add ticket assignment to ticket create & edit forms

- workbaskets/tests/test_views.py
The unit `test workbaskets/tests/test_views.py::test_download` has started to fail or failing intermittently because of a missing mandatory parameter to a Boto3 API call, `create_bucket()`.
Provides the mandatory parameter to fix the failing unit test.
> TP2000-1767 Add required param to create_bucket()

- settings/common.py
- tasks/filters.py
- tasks/jinja2/tasks/workflows/confirm_update.jinja
- tasks/jinja2/tasks/workflows/delete.jinja
- tasks/jinja2/tasks/workflows/detail.jinja
- tasks/jinja2/tasks/workflows/edit.jinja
- tasks/jinja2/tasks/workflows/list.jinja
- tasks/models/workflow.py
- tasks/tests/test_filters.py
- tasks/tests/test_models.py
A ticket naming prefix may be desirable as a way of including contextual information when referring to tickets by their ID. For instance, if a prefix of “TC-” (Tariff Change, or other preferred prefix, including the empty string) is adopted, then by referring to TC-123 it’s clear that ticket 123 is being referenced.
This PR adds a configurable TICKET_PREFIX env variable used as the prefix to a ticket PK to form the prefixed_id which is rendered to users whenever a ticket ID is referenced.
It also updates filtering so correct results are returned regardless of case or whether the prefix is included in search.
> TP2000-1744 Support configurable ticket ID prefix

- common/jinja2/includes/common/pagination-list-summary.jinja
- tasks/jinja2/tasks/confirm_delete.jinja
- tasks/jinja2/tasks/confirm_update.jinja
- tasks/jinja2/tasks/delete.jinja
- tasks/jinja2/tasks/detail.jinja
- tasks/jinja2/tasks/edit.jinja
- tasks/jinja2/tasks/workflows/confirm_create.jinja
- tasks/jinja2/tasks/workflows/confirm_delete.jinja
- tasks/jinja2/tasks/workflows/confirm_update.jinja
- tasks/jinja2/tasks/workflows/create.jinja
- tasks/jinja2/tasks/workflows/delete.jinja
- tasks/jinja2/tasks/workflows/detail.jinja
- tasks/jinja2/tasks/workflows/edit.jinja
- tasks/jinja2/tasks/workflows/list.jinja
- tasks/jinja2/tasks/workflows/task_template_confirm_create.jinja
- tasks/jinja2/tasks/workflows/task_template_confirm_delete.jinja
- tasks/jinja2/tasks/workflows/task_template_confirm_update.jinja
- tasks/jinja2/tasks/workflows/task_template_delete.jinja
- tasks/jinja2/tasks/workflows/task_template_detail.jinja
- tasks/jinja2/tasks/workflows/task_template_save.jinja
- tasks/jinja2/tasks/workflows/template_list.jinja
- tasks/static/tasks/scss/_tasks.scss
- tasks/tests/test_views.py
- tasks/urls.py
- tasks/views.py
A coherent page hierarchy and user navigation experience is required on ticket and step pages.
- Amends the breadcumbs on all ticket, ticket template, step and step template pages
- Updates button text and links on confirmation pages
- Renames old references to workflows and tasks on pages
> TP2000-1775  Amend breadcrumbs on ticket and step pages

- commodities/jinja2/includes/commodities/tabs/hierarchy.jinja
Basing the style assignment on the comm.indent didn't catch all circumstances where the styles should be assigned. They are now assigned based on the comm.code not being '00' (ie. being a positive value)
> FIX-Style assignment for comm code indentations

- common/static/common/scss/_quota-definitions.scss
- common/templates/common/widgets/radio_conditional_commodities.html
- common/widgets.py
- quotas/forms/wizards.py
- quotas/tests/test_forms.py
- quotas/tests/test_views.py
Annually recurring QuotaDefinitionPeriods can increase or decrease by a numerical or percentage value from the previous year.
This feature calculates the value of a QuotaDefinitionPeriod volume based on the value of the previous year's volume and a provided figure, either as a percentage or an amount.
The widget used is a custom RadioSelect widget that uses elements of two GDS radio select widgets, the radio select with text divider and the radio select with conditionally revealed inputs. Documentation on these can be found [here](https://design-system.service.gov.uk/components/radios/)
The user is presented with five options, no change or for the figure to increase or decrease by amount or percentage. Choosing an option that changes the volume opens an input field for a value, either …
> TP-2000-1784 annual volume changes for recurring QuotaDefinitionPeriods

- common/jinja2/common/homepage.jinja
* Implementing TAP ticketing ID prefixes in the UI 
* Adding in ticket prefix to ticket ID on a user's 'my tickets' card on the homepage
- Requires migrations? - No
- Requires dependency updates? - No
<details open>
<summary>Updated 'Tickets' homepage card</summary>
<br>
</details>
> added prefixed id back to homepage ticket card
